### ISSUE TITLE
TRC:Native Token Standard

### ISSUE THREAD

**Issue by zhaohong** [tronprotocol/tips#10]

**Comment by zhaohong** [comment]
```
tip: 10
title: TRC-10 Native Token Standard
author: Marcus Zhao(@zhaohong ) <zhaohong229@gmail.com> 
discussions to: https://github.com/tronprotocol/TIPs/issues/10
status: Draft
type: Standards Track
category: TRC
created: 2018-12-20
```

**Comment by chiro-hiro** [comment]
**start_time** and **end_time** should be `unsinged integer` unix time stamp.
According to [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem) then It should be 64 bits.

Is **decimals** missing?

**Comment by zhaohong** [comment]
@chiro-hiro  thanks for the reminder
