### ISSUE TITLE
Discussion: implement the shielded token contract

### ISSUE THREAD

**Issue by Federico2014** [tronprotocol/tips#135]
## Background

For TRC-20 token contract,  it allows users to issue and transfer tokens, but it can not guarantee the privacy, since  it leaks the token ownership. When transfering the token, the source and destination address, and the token amount are also public.  Transaction privacy protection is quite important  for blockchain. So we may need the shielded token contract,  it will attract more users by providing better privacy for token transactions and promote the widespread adoption of  TRC-20 token and related DApps.

## Motivation

We plan to implement the  shielded token contract, which aims to provide users better privacy for token ownership and transactions.  It can transform public TRC-20 token to shielded token, transfer the shielded tokens and transform the shielded the token back to the public TRC-20 token. The technology implemention of shielded token contract can be based on zk-SNARK proof system, to make it  secure and efficient.

**Comment by shydesky** [comment]
An imaginative design, I think. By the way, is this mean the TRC20 token owners must re-deploy a new contract to issue a new TRC20 token for the replacement of the old one?

**Comment by Federico2014** [comment]
> An imaginative design, I think. By the way, is this mean the TRC20 token owners must re-deploy a new contract to issue a new TRC20 token for the replacement of the old one?

A new contract needs to be depolyed, but may not by the TRC20 token owners. Anyone else can deploy it. And the new contract is not the replacement of the old one, it just transform the public TRC20 token into shielded form and  the shielded form can also transformed back to the public TRC20 token

**Comment by Benson0224** [comment]
since additional transform is needed during TRX20 transfer, will this impact the overall performance? can you share some test report on this part if you have, thanks.

**Comment by Federico2014** [comment]
> some

**Comment by shydesky** [comment]
> A new contract needs to be depolyed, but may not by the TRC20 token owners. Anyone else can deploy it. And the new contract is not the replacement of the old one, it just transform the public TRC20 token into shielded form and the shielded form can also transformed back to the public TRC20 token

Can I regard the new contract as a tool providing the function that converts the trc20 token and "shield data" back and forth?

**Comment by Federico2014** [comment]
> since additional transform is needed during TRX20 transfer, will this impact the overall performance? can you share some test report on this part if you have, thanks.

The public TRC20 token first need to be transformed into shielded form, then for shielded token transactions, it is more complex than the public TRC20 transactions. According the test,  it takes about 9~20 ms

**Comment by Federico2014** [comment]
> > A new contract needs to be depolyed, but may not by the TRC20 token owners. Anyone else can deploy it. And the new contract is not the replacement of the old one, it just transform the public TRC20 token into shielded form and the shielded form can also transformed back to the public TRC20 token
> 
> Can I regard the new contract as a tool providing the function that converts the trc20 token and "shield data" back and forth?

Yes, it can also the support the shielded token transactions, and the source and destination address, and amount in the transaction is invisible to the public

**Comment by shydesky** [comment]
Are there any mature solutions for transferring tokens anonymously? I never seem to have heard of making anonymous transfers by the smart contracts.

**Comment by Benson0224** [comment]
will the token amount also be transformed into another format?

**Comment by Federico2014** [comment]
> will the token amount also be transformed into another format?

yes, it needs be transformed into encrypted form, like the note commitment

**Comment by Federico2014** [comment]
> Are there any mature solutions for transferring tokens anonymously? I never seem to have heard of making anonymous transfers by the smart contracts.

Currently, some teams are working on it, like the projects such as AZTEC, EYBlockchain, and tornado.cash. We put forward the scheme by a comprehensive research of the latest technology progress

**Comment by Federico2014** [comment]
We have completed the TIP draft for shielded token contract.  Please refer the PR: https://github.com/tronprotocol/tips/pull/132/files

**Comment by shydesky** [comment]
```
constructor(address _trc20Token) public {
    _owner = msg.sender;
    trc20Token = TRC20Interface(_trc20Token);
}```

the param "_trc20Token" means the token waiting for shielded?
the "TRC20Interface" is a contract with the three functions "mint, transfer, burn"?

**Comment by Federico2014** [comment]
> ```
> constructor(address _trc20Token) public {
>     _owner = msg.sender;
>     trc20Token = TRC20Interface(_trc20Token);
> }```
> 
> the param "_trc20Token" means the token waiting for shielded?
> the "TRC20Interface" is a contract with the three functions "mint, transfer, burn"?
> ```

`_trc20Token` is the TRC-20 token  contract address,  it's used to binding the shielded token contract. There may be many TRC-20 tokens,  so one TRC-20 token can has its correspondent shielded token contract by the constructor.

**Comment by Federico2014** [comment]
I have updated the draft, please refer #139

**Comment by Benson0224** [comment]
does “shielded token contract” only apply to TRC-20 transfer contract? or it can be used for all transfer contract?

**Comment by Federico2014** [comment]
> does “shielded token contract” only apply to TRC-20 transfer contract? or it can be used for all transfer contract?

What do mean for all transfer contract, can you show some examples,  I am not sure about it

**Comment by Benson0224** [comment]
> > does “shielded token contract” only apply to TRC-20 transfer contract? or it can be used for all transfer contract?
> 
> What do mean for all transfer contract, can you show some examples, I am not sure about it

I mean we have Token 10 and Token 20, is this shielded token contract only work for token 20, right?

**Comment by Federico2014** [comment]
> > > does “shielded token contract” only apply to TRC-20 transfer contract? or it can be used for all transfer contract?
> > 
> > 
> > What do mean for all transfer contract, can you show some examples, I am not sure about it
> 
> I mean we have Token 10 and Token 20, is this shielded token contract only work for token 20, right?

It works for Token 10 and the shielded TRC10 transaction has already been implemented.

**Comment by chenluyong** [comment]
Is there a sample program to meet my requirements for the `Shielded Token Contract` test?
I want to execute procedures that do not involve third-party APIs, except for `Tron Node`.
The sample application will help developers better understand and control the process.
Just like [`tronpy`](https://github.com/andelf/tronpy)

**Comment by Federico2014** [comment]
> Is there a sample program to meet my requirements for the `Shielded Token Contract` test?
> I want to execute procedures that do not involve third-party APIs, except for `Tron Node`.
> The sample application will help developers better understand and control the process.
> for example just like [`tronpy`](https://github.com/andelf/tronpy).
> 
> I found [How to Use Shielded Smart Contracts](https://developers.tron.network/docs/how-to-use-tronz).
> This is a good guide, but it's not what I need because it relies on the HTTP interface and I want it to be built locally.
> 
> I saw that [TIP-135](https://github.com/tronprotocol/documentation-en/blob/master/docs/mechanism-algorithm/shielded-TRC20-contract.md) was also done using the API, If it can only rely on a third party interface to run, is there a sample program?

You can reference the wallet-cli command:
https://github.com/tronprotocol/wallet-cli#How-to-transfer-shielded-TRC20-token
Also with a demo: https://github.com/tronprotocol/wallet-cli/blob/develop/src/main/java/org/tron/demo/ShieldedTRC20Demo.java

**Comment by chenluyong** [comment]
Is there a `Python` of the SDK available?

> You can reference the wallet-cli command:
> https://github.com/tronprotocol/wallet-cli#How-to-transfer-shielded-TRC20-token
> Also with a demo: https://github.com/tronprotocol/wallet-cli/blob/develop/src/main/java/org/tron/demo/ShieldedTRC20Demo.java

**Comment by Federico2014** [comment]
> Is there a `Python` of the SDK available?
> 
> > You can reference the wallet-cli command:
> > https://github.com/tronprotocol/wallet-cli#How-to-transfer-shielded-TRC20-token
> > Also with a demo: https://github.com/tronprotocol/wallet-cli/blob/develop/src/main/java/org/tron/demo/ShieldedTRC20Demo.java

 No python SDK.
