### ISSUE TITLE
Discussion: add the Pedersen hash function in the shielded token contract

### ISSUE THREAD

**Issue by Federico2014** [tronprotocol/tips#138]
## Background 

In order to implement shielded transaction for [TRC-20](https://github.com/tronprotocol/TIPs/blob/master/tip-20.md) token,  We plan to  develop the shielded token contract and  it needs the Merkle tree construction and proof, which needs the Pedersen hash compution. So providing the Pedersen hash function `PedersenHash` is nesscessary for shielded contract implementation.

## Motivation 

In order to implement to Pedersen hash computation in shielded token contract,  we want to introduce the `PedersenHash` function, which can be  used for compuation of Merkle tree node value in shielded contract.  The  function can be implemented in precompiled contract form.

**Comment by Benson0224** [comment]
what is the advantage of Pedersen Hash compared to SHA256 hash?

**Comment by shydesky** [comment]
is the Pedersen hash computation time-consuming operation？I think the transaction processing time is limited in 50ms.

**Comment by Federico2014** [comment]
> what is the advantage of Pedersen Hash compared to SHA256 hash?

The  Pedersen hash can be more efficient for Merkle tree node value computation than SHA256

**Comment by Federico2014** [comment]
> is the Pedersen hash computation time-consuming operation？I think the transaction processing time is limited in 50ms.

The Pedersen hash come from the Zcash protocol, used for Merkle tree node value compuation in shielded transactions.  We use it here because it is more efficient than SHA256

**Comment by shydesky** [comment]
#135

**Comment by shydesky** [comment]
Cool, I think the Pedersen hash is an excellent way to build the Merkle tree.

**Comment by Federico2014** [comment]
> The Pedersen hash, compared with the SHA256, maybe an excellent way to build the Merkle tree. But a proper test for performance is needed, I think. The transaction will be regarded as the long-running transaction which may lead that it can not be packed in the block.

In the shielded token transaction,  the zero-knowledge proof verification costs much more time. So Pedersen hash is used to save the time in order to avoid the long-running transaction. We will do the performance test for the overall shielded token transaction soon.

**Comment by Benson0224** [comment]
Thank everyone for contributing to this issue. 
This issue will be closed as it is already included in [TIP-138](https://github.com/tronprotocol/tips/blob/master/tip-138.md) and implemented in [GreatVoyage-v4.0.0](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.0.0)
