### ISSUE TITLE
Discussion: TRC10 And TRC20 Conversion Contract Standard

### ISSUE THREAD

**Issue by sean-liu55** [tronprotocol/tips#154]
## Background
As stated in the issue https://github.com/tronprotocol/tips/issues/153, we need a conversion method that can convert between TRC10 and TRC20 to support TRC20 trading in Tron DEX. 

## Motivation 
The conversion method through a smart contract seems to be a more feasible, simple, and safe method. 

 With this standard, all TRC20 issuers or trusted third parties can independently create a platform for TRC20 to TRC10 conversion. Ordinary users can also convert TRC20 to TRC10 in this trusted way, and then conveniently trade in Tron DEX.

If there is no standard, each issuer may design its own contract with potential security risks, and it is difficult for users to verify the security of conversion contracts issued by the issuer.

So maybe we need a contract standard.

**Comment by shydesky** [comment]
#153

**Comment by shydesky** [comment]
what is the meaning of "a contract standard"? Does it need to be supported by the blockchain, or we can think it is just a standard likes TRC20 in which users can comply with it by defining specific functions(for example, transfer, transferFrom)?

**Comment by mattopolitan** [comment]
@shydesky has just posted a great concern for the "Contract Standard", and it had to be done by functions within the blockchain. If it's only a suggested standard, I'm afraid that not everyone would follow the exact standard, and it's really hard to regulate & verify these contract, which poses a great threat to our Tron community.

**Comment by shydesky** [comment]
@mattopolitan  I am not sure whether this contract standard is mandatory or not. I think there is not any existing methods that can convert the TRC20 token to TRC10 token. Theoretically, it should be workable if you define some special commands supported by the TVM.

**Comment by kuailz** [comment]
Why can't you make a decentralized platform for trading the TRC20 token directly? This may confuse users. I think a lot of people can not distinguish the TRC10 token with TRC20 token right now.

**Comment by mattopolitan** [comment]
@shydesky A contract standard is a must, or there will be too many scammy / fraudulent contracts  coming out, poses threat to our community. And we have to define & implement sufficient commands / functions in TVM to support with these standards.

**Comment by kuailz** [comment]
> @shydesky A contract standard is a must, or there will be too many scammy / fraudulent contracts coming out, poses threat to our community. And we have to define & implement sufficient commands / functions in TVM to support with these standards.

I agree with you. Some hackers may deploy malicious contract code which can steal the users' assets or tokens. But can we determine that the contract is verified and don't do something illegal? What I mean is we should ensure the deployed contract code must be checked. It is very important for users.

**Comment by zhangwenhua-tron** [comment]
@shydesky @mattopolitan @kuailz In order to support TRC20 trading in Tron DEX which is based on the system contract, we need to convert TRC20 to TRC10, after that, users can trade the converted TRC10 in Tron DEX as mentioned in [#153.](https://github.com/tronprotocol/tips/issues/153).
Therefore, we need a smart contract to convert TRC20 to TRC10 or to convert TRC10 back to TRC20, and this requires some standards to ensure security and credibility.

**Comment by zhangwenhua-tron** [comment]
> Does it need to be supported by the blockchain, or we can think it is just a standard likes TRC20 in which users can comply with it by defining specific functions(for example, transfer, transferFrom)?

@shydesky We will make some rules and add some basic commands in TVM, so it is supported by the blockchain, it likes TRC20 in some aspects.

**Comment by zhangwenhua-tron** [comment]
> Why can't you make a decentralized platform for trading the TRC20 token directly? This may confuse users. I think a lot of people can not distinguish the TRC10 token with TRC20 token right now.

@kuailz Tron DEX just supports TRC10 right now and it is difficult to support TRC20 trades directly, so we need to convert TRC20 to TRC10. You can get more info about Tron DEX in [tip #127](https://github.com/tronprotocol/tips/issues/127) and [issue #153](https://github.com/tronprotocol/tips/issues/153).

**Comment by behilter** [comment]
hello, I am studying for a master's degree in computer science, and I am working on blockchain-related topics.  I am very interested in the Tron blockchain. I want to know how to begin with the Tron blockchain. I read your discussion and I'd like to ask if you'll do some development. Could I join you?

**Comment by mattopolitan** [comment]
Welcome @behilter. Tron is an open source project, so everyone could join & contribute. I'd suggest you to clone the [java-tron](https://github.com/tronprotocol/java-tron) project first, try setting up a private net or as a test node by following the [deployment guide](https://tronprotocol.github.io/documentation-en/developers/deployment/). When everything's set, you could try out the [http api](https://tronprotocol.github.io/documentation-en/api/http/) call and see how things work :)
