### ISSUE TITLE
Discussion: Allow Issuing TRC10 In Contract 

### ISSUE THREAD

**Issue by sean-liu55** [tronprotocol/tips#155]
## Background
As stated in the issue https://github.com/tronprotocol/tips/issues/153 and issue https://github.com/tronprotocol/tips/issues/154. It is necessary to support the conversion of TRC10 and TRC20, and supporting this conversion through a smart contract should be a safe and feasible method.

## Motivation  
 
Contract security is a key factor. This conversion contract should be strictly bound to the converted TRC10 and TRC20, and cannot be modified once set. Therefore, users do not have to worry about the issuer adjusting the TRC10 and TRC20 within the contract after the contract is issued.

If the contract can issue TRC10, all corresponding TRC10 belong to this contract instead of the issuer, and the issuer cannot change and operate TRC10 in the contract. This ensures the safety of the conversion contract.

Therefore, the function of issuing TRC10 in the contract should be supported.

**Comment by zhang2853** [comment]
Is that to say, each Contract needs to issue a TRC10 token if they want to use Tron-DEX?   is this done automatically when the Contract trigger Tron-DEX?

**Comment by mattopolitan** [comment]
@zhang2853 In order to make TRC20 to be supported in Tron-DEX, from my understanding, yes. It will be a 1 to 1 token conversion between TRC10 and TRC20 and everything is automatically done by the contract for safety reasons. Yet the contract itself should also be verified & created by functions within the blockchain, which is a prerequisite of this issue and yet to be implemented.

**Comment by Benson0224** [comment]
it sounds quite complicated.  if it is 1 to 1 token conversion, does it mean that Transfer TRC20 will also lead to TRC10 transfer?

**Comment by zhang2853** [comment]
> @zhang2853 In order to make TRC20 to be supported in Tron-DEX, from my understanding, yes. It will be a 1 to 1 token conversion between TRC10 and TRC20 and everything is automatically done by the contract for safety reasons. But the contract itself should also be verified & created by functions within the blockchain, which is a prerequisite of this issue and yet to be implemented.

can you please give an overall working flow how this conversion? or what is your proposal? 
1. When will TRC20 be converted to TRC10? 
2. Will these new TRC10 tokens be transferred to users who own the corresponding TRC20?

**Comment by kuailz** [comment]
> quite complicated. if it is 1 to 1 token conversion, does it mean that Transfer TRC20 will also lead to TRC10 transfer?

I think the conversion may only happens when you want to trade the TRC20 token on the Tron-DEX. It seems that we should freeze some TRC20 tokens in the contract temporarily and then "produce" some TRC10 tokens. After the TRC10 tokens deal done, the TRC10 token's buyer can unfreeze those TRC20 tokens.

**Comment by sean-liu55** [comment]
@zhang2853 
When this conversion contract is ready, including banding TRC20 and issuing the corresponding TRC10, users could transfer TRC20 to this contract and receive the TRC10.

**Comment by sean-liu55** [comment]
@mattopolitan, because of the different precise supported between TRC10 and TRC20, the conversion rate may not be 1:1, which is decided by contract issuer. In most cases, this ratio is 1: 1

**Comment by sean-liu55** [comment]
@Benson0224 , the holder of the TRC20 should not receive the corresponding TRC10 automatically, so Transfer TRC20 will not lead to TRC10 transfer.

**Comment by zhangwenhua-tron** [comment]
> > @zhang2853 In order to make TRC20 to be supported in Tron-DEX, from my understanding, yes. It will be a 1 to 1 token conversion between TRC10 and TRC20 and everything is automatically done by the contract for safety reasons. But the contract itself should also be verified & created by functions within the blockchain, which is a prerequisite of this issue and yet to be implemented.
> 
> can you please give an overall working flow how this conversion? or what is your proposal?
> 
> 
> 2. Will these new TRC10 tokens be transferred to users who own the corresponding TRC20?

For users who own the the corresponding TRC20, if they want to receive the TRC10, they should trigger the smart contract to convert their TRC20 tokens to TRC10 tokens.
It will not be done automatically.

**Comment by kimjimin5021** [comment]
> > quite complicated. if it is 1 to 1 token conversion, does it mean that Transfer TRC20 will also lead to TRC10 transfer?
> 
> I think the conversion may only happens when you want to trade the TRC20 token on the Tron-DEX. It seems that we should freeze some TRC20 tokens in the contract temporarily and then "produce" some TRC10 tokens. After the TRC10 tokens deal done, the TRC10 token's buyer can unfreeze those TRC20 tokens.

Excuse me, is this freezing at least 3 days like what I do in Tronscan? Or I could use a shorter timestamp parameter in a freezing function, then unfreeze it when the deal is done?

**Comment by sean-liu55** [comment]
@kimjimin5021, I think there is no need to set a lock time, you may redeem TRC20 tokens at any time. "Freeze" here only means putting the TRC20 tokens in this contract.
