### ISSUE TITLE
TRC 16: Multi-signature

### ISSUE THREAD

**Issue by zk19862018** [tronprotocol/TIPs#16]
```
tip: 16
title: Account Multi-signature
author: Marcus Zhao(@zhaohong ) <zhaohong229@gmail.com> 
discussions to: https://github.com/tronprotocol/TIPs/issues/16
status: Draft
type: Standards Track
category: TRC
created: 2018-12-27
```
## Simple Summary

This doc describes the  standard interface of Account Multi-signature

## Abstract

Standard transactions on cryptocurrency networks can be called single-signature transactions, because they require only one digital signature for transaction to be done. Multi-signature is the requirement that signatures of the transactions must reach the weight customized before they can be executed. 
Once an owner account is created, roles can be added to the account, each role has a signature weight. The owner account has a signature weight threshold, if all the signatures weight from the roles added up reach the threshold, the transactions made by the owner address can be executed.
Different roles can be set different signature permissions.

Scenario 1: 

Alice is running a company, he creates an owner account as his company fund account. Alice adds Bob(Accountant), Carol(CFO) and Alice(CEO) into his account. Bob's signature weight is 2, Carol's signature weight is 2, Alice's signature weight is 5. The owner account's signature weight threshold is 3. Alice's signature weight is bigger than the threshold(5>3), so his only signature is sufficient to make transactions.  Bob's signature weight is smaller than the threshold(2<3), to make a transaction, Bob needs Carol's or Alice's signature, if Carol approves, the total signature weight is 2+2>3, so the transaction can be executed.

After Alice add Bob's account into his owner account, he can set Bob's signature permissions, such as Bob can only make transfer transactions or other types of transactions. Same rules apply to Carol.

Scenario 2: 

(Previous Scenario)
Alice has many TRX assets. One day, misfortune has come, Alice is dead due to an accident. He is the only one who holds the private key of his account, so his assets will stay in that account forever, nobody can get it.
(Current Scenario)
Alice has many TRX assets. He adds his wife and son's accounts into his account, and give them the permission to operation his account. So after Alice no long exists, his family members can still operate his account.

Scenario 3:

Alice is running a company, he creates an owner account as his business account. Alice adds Bob(Accountant), Carol(CFO) and Alice(CEO) into his account. Alice gives them the permissions to operation his business account. One day, Bob resigns. To keep Alice's account safe, Alice can remove Bob's account from his business account, then Bob can not operate his account any more.

## Motivation

1. Support account Access Control Based on Roles;
2. Account can be controlled by several private keys, in case of private key lost;

#### AccountPermissionUpdate
 * @param owner_address 
 * @param permissions 
  { 
  string name = 1;
  int64 threshold = 2;
  string parent = 3;
  repeated Key keys = 4;
 }
 * @return The transaction

#### PermissionAddKey
 * @param owner_address 
 * @param key
 {
  bytes address = 1;
  int64 weight = 2;
 }
 * @param permission_name 
 * @return The transaction

#### PermissionUpdateKey
 * @param owner_address 
 * @param key
 {
  bytes address = 1;
  int64 weight = 2;
 }
 * @param permission_name 
 * @return The transaction

#### PermissionDeleteKey
 * @param owner_address 
 * @param key_address
 * @param permission_name 
 * @return The transaction

#### GetSignWeight
 * @param transaction 
 * @return The transaction sign weight

#### AddTransactionSign
 * @param transaction 
 * @return The transaction

**Comment by olenheim** [comment]
If we support multi-signature  we must refator multi-validating signature module, we can discuss here
https://github.com/tronprotocol/java-tron/issues/1889

**Comment by lvs007** [comment]
We can only package one transaction for the same account at the time of the block.
