### ISSUE TITLE
CHAINID instruction

### ISSUE THREAD

**Issue by taihaofu** [tronprotocol/tips#174]
## Background

Cross chain solution and side chain solution will provide more than one single chain for TRON ecosystem. But transaction can be the same on different chains, which will lead relay attack for TRON. We need to give a chain id to distinguish them and also provide a CHAINID instruction in TVM level.

## Implementation
We can define chain id as the genesis block hash(id). 

## Solidity code
```
function getId() public view returns(uint256){
        uint256 id;
        assembly {
            id := chainid()
        }
        return id;
}
```

**Comment by Benson0224** [comment]
Thank everyone for contributing to this issue. 
This issue will be closed as it is already included in [TIP-174](https://github.com/tronprotocol/tips/blob/master/tip-174.md)
