### ISSUE TITLE
SELFBALANCE Instruction in TRON

### ISSUE THREAD

**Issue by taihaofu** [tronprotocol/tips#175]
## Background

A TRON version of SELFBALANCE should be defined, so that we can reduce energy cost for smart contracts and adaptive to new compiler.

## Implementation
use selfbalance instead of balance when calling `address(this).balance`

this should return the current balance of the smart contract.

The energy cost can be different from `BALANCE`, for now is recommended to defined as 20 Energy.

**Comment by Benson0224** [comment]
Thanks for contributing to this issue. 
This issue will be closed as it is already included in [TIP-175](https://github.com/tronprotocol/tips/blob/master/tip-175.md)
