### ISSUE TITLE
altbn128 precompile contract energy reduction

### ISSUE THREAD

**Issue by taihaofu** [tronprotocol/tips#176]
## Background

As more teams are going to use altbn128 in their smart contract, a energy reduction is required to re-design the energy cost for altbn128 precompile contracts.
.

## Implementation

Reduce 3 functions:

1. `Addition` `500`-> `150`
2. `Multiplication` `40000` -> `6000`
3. `Paring` `80000 * pairs + 100000` -> `34000 * pairs + 45000`

**Comment by Benson0224** [comment]
Thanks for contributing to this issue. 
This issue will be closed as it is already included in [TIP-176](https://github.com/tronprotocol/tips/blob/master/tip-176.md)
