### ISSUE TITLE
TRC10 issue in smart contract

### ISSUE THREAD

**Issue by taihaofu** [tronprotocol/tips#178]
## Background

Asset issue is a system contract and an trc10 asset can be issued by private-key accounts. But, for some scenarios like a decentralized exchange, they may prefer to issue trc10 in smart contracts. TVM need to provide this functionality to developers.

## Implementation

Basically we need at least 2 Instructions:
* `TOKENISSUE`          
* `UPDATEASSET`    

`TOKENISSUE` should be the same as assetissuecontract in system contract. Also require to burn 1024 TRX for new TRC10 token.

`UPDATEASSET`should be used to update abbreviations, description etc.

**Comment by kropple** [comment]
how about creating the trc10 with 99999999999999 tokens and the contract holds the excess tokens and sends trc10 tokens to the user when needed?
only downside i see in that, that the circulating supply number is wrong then, but can be calculated by "ciriculating supply minus contract reserve amount"

**Comment by yanghang8612** [comment]
We do not have further implemention plan.
So we close this issue.
