### ISSUE TITLE
Standard Interface Detection In Contract

### ISSUE THREAD

**Issue by timothyckw** [tronprotocol/tips#200]
## Simple Summary

A standard method to publish and detect what interfaces a smart contract has implemented.

## Abstract

This TIP scandalizes the interface detection, checking contract if implement TRC165.

## Motivation

There is not a standard interface to query or check the contract if it supports a specific interface on Tron. It's inconvenient to interact with smart contracts without standard. Here is an example of why we need to standardize the interface as below. 

Imagining that somebody issued a standard TRC20 contract. Callers can check the interface - totalSupply(), balanceOf(address who) through browser - tronscan.org firstly to verify the interfaces of the contract before communication. But, are there any other methods to check the interfaces except browser or read the contract? The answer is "no". So, it is necessary to provide a standard to solve this kind of issue by contract. That means we can detect the interface directly in smart contract if implemented.

```solidity
pragma solidity ^0.4.23;

/**
 * @title TRC20 interface (compatible with ERC20 interface)
 * @dev see https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md
 */
interface ITRC20 {
    function totalSupply() external view returns (uint256);

    function balanceOf(address who) external view returns (uint256);

    function allowance(address owner, address spender)
    external view returns (uint256);

    function transfer(address to, uint256 value) external returns (bool);

    function approve(address spender, uint256 value)
    external returns (bool);

    function transferFrom(address from, address to, uint256 value)
    external returns (bool);

    event Transfer(
        address indexed from,
        address indexed to,
        uint256 value
    );

    event Approval(
        address indexed owner,
        address indexed spender,
        uint256 value
    );
}
```

On the other hand, EIP-165 solved the above issue, which can check the target interface if it exists through ERC165. The standard (EIP-165) has been implemented successfully on ETH. Thus, we would like to achieve a similar standard on Tron.

**Comment by KI5FPL** [comment]
ERC1820 is also needed.

**Comment by timothyckw** [comment]
> ERC1820 is also needed.
Thanks for your suggestion. The standard of TRC165 seems to still have some limitations. And we will continue to improve this standard. ERC1820 is the latest proposal for the ERC165 and ERC672. I think ERC1820 is pretty good, too.

**Comment by yanghang8612** [comment]
TRC-165 has been marked as `Final`.
So we close this issue.
