### ISSUE TITLE
Non-Fungible Token Standard

### ISSUE THREAD

**Issue by timothyckw** [tronprotocol/tips#201]
## Simple Summary

A standard interface for non-fungible tokens.

## Abstract

A standard API to implement non-fungible tokens within smart contracts. Basic functionality, track and transfer ownership of NFTs will be provided.

## Background

Users could issue ERC721 (Non-Fungible Token) on Ethereum chain from 2018. However, Tron still doesn't have standardized NFT tokens nowadays. In particular, DeFi became more and more popular this year. It can bring more economic value if integrating NFTs with DeFi as well. Like cryptokitties. On the other hand, the community will have more choices for different kinds of tokens to issue or buy. Therefore, we hope that we can standardize TRC721 on Tron. Based on the standard, we can track and transfer ownership of NFTs.

## Motivation

Non Fungible Token is entirely different from TRC20. The main point is that each NFT token have unique ID to represent. It can't be replaced and split. For example, houses, furniture and diamond. However, we can transfer the ownership of those properties or assets. Under TRC721 standard, we can transfer the property as a unique (uint256) token. In addition, NFT token is inspired from TRC20. It could compensate the weakness of TRC20. This is much like playing an online game. We need to pay for some weapon. The property or value of a weapon can be very different. TRC721 looks like the value of a weapon.

A standard interface which allows NFTs on Tron. Standardized wallets can track the NTFs and can be traded in exchanges.

**Comment by KI5FPL** [comment]
How about erc-2309?

**Comment by timothyckw** [comment]
> How about erc-2309?

That is an exciting proposal. It allows users to mint a large number of non-fungible tokens in a single transaction. The proposal helps to improve the cost and speed of transaction. We will process similar proposal as soon as possible.

**Comment by Lredhdx** [comment]
How to transfer NFT? Is it different with trc20?

**Comment by timothyckw** [comment]
> How to transfer NFT? Is it different with trc20?

Firstly, we provide two kinds of transfer functions in NTF standard as follow and suggest using safeTransferFrom instead of transferFrom: 

1. safeTransferFrom(address _from, address _to, uint256 _tokenId)
   - Transfer `tokenId` token from `from` to `to` Safely.  Prevent tokens from being forever locked by checking first that contract recipients are aware of the TRC721 protocol.
2. transferFrom(address _from, address _to, uint256 _tokenId)
   - Transfers `tokenId` token from `from` to `to`.

Requirements:

- `from` cannot be the zero address.
- `to` cannot be the zero address.
- `tokenId` token must exist and be owned by `from`

Secondly, TRC721 is different from TRC20. And it's more complex than TRC20. In other words, NTF token is unique and can have different value than other token from the same contract. NFT projects like CryptoPunks, Curio Cards and Rare Pepe.

**Comment by bruffstar** [comment]
Do we have any news on when Tronscan, Tronlink, etc. will be updated to be able to accomodate TRC721 tokens, in terms of, for example, displaying `tokenId`, meta data, etc.

Also, are there any TRC721 projects already out there in the wild?

**Comment by timothyckw** [comment]
> Do we have any news on when Tronscan, Tronlink, etc. will be updated to be able to accomodate TRC721 tokens, in terms of, for example, displaying `tokenId`, meta data, etc.
> 
> Also, are there any TRC721 projects already out there in the wild?

1. Both Tronscan and Tronlink are unable to accomodate TRC721 tokens so far. 
2. The TRC721 related projects seems still under development in the community.

**Comment by yanghang8612** [comment]
TRC-721 has been marked as `Final`.
So we close this issue.
