### ISSUE TITLE
MAX_FEE_LIMIT Should be Adaptive

### ISSUE THREAD

**Issue by Lredhdx** [tronprotocol/tips#204]
## Simple Summary

MAX_FEE_LIMIT Should be Adaptive.

## Background
Currently, the max_fee_limit is fixed and cannot be changed. As the energy changes，
In some cases, max_fee_limit may be insufficient. So we should change max_fee_limit 
base on needs.

**Comment by jeancky** [comment]
Yes, this proposal makes sense.

MAX_FEE_LIMIT is now valued in TRX.  If the energy-price changed, the maximum amount of energy available for a transaction will be affected.

I suggest this time to use the energy unit directly.

**Comment by Benson0224** [comment]
Thanks for contributing to this issue. 
This issue will be closed as it is already included in [TIP-204](https://github.com/tronprotocol/tips/blob/master/tip-204.md) and implemented in [GreatVoyage-v4.1.2](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.1.2).
