### ISSUE TITLE
Solidity Should Update to 0.6.0

### ISSUE THREAD

**Issue by Lredhdx** [tronprotocol/tips#209]
## Simple Summary

Solidity should update to 0.6.0 for developing better.

## Background

In order to develop better on TRON, solidity 0.6.0 should add more new features.We should disallow explicit conversions from external function types to address and add a member called address to them as replacement.We are supposed to enable Yul optimizer as part of standard optimization and add new reserved keywords: override, receive, and virtual.We should split unnamed fallback functions into two cases defined using fallback() and receive() as so on.

**Comment by jeancky** [comment]
Do we plan to support all features of Solidity 0.6.0 upon Tron-VM?

**Comment by yanghang8612** [comment]
> Do we plan to support all features of Solidity 0.6.0 upon Tron-VM?

Most features will be supported expect some try-catch cases such as assert and exceptions.

**Comment by Guhaaa** [comment]
Are there any updates for this issue?

**Comment by yanghang8612** [comment]
> Are there any updates for this issue?

Firstly, if you want to know new features and changes about solidity-v0.6.0 in tron, please see [tip-209](https://github.com/tronprotocol/tips/blob/master/tip-209.md) for more information.
Secondly, you can download [solc-bin](https://github.com/tronprotocol/solidity/releases/tag/tv_0.6.0) to complie your smart contract written with solidity-v0.6.0 and deploy it to tron network.
Questions are welcome!😊

**Comment by Benson0224** [comment]
Thanks for contributing to this issue. 
This issue will be closed as it is already included in [TIP-209](https://github.com/tronprotocol/tips/blob/master/tip-209.md) and implemented in [GreatVoyage-v4.1.2](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.1.2).
