### ISSUE TITLE
SRs reward system "Caishen"

### ISSUE THREAD

**Issue by ghost** [tronprotocol/tips#221]
### Reality

The current awards given to each SR include 16 TRX for block production and 160 TRX for voting. Transaction fees on the TRON network are based on energy and bandwidth consumption. All transaction fees are transferred to the black hole account. 

### Defect

Inflation and deflation of coins; lack of stability for users, lack of motivation and funding to upgrade SR equipment, little interest from investors.

### Solution

Disable TRX creation, tokenize SR rewards

### Principle of operation of the reward system "Caishen"

When a user makes a transaction, the commission instead of burn it goes to the "Capacity" address.
Super representatives receive a Reward Token (RWD) for creating a block. (1 block = 1 RWD) + 10 RWD for votes.
Every 24 hours, funds are transferred from the "Capacity" address to the RWD\TRX JustSwap liquidity pool to ensure the value of the RWD token (1 RWD = 16TRX). The remainder of the funds is distributed among users who voted for SRs.

### Nuances

The system is dynamically self-balancing: if SRs starts to create empty blocks, or if all transactions will be done with free energy, then SRs will start accumulating "Reward" tokens due to the lack of securing the value of tokens with TRX. This motivates them to increase the amount of energy derived directly from "burning" the TRX(burning means sending TRX to the "Capacity" address). Therefore, transactions on the Tron network will always be cheap.

_* All figures, percentages and time periods are given as examples and require analyst calculation.
** The proposal is a draft and you can suggest edits.
*** "Caishen" - god of wealth. The name is not essential and serves only to differentiate._

MIT License

**Comment by zweryok** [comment]
Thank you all very much for the tips, I am working on the bugs.

**Comment by Imbaexchange** [comment]
I don't understand what the Tron SRs don't understand when all of the community cry out burn more TRX.

**Comment by JesseHerring33** [comment]
How to use the app

**Comment by JesseHerring33** [comment]
What to do

**Comment by zweryok** [comment]
> How to use the app

Which app are you talking about? This is not an application, this is an option to reward SR nodes for mining

**Comment by ethan1844** [comment]
This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback.
