### ISSUE TITLE
Security system "Mehen"

### ISSUE THREAD

**Issue by zweryok** [tronprotocol/tips#233]
### Reality

A lot of rogue applications and pyramids have emerged, many posing as the Tron Foundation.
They create unnecessary load on the nodes, ruining the reputation of the TRON blockchain.
The scammers sell the stolen TRX and reduce the TRON rate.

### Decision

Create a list of smart contracts dynamically generated by users, divided into three levels according to the degree of trust:
Positive, Neutral, Negative. **Allow users to create their own lists, share them, save.**
By default, attach the base list of applications to the address. A similar technology is used in JustSwap.

When launching a smart contract from the Neutral List, warn the user about the risk.
To launch a smart contract from the "Negative" list, the user will have to add a smart contract to the list of allowed ones.

*The proposal is a draft and you can suggest edits.
**"Mehen" - god of protection. The name is not essential and serves only to differentiate.

MIT License

**Comment by otakuinny** [comment]
Who decides which smart contracts go into which list.

**Comment by zweryok** [comment]
> Who decides which smart contracts go into which list.

 **Allow users to create their own lists, share them, save.**
