### ISSUE TITLE
Proposal: Optimize the black hole accounts to increase the execution speed of transactions

### ISSUE THREAD

**Issue by Benson0224** [tronprotocol/tips#234]
## Motivation

As introduced before, the black hole address optimization function is one of the important updates in version 4.1.2. After this feature is enabled, it will greatly increase the execution speed of transactions and improve the performance of java-tron.

## Timeline 
We hope in the next two weeks, everyone can share their opinions here.
The estimated timeline :
- Creation time of the voting request: 22nd Feb. 2021
- Effective time of voting request: 25th Feb. 2021

## How to initiate the voting request
This is the command of initiating the voting request
- createProposal 49 1

## Background                             
In the current Tron network, the burned TRX is transferred to the black hole account. In the process of performing the transfer, the black hole address will be serialized and deserialized. Serialization and Deserialization of Objects consume CPU time a lot.  With the increase of TRC10 tokens in the black hole address, the ‘Object’ size of blackhole accounts become bigger. The execution time of the black hole address serialization and deserialization is getting longer and longer, which has affected the performance of java-tron significantly. Therefore, in order to avoid frequent serialization and deserialization operations on the black hole address, proposal `#49` is introduced into java-tron to allow changing the storage location of the burned TRX, from the black hole address to the `DynamicPropertiesStore`.

In addition to performance considerations, this `#49` proposal can also help us count the burned TRX more flexibly, for example, we can clearly know the amount of burned TRX in a certain day or month, and more detailed statistics
 
## Technical Specs
There are many scenarios currently involved in sending transaction fees to blackhole, such as Transfer Asset, Create Account, and so on, instead of sending transactions fees to blackhole account, all burned TRX will be accumulated in `burnTrx`, which means using `DynamicPropertiesStore` to record the number of destroyed TRX.
Add a new Key-Value pair structures to `DynamicPropertiesStore`, the structures are  like : key: BURN_TRX; value: the number of TRX burned

**Note**: the main change for `#49` proposal is to improve the performance of java-tron by technically changing the storage address of burning TRX. It will not impact the TRX circulation and it will not change the calculation logic for the TRX circulation either. check the pull request code change [here](https://github.com/tronprotocol/java-tron/pull/3608).

## 4.1.1 VS 4.1.2 Comparison
Different tests were designed and executed based on different testing strategies to achieve the comparative testing, these strategies including different test data samples, different test periods, different testing environments, and so on. 

After testing, compared the TPS(transactions executed per second) of 4.1.2 with the TPS of 4.1.1, we can see that the TPS has increased by about 17.5% overall after this feature is enabled(in testnet, which may differ in mainnet)

More detail, With the feature “optimize the black hole accounts” enabled, For transactions where transaction fees are paid by burning TRX, the performance has been greatly improved. Here is the result:
- The TPS of system contract call increased by 240% 
- The TPS of smart contract call increased by 200%

Note: the `#49` proposal only works in the java-tron and only improves the java-tron performance. And this comparison test is executed in java-tron, not including the other implementations like rust-tron, scala-tron.

If you want to know more testing tech details, welcome to join this discussion.

## Why the improvement rate exceeds 200% while the overall improvement rate is 17.5%
Bandwidth and energy can be obtained via freezing TRX or burning TRX, this feature is to optimize the black hole account, which means it will only improve those transactions where the transaction fee is paid by burning TRX, and those transactions where the transaction fee is paid by freezing TRX will not be impacted.  

The 200% and 240% show the theoretical values, the testing is based on standard TRC20 contracts and all transaction fees are paid by burning TRX. However, On the mainnet, there are a variety of contracts with different complexity, and the execution time of contract calls also varies with the complexity. for contracts with higher complexity, The execution time of transferring TRX to the black hole address is only a small part, even after optimization, the overall execution time will not be greatly improved. However,  for the standard TRC20 contract, the impact is huge. 

Welcome to discuss.

**Comment by dudebing99** [comment]
Aye

**Comment by a49688448** [comment]
Support performance improvements

**Comment by kangjiancheng** [comment]
GOOOOOD!

**Comment by dkealervdsf** [comment]
Support this proposal!

**Comment by kunlunxuejue11** [comment]
This black hole account should have been removed a long time ago. Many people mistakenly thought this was a real black hole account and earned trc10 and trc20 tokens into this account. In fact, this is not a real black hole account.

**Comment by woaichixigua07** [comment]
This is too useful, for contracts, it will reduce the out-of-time error rate. Just this point will have very good results.

**Comment by otakuinny** [comment]
Now this is the kind of proposal I can get behind.

**Comment by joanna459** [comment]
The proposal is sooooo great!! Awesome improvement!

**Comment by woaichixigua07** [comment]
This proposal is to optimize the performance of java tron, it is really useful!

**Comment by MRFUNCT1ON** [comment]
I support this proposal

**Comment by MikumoGuynemer** [comment]
This is the best news I heard from TRON recently. We suffered from server busy too often during this period of time. Overall 17.5% improvement is great and the most important is: I've known TRON is truly making efforts on the blockchain tech itself.

**Comment by vita-coffee** [comment]
First of all, I must admit that this is the best one of the last few proposals. It is a thing that benefits everyone. I fully support this proposal.

Take a look at the original issue, https://github.com/tronprotocol/tips/issues/222, it mentioned below point, I have to say that I cannot agree with this point. Compatibility is very important that must be considered for software version iteration. Delete or modify existing interfaces should be avoided as much as possible. All new functions should be implemented using new interfaces as much as possible. So I suggest keeping the black hole address, even if we no longer use it. Avoid affecting users who are using it.
![image](https://user-images.githubusercontent.com/78467791/106842326-cd6a4a00-66de-11eb-931c-3e47de4d9dbd.png)

From another perspective, this solution is more like a short-term solution. As mentioned in https://github.com/tronprotocol/tips/issues/222, transferring TRX will serialize and deserialize the black hole address. I believe that transferring TRX to any other account will also perform serialization and deserialization. should we consider avoiding this kind of serialization operation, or optimizing this serialization operation to improve the performance of the entire network?

**Comment by Benson0224** [comment]
Hi,
Thanks for your suggestion. yes, you are right, currently, there is no plan to remove the blackhole account completely. 

Regarding improving the serialization, now serialization is mandatory to store data in the database, it is not easy to improve this part. however, In the long run, we will continue to explore other solutions to optimize the performance of this part. 

> Take a look at the original issue, #222, it mentioned below point, I have to say that I cannot agree with this point. Compatibility is very important that must be considered for software version iteration. Delete or modify existing interfaces should be avoided as much as possible. All new functions should be implemented using new interfaces as much as possible. So I suggest keeping the black hole address, even if we no longer use it. Avoid affecting users who are using it.
> ![image](https://user-images.githubusercontent.com/78467791/106842326-cd6a4a00-66de-11eb-931c-3e47de4d9dbd.png)
> 
> From another perspective, this solution is more like a short-term solution. As mentioned in #222, transferring TRX will serialize and deserialize the black hole address. I believe that transferring TRX to any other account will also perform serialization and deserialization. should we consider avoiding this kind of serialization operation, or optimizing this serialization operation to improve the performance of the entire network?

**Comment by Benson0224** [comment]
Close this issue as the proposal already got passed on the mainnet. 
Check detail at https://tronscan.org/#/proposal/54
