### ISSUE TITLE
Proposal: Disenfranchise the TRON foundation addresses from voting and make the SR voting process truly democratic

### ISSUE THREAD

**Issue by otakuinny** [tronprotocol/tips#235]
Currently, the account owned by the TRON foundation [TTXeVETaU1wSV9cYutUgyg7x1gtrfCiDiW](https://tronscan.org/#/address/TTXeVETaU1wSV9cYutUgyg7x1gtrfCiDiW) that has more than **5.2 Billion TRX** participates in the SR voting process. This account takes advantage of the massive number of votes it has and votes for super representatives that are really surrogates for the TRON foundation. **This has resulted in the TRON foundation gaining a lot of SR spots in the top 27 which gives them a super majority and the power to approve/reject any proposal unilaterally.**  

This flies in the face of the SR voting process which was meant to be a democratic process where TRON users vote for those SR/SRCs they think is doing the most for the advancement of the TRON eco-system. 

The following URL shows the SRs this account votes for.
https://tronscan.org/#/address/TTXeVETaU1wSV9cYutUgyg7x1gtrfCiDiW/votes

**These votes also dilute the voter rewards which means less voting rewards for the TRON users.** 

The votes from this account and any other TRON foundation linked account are illegitimate and they should be disqualified from participating in the voting process. Only then do the votes of ordinary every day TRON users matter.

Let's discuss....

**Comment by birdonwheels5** [comment]
I agree with the idea of not allowing the funds held by that address to vote, however how would they be blacklisted? If you say that address can't vote, what is to stop them from sending the funds to another address or addresses and voting from there? They can easily send to an exchange and withdraw to other addresses to hide the fact that they are still voting.

But yes, the TRON foundation appears to be holding the majority, which completely defeats the purpose of voting. I do not believe the recent proposal 51 would have passed (should pass with 17 votes) if it were not for this. You can see almost entirely TRON foundation SRs voting for it.

**Comment by otakuinny** [comment]
@birdonwheels5, I should have made it clear in my post above. This is not a technical proposal where we prevent certain addresses from voting. The goal is to bring enough awareness in the TRON community to this blatant practice so the foundation is pushed to to agree to not participate in voting. I'm sure when more people are aware of this they'd be on-board with it considering how their share of daily voter rewards will go up significantly once the votes from the foundation addresses are removed.

**Comment by birdonwheels5** [comment]
Unfortunately I'm not sure if that will happen because it seems like people don't really care that the voting is pretty much rigged as it is now. They can only see dollar signs... Of course, I would love to see the TRON foundation back away from voting like this, but I doubt it will ever happen given the personality of Justin Sun. Even with a public backlash on the voting practices, he will find a way to maintain some level of control and influence over the protocol, even if it is not as direct as it is now.

**Comment by zweryok** [comment]
Anyone who has a lot of money has managed to earn it with his mind. Are you proposing to exclude the smartest from the voting? This is ridiculous.

**Comment by otakuinny** [comment]
@zweryok, son, did you read the proposal? On second thought, can you read at all? We are talking about tron foundation using the billions of trx they pre mined in the SR voting process.

**Comment by otakuinny** [comment]
Closing
