### ISSUE TITLE
Adaptation to solidity-v0.5.16

### ISSUE THREAD

**Issue by yanghang8612** [tronprotocol/tips#241]
## Simple Summary

A bugfix about Yul Optimizer in Tron Solidity

## Background

Solidity-v0.5.16 of Ethereum fix a bug in redundant assignment remover in combination with break and continue statements. So we should update Tron Solidity to follow it.

## Details

The Yul optimizer has a stage that removes assignments to variables that are overwritten again or are not used in all following control-flow branches. This logic incorrectly removes such assignments to variables declared inside a for loop if they can be removed in a control-flow branch that ends with ``break`` or ``continue`` even though they cannot be removed in other control-flow branches.

**Comment by Benson0224** [comment]
Closed this issue as it is already included in the latest release. thanks.
