### ISSUE TITLE
TIP243:TRON Parachain Slots Auction

### ISSUE THREAD

**Issue by xq-lu** [tronprotocol/tips#243]
``` 
tip: 243
title: TRON Parachain Slots Auction
author: xq.lu <xq.lu@tron.network>
discussions to: https://github.com/tronprotocol/tips/issues/243
status: Draft
type: Standards Track
category: Core
created: 2021-03-08
```

## Simple Summary

This TIP describes the access mechanism of how a  para chain participates in the TRON network.

## Abstract
This TIP provides a detailed introduction on how parallel chains can access the main TRON network, mainly covering: how parallel chains register on the TRON network and prevent malicious registrations from affecting the main chain; the auction mechanism of parallel chain slots on the TRON network, and the exit mechanism of parallel chains.

## Motivation
As we know, the essence of cross-chain is the information interaction between different chains, and the chain interaction will bring great value to the whole cross-chain ecology. In the TRON cross-chain solution, the requirements for accessing parallel chains are relatively high. We have designed a perfect access mechanism to make the parallel chains interested in the TRON cross-chain ecology can access the TRON ecology easily and quickly.

We designed an innovative registration mechanism to ensure fast access while maximizing the security and stability of the TRON network and preventing some malicious parallel chains from destroying the stability of the main network.
At the same time, we designed a refined and simple auction mechanism, so that interested parallel chain participants can participate in the chain slot auction with a sense of security and boldness, without having to worry about funding, so that good projects can access the TRON ecology!

## Technical Specifications

Our design document mainly contains two parts according to the timeline of parallel chain participation, firstly, parallel chains register on the main network of TRON, after successful registration, they can participate in the chain slot auction, and after the successful auction, they can access the main network of TRON to operate across chain actions.

### Parallel chain registration
Suppose chainA, a chain developed based on TRON network, wants to access TRON network as a parallel chain, first it needs to register on TRON network, the registration will deduct some TRXs from  chainA's account on TRON network, the registration fee is 1000TRX for currently, the chain already registered is not allowed to register again to avoid multiple fee deductions. See Appendix 1 for the interface and data structure

During the registration process, it will check whether the account balance of the registrant is sufficient, and the corresponding registration fee of 1000TRX will be deducted directly from the account if the condition is met (tentative, which can be modified by the proposal later)

Considering that the registration information of parallel chain may be outdated, `UpdateCrossActuator` is responsible for updating the information of the registered parallel chain, and at the same time, it will determine whether the `owner_address` that initiated the update is the same as the `owner_address` that initiated the registration. See Appendix 2 for the interface and data structure.

After successful registration or update, the parallel chain information will be kept in the database `cross-revoke-database`, see Appendix 3 for the database structure.

### Slots Auction 

The auction of slots in the main TRON network will be started at the same time as the cross-revoke proposal is approved.
Slot auction will be held at irregular intervals. For example, the first round of the auction is held on May 1 and the second round is held 15 days later One auction cycle is 28 maintenance periods; during the auction cycle in this round, parallel chains can call users to vote for themselves (make sure that these parallel chains have been registered), and at the end of the auction cycle in this round, we will select the n parallel chains with the highest votes, and these n parallel chains will be connected to the main TRON network for cross-chain communication as the successful parallel chains in the auction in this round.

The details will be divided into the following parts:

1. Users vote for parallel chains
As we mentioned above, before the start of the card slot auction in this round, the parallel chain project can call for users to vote for themselves. When a user votes for a parallel chain, the amount of asset data corresponding to the number of votes will be deducted and transferred to the blackhole account, and the voting record of this user will be recorded. 

Of course, since users can vote for a certain parallel chain, they can also withdraw their votes for this parallel chain and switch to other parallel chains when their opinions change. When a user withdraws his vote, all his votes for the parallel chain will be withdrawn, and the corresponding amount of assets previously deducted will be returned to his account at the end of this round. 

At the same time, we provide several query interfaces to help check the voting status of this round. 

2. Slot Auction

After the cross-chain proposal of the TRON network is passed and started of specific round, the slot auction of this round starts at the same time, and the auction lifecycle will be configured through the auction config proposal. Users vote on the registered parallel chains during the auction cycle, and the first N parallel chains with the highest votes are selected at the end of the auction cycle, then the TRON network starts synchronizing the blockheads of these parallel chains, and the current time t1 is recorded as the start time of the current cross-chain cycle.
Parallel chains can be registered at any time, and users can be called to vote on them after a successful registration.

After the para chain won the slot auction of this round, the para chain config of the winner will be solidified and stored in TRON network. which will be used when this para chain connected to TRON network in this round. the successful para chain can use the slot for a specific time(configured through auction config proposal).

If a user finds that a parallel chain has cheated, he/she can initiate a proposal and the committee will confirm it. After most committee members confirm it, this user will be rewarded who initiated the proposal and the committee members according to a certain percentage(**not implemented right now**).

----------------------------------------------------------------

### Why use the current auction scheme instead of the candle auction?
The current auction scheme is a clever mix of Dutch-style auctions and crowdfunding. Generally speaking, for a parallel chain project that wants to participate in the auction of slots, the project may not have enough reserve funds to participate in the auction because the project itself has insufficient funds, although the project is excellent, it does not have enough reserve funds to participate in the auction. For the users who participate in the voting, once the project supports bids for slots successfully, the subsequent participation in the cross-chain ecology can also bring great benefits to the users.

As we all know, TRON network is the popular public chain network in the world, and TRON's cross-chain architecture has the characteristics of refinement and high scalability based on the realization of cross-chain core functions, as well as the high performance and 0 commission of TRON network itself. We believe that there will be many parallel chain projects that will actively and enthusiastically participate in TRON's cross-chain slot auction.

In the current auction scheme, we have set a minimum starting price to ensure that many parallel chain projects can participate in the auction so that those who really want to participate in the wavefield cross-chain ecology can be successful.

The problem with the current auction scheme is that the auction period is fixed (currently 28 maintenance periods), and some users may be able to force a parallel chain with a low number of votes into the top N at a low cost instantly before the end of the vote, which affects the fairness of the vote to some extent. Candle auction can solve this problem perfectly, and if this kind of auction attack occurs subsequently, we  can consider using candle auction

### When will TRON parachain slots auction begin？
We will launch the TRON cross-chain Testnet in May, and started the TestNet Parachain slots auction in May.

### Additional things to do after winning a slot in parallel chain slots auction?

As we mentioned above, after a parallel chain wins a slot auction, the TRON network saves the parallel chain's information for subsequent access. After the parallel chain accesses the TRON network, TRON network information does not existed in this para-chain. From the parallel chain's perspective, the TRON network can be seen as its parallel chain. At this time, the parallel chain can hold a para-chain slot auction too. So that the TRON network can bid for the slot, and then the parallel chain can save  TRON network's information to facilitate the subsequent communication between the TRON network and the parallel chain.
Of course, auctions held by parallel chains can be simplified as much as possible, if they just need to give access right to the TRON network.

### cross-chain registration
API:

```

/wallet/registercrosschain

```
Cross-chain message format:

```protobuf
message CrossChainInfo {

  bytes chain_id = 1;
  bytes owner_address = 2;
  bytes sr_list = 3;
  int64 begin_sync_height = 4;
  int64 maintenance_time_interval = 5;
  bytes parent_block_hash = 6;
}
```

### cross-chain registration update
API:

```

/wallet/updatecrosschain

```

Message

```protobuf
message CrossChainInfo {

  bytes chain_id = 1;
  bytes owner_address = 2;
  bytes sr_list = 3;
  int64 begin_sync_height = 4;
  int64 maintenance_time_interval = 5;
  bytes parent_block_hash = 6;
}
```

### cross-revoke-database
```
{
  key: "register" + {chain_id},
  value: content of {CrossChainInfo}

}
```

### registration details query
HTTP
```
URL: /wallet/getregistercrosschainlist
RETURN: List<CrossChainInfo>
```

gRPC
```
rpc GetRegisterCrossChainList(PaginatedMessage) returns (List<CrossChainInfo>) {

  option (google.api.http) = {
    post: "/wallet/getcrosschainregisterlist"
    body: "*"
    additional_bindings {
    get: "/wallet/getcrosschainregisterlist"
    }
  };
};
```

### vote for slot auction
```protobuf
message VoteCrossChainContract {
  bytes chain_id = 1;
  bytes owner_address = 2;
  int64 amount = 3;
}
```

API:

```

/wallet/votecrosschain

```
### cross-revoke-database
```
{
  key: "vote" + chain_id + owner_address,
  value: amount
}
```

### unvote for slot auction

```protobuf
message UnvoteCrossChainContract {
  bytes chain_id = 1;
  bytes owner_address = 2;
  int32 round = 3;
}
```

API:

```

/wallet/unvotecrosschain

```

### vote sumary query 
```protobuf

message CrossChainVoteSummary {

  bytes chain_id = 1;
  int64 amount = 2;
  int32 round = 3;
}

```

HTTP:
```
URL: /wallet/getcrosschainvotesummarylist
PARAMS:
- offset
- limit 
RETURN: List<CrossChainVoteSummary>
```

gRPC:
```
rpc GetCrossChainVoteSummaryList (int offset, int limit) returns (List<CrossChainVoteSummary>) {
option (google.api.http) = {
    post: "/wallet/getcrosschainvotesummarylist"
    body: "*"
    additional_bindings {
    get: "/wallet/getcrosschainvotesummarylist"
    }
  };
};

```

### vote details query
HTTP:
```
URL: /wallet/getcrosschainvotedetaillist
PARAMS:
- offset
- limit 
RETURN: List<VoteCrossChainContract>
```

gRPC:
```
rpc GetCrossChainVoteDetailList (int offset, int limit) returns (List<VoteCrossChainContract>) {
    option (google.api.http) = {
    post: "/wallet/getcrosschainvotedetaillist"
    body: "*"
    additional_bindings {
    get: "/wallet/getcrosschainvotedetaillist"
    }
  };
};

```

**Comment by KI5FPL** [comment]
```protobuf
message VoteCrossContract {
  bytes chain_id = 1;
  bytes owner_address = 2;
  int64 amount = 3;
}
```

Tron-protocol never(except 1 flaw) use `owner_address` in field 2. It should be always at field 1.

To disambiguate, use `VoteParachainContract`. Any built-in contract should be a verb phrase.

In an auction, the use of `amount` has an ambiguity too. You should use `bid_amount`.

**Comment by KI5FPL** [comment]
Your TOC level has 1.2. and a.b. interlaced.

**Comment by jamestompson** [comment]
Very interesting, can you tell us how to develop TRON parallel chains, any document?

What are the requirements if I want to access the test network, like Rococo.

**Comment by a49688448** [comment]
How many Slot Auction in TRON?
What are the auction rules?

**Comment by MikumoGuynemer** [comment]
I think candle auction is better because of its random ending time. We must consider the possibility of SR cheating. If the auction ends at a fixed time, a malicious block producer will have the chance to choose specific transactions to pack then impact the auction result.

**Comment by xiangyuan-chaoqing** [comment]
From your description, in the voting phase, one TRX is equivalent to one vote, and the TRX participating in the voting will be transferred to the `crosschain-fund` account. 
Based on your current description, these TRXs are equivalent to being locked in the `crosschain-fund` account. did not generate any other value, this is not the freezing we understand in the TRON ecosystem. 

Would it be better to adopt the freezing mechanism so that the TRX participating in the voting can also obtain energy or bandwidth at the same time. In this way, it is more consistent with the existing mechanism of TRON.

**Comment by xq-lu** [comment]
> Very interesting, can you tell us how to develop TRON parallel chains, any document?
> 
> What are the requirements if I want to access the test network, like Rococo.

dev documents will be ready when the test network launch.
if you want to access the test network, you may also need to win/acquire test network slots in the slots auction.

**Comment by xq-lu** [comment]
> How many Slot Auction in TRON?
> What are the auction rules?

1.The number of card slots will be determined by the number of parallel chains participating in the card slot auction。
2.please see section 'Slots Auction'  in this TIP for the auction rules details.

**Comment by xq-lu** [comment]
> I think candle auction is better because of its random ending time. We must consider the possibility of SR cheating. If the auction ends at a fixed time, a malicious block producer will have the chance to choose specific transactions to pack then impact the auction result.

you can check the section 'Why use the current auction scheme instead of the candle auction?', which explains your question.

**Comment by xq-lu** [comment]
> From your description, in the voting phase, one TRX is equivalent to one vote, and the TRX participating in the voting will be transferred to the `crosschain-fund` account.
> Based on your current description, these TRXs are equivalent to being locked in the `crosschain-fund` account. did not generate any other value, this is not the freezing we understand in the TRON ecosystem.
> 
> Would it be better to adopt the freezing mechanism so that the TRX participating in the voting can also obtain energy or bandwidth at the same time. In this way, it is more consistent with the existing mechanism of TRON.

your suggestion is really great and reasonable, we will consider it seriously🙂

**Comment by a49688448** [comment]
What's the detail timeline of TRON Parachain Slots Auction?
How do I find out which items on TRON will participate in parallel chain auctions？

**Comment by woaichixigua07** [comment]
When the Parachain slot is released, can the TRX pledged during the auction be returned? And can I still participate in the auction in the future?

**Comment by dkealervdsf** [comment]
how to prevent some malicious parallel chains from destroying the stability of the main network?

**Comment by xq-lu** [comment]
> malicious

A para-chain who wins the slot will be staked some TRXs(depends on the votes, also we will have a minimum staking amount ), if this para-chain misbehave and destroy the stability of TRON network, part of this staking TRXs will be published.

**Comment by xq-lu** [comment]
> What's the detail timeline of TRON Parachain Slots Auction?
> How do I find out which items on TRON will participate in parallel chain auctions？

The detailed timeline will be published after the test net launch.

**Comment by xq-lu** [comment]
> When the Parachain slot is released, can the TRX pledged during the auction be returned? And can I still participate in the auction in the future?

The para-chain slot will be released after a specific period(currently is one year, which can be configured by proposal), after that the staking TRX will be returned to the user's account from ‘crosschain-fund’ account。 you can find the detail in the section 'Users vote for parallel chains'
