### ISSUE TITLE
TRC-248 : SPV on TRON

### ISSUE THREAD

**Issue by spidemen** [tronprotocol/tips#248]
```
tip: 248
title: SPV on TRON
author: xing<xing@tron.network>
discussions to: https://github.com/tronprotocol/tips/issues/248
category: TRC
status:  DRAFT
created: 2021-03-21
```
 
## Simple Summary
 
This tip mainly describes SPV and how it works on cross-chain projects. In addition, it also discusses a solution to TRON version SPV.
 
## Abstract
 
SPV plays a very important role in cross-chain projects since it provides fast transaction verification on lightweight clients such as wallets. Those clients only store block header information for verification purposes. However, there are likely to be tampering attacks on block producing and confirmation stages, which may lead to chain switch or forking. With TRON version SPV, TRON version SPV ensures the correctness of blocks that you use to do SPV.
 
## Motivation
 
In the Bitcoin world, most users do not have mining machines, and nor do they have enough resources to run a full node. For now, you need 200GB hard drive space to store the entire blockchain data and a solid state drive is preferred. For most users, what they need is only selling and buying. Since they don't care about the verification process, a mining machine seems a bit redundant. Here's when TRON version SPV comes into play. SPV is lightweight, as it stores only block headers, only a small MBs space is required. From the block headers, we are able to know whether the transaction appears in a block, which can prove whether it has been verified.
 
TRON version of SPV improves the accuracy and security of block query, which safeguards the verification process of blocks and transactions. 
 
### Merkle Tree  
Basically, the Merkle tree, named after Ralph C. Merkle, who is a famous cryptographer, is like a hash tree, which uses a hash function to connect with each node. The value of leaf node in the Merkle tree is a data block hash, while the hash value of non-leaf node is a hash of hashing several other nodes' hash values. It's like we can hash two leaves' hash value into a non-leave hash, which is the root of those two.
 
![MerkleTree](https://user-images.githubusercontent.com/33735949/112413057-869de580-8d5a-11eb-82e7-89517538a150.png)
                           <center>Figure 1</center> 
        
- Merkle proof         
 Merkle proof is the Merkle path and block height obtained from the full node.
 
- Merkle path
  Merkle path is a hash path that consists of node hash values from the bottom leaf node all the way to the top node where node hash values are computed by given transaction hash values. For example, given transaction D, the corresponding hash value is N3, the Merkle path should be N2--N4 since we use N2 to get N5 by N5 = hash(N2,N3) and the same root by doing hash(N4,N5).
 
 
- Features:
    1.  highly efficient: To validate transactions, just compare the root hash of those transactions, see if they are equal or not.
 
    2.  highly secure: If transaction C changes, then it will lead to hash value change of N2, N5 and root. So, it is impossible to create a fake transaction within SPV. In addition, fast troubleshooting can be done by comparing the different hash values of the nodes. Like the above example, From root → N5 → N2 hash value will change, and then we could locate the change of transaction C.
 
 
### Epoch  
   Every six hours is called Epoch in TRON. In other words, it is a cycle for producing a certain number of blocks.
 
### SR List
  SR list is a type of data structure used for block verification, which includes srAddress. SRL will be calculated in each maintenance period, which stores a list of SR addresses on the next epoch. For block verification, just check if there are 2/3+1 SRs that sign the blocks in the SR list.
 
```
message SRL {
 repeated bytes srAddress = 1;
}
 
```
 
 
#### Threshold Signature
 
1. At least t  participants in the group can collaborate to generate a valid signature on behalf of the group signature.
2. Anyone who plays the role of a veriﬁer can use the group’s public key to verify the group signature with-out identifying the identities of the signers
 
### Verifier
 nodes that trigger the pBFT consensus procedure for blocks produced by SRs
 
### Algorithm on Merkle Tree
- Generate a Merkle proof
  1. given a transaction hash value
  2. query from full node to get the list of transactions hash values in associated block and mark as leave nodes
  3. iterate all leaf nodes by group of two at each pass and compute each two leave node parent hash and add it into parent list and find leaf node that matches the given transaction hash value
  4. add the other node hash value of this group into Merkle proof list and mark their parent node
  5. iterate parent list by group of two at each pass and compute each two node hash value and add it into temporary parent list and find marked node
  6. add another node of this group and mark their parent node
  7.  go to step 5, use a temporary parent list to replace leave nodes and the same process
  8. check step 5's parent nodes size, if bigger than 1 , then to step 6, otherwise return Merkle proof list
 
Take Figure 1 as an example, be given Transaction D and then calculate Transaction D hash value--N3.  From step 2, we can get a list of all transaction hash values [N0,N1,N2,N3]. And take a group of two and do iteration: [N0,N1],[N2,N3]; at the second pass, we can find N3 and add N2 into Merkle proof list([N2]) and meanwhile compute parent hash list as [N4,N5] and mark N5.  Next, iterate [N4,N5] and add N4 into the Markle proof list, which is [N2,N4].
 
Take the Merkle proof list [N2,N4] and N3, we can compute the Merkle root by doing Hash(N4,Hash(N3,N2)).
If you are more interested in how to implement it, feel free to check the function: generateProofPath in our java tron codebase.
 
-  Valid Merkle proof
  1. Give a Merkle proof list and Transaction associated value N3
  2. do result = N3 and iteration proof list
  3. do result = hash(result, element in the proof list)
  4. get Merkle root and compare with local Merkle root
  5. if equal, then valid , otherwise, fake transaction
 
If you are more interested in how to implement it, feel free to check the function: validProof in our java tron codebase.
 
### SPV process
1. Get the transaction hash.
2. From a full node, get the corresponding Merkle proof. For detail see generate Merkle proof
3. Based on the Merkle path, do Markle proof and finally get Merkle root. For detail see valid Merkle proof
4. Compare local Merkle root with the calculated one.
5. Judge if the transaction is legal on the basis that whether the result is equivalent to the local Merkle Root.
 
Basically, given a transaction hash and use that hash query full node to get block header as well as Merkle path. Based on the Merkle path and feature of Merkle tree, we can easily calculate the new Merkle root and then we can compare with the local Merkle root.If it matches, then it is a valid transaction; otherwise, it is a fake one.
 
### SPV on tron
 
In DPOS consensus every slot is assigned to the only legal SR. So within one schedule if verifiers know the legal SR list they can verify every block header easily. Since verifiers don't process most transactions including vote transactions they have no way to know the voting result. In other words they are unable to know the next legal SR list. The focus of this problem is on how to handle the maintenance period correctly. Based on the above reasons we can solve this problem by recording SR lists in one type of BPFT messages which are sent by the previous legal SR list we trust.
 
Most process of TRON version SPV is the same as the SPV process as above, the only difference is that we add SR list and SR signature in the pBFT message. So we can use the SR list to validate the block header and SR signature to validate SRs, which can safeguard our SPV process.
 
For more details about block header: please take a look at TIP 251-cross chain block header synchronization
### data structure
 
Leaf: Merkle tree leaf node which contains left and right child, hash value and remark status 
 
```typescript
 
public class Leaf {
 
 private Sha256Hash hash;
 private Leaf left, right;
 private boolean remark;
}
```
 
ProofLeaf: Merkle tree proof data structure which contains the hash value of nodes in the Merkle path and a boolean value indicating left or right node. 
 
```typescript
public class ProofLeaf {
 
 private Sha256Hash hash;
 private boolean leftOrRight;//left leaf is false,and the right one is true
 
 public ProofLeaf(Sha256Hash hash, boolean leftOrRight) {
   this.hash = hash;
   this.leftOrRight = leftOrRight;
 }
}
```
 
 
### required function
 
 
validSrList: use previous SR list and PBFT commit result to valid current SR list  .  
 
```typescript
 
public boolean validSrList(PBFTCommitResult dataSign, Set<ByteString> preSRL)
 
```
 
 
getCurrentSrList: given block header and chainId, and give a list of SRs .  
 
```typescript
 
private List<ByteString> getCurrentSrList(BlockHeader header, String chainId)
 
```
 
 
setSrList: set next epoch SR list  .  
 
```typescript
 
 protected void setSrList(Builder builder, String chainIdString, long blockTime)
 
```
 
generateProofPath: get a Merkle proof based on the transaction hash value.  
 
```typescript
 
 public List<ProofLeaf> generateProofPath(List<Sha256Hash> hashList, Sha256Hash src)
 
```
 
validProof: valid given Merkle proof.  
 
```typescript
 
public boolean validProof(Sha256Hash root, List<ProofLeaf> proofPath, Sha256Hash src)
 
```

**Comment by spidemen** [comment]
```
tip: 248
title: SPV on TRON
author: xing<xing@tron.network> 
discussions to: https://github.com/tronprotocol/tips/issues/248
category: TRC
status:  DRAFT
created: 2021-03-21
```

## Simple Summary

This tip mainly describes SPV and how it works on cross-chain. In addition, also discusses a solution to support tron version SPV. 

## Abstract

Currently, SPV play a very important role in cross-chain project since it can provide fast transaction verification on light weight client such as wallets. Those clients only store block header information for verification purpose. However, there are might be tampering attack on block producing and confirm stage, which may lead to switch chain or do another fork. With tron version SPV, it ensures the correctness of block that you use to do SPV.

## Motivation

In Bitcoin world, most of users do not have mining machine, and they do not have enough resource to run a full node. For now, you need 200GB hard drive space to store the entire blockchain data and a solid state drive is preferred. For most users, what they need, is only selling and buying. Since they don't care about the verification process, a mining machine seems a bit redundant. SPV appears to solve this problem. SPV is lightweight, as it stores only block headers, a few MBs space is required. From the block headers, we are able to know whether the transaction appears in a block, which can prove whether it has been verified.

Tron version of SPV provides extra correctness and security for block query, which safeguards block and transactions verification process.  

## Specification

### Merkle Tree   
Basically, Merkle tree, named after Ralph C. Merkle who is a famous cryptographers, is like a hash tree, which uses hash function to connect with each node. The value of leaf node in Merkle tree is a data block hash, while hash value of non-leaf node is a hash of hashing several other nodes' hash values. It's like we can hash two leaves hash value into a non-leave hash, which is the root of those two.
   
  ![](https://github.com/tronprotocol/tips/raw/master/tp/MerkleTree.png) 
              <center>Figure 1</center>  
  
- Features: 
     1.  highly efficient: To validate transactions, just compare the root hash of those transactions, see if they are equal or not. 

     2.  highly secure: If transaction C changes, then it will lead to hash value change of N2, N5 and root. So, it is impossible to create a fake transaction within SPV. In addition, fast troubleshot can be done by comparing the different hash value of the nodes. Like the above example, From root → N5 → N2 hash value will change, and then we could locate the change of transaction C.


### Epoch   
    Every six hours is called Epoch in tron. In other words, a cycle for producing a certain number of blocks.

### SR List 
 
   SR list is type of data structure used for block verification, which includes nextSrList and sr_signature. SRL will be calculated in each maintenance period, which stores a list of SR address on next epoch. For block verification, just check block if there is 2/3+1 SR that sign this blocks in the SR list or not. 

```
message SRL {
  repeated bytes srAddress = 1;
}

```


#### Threshold Signature

1. At least t  participants in the group can collaborate to generate a valid signature on behalf of the group signature.
2. Any one who plays the role of a veriﬁer can use the group’s public key to verify the group signature with-out identifying the identities of the signers

### Verifier
  nodes that trigger the pBFT consensus procedure for blocks produced by SRs

## Rationale

### SPV process
 
1. Get the transaction hash.
2. From a full node, getting the corresponding Merkle proof.
3. Base on Merkle path, doing Markle proof and finally get Merkle root.
4. Comparing local Merkle root with the calculated one.
5. Judging if the transaction is legal from whether the result is equivalent to the local Merkle Root.

Basically, given a transaction hash and using that hash query full node to get block header as well as Merkle path. Based on Merkle path and feature of Merkle tree, we can easily calculate new Merkle root and then we can compare with local Merkle root, if match, then it is valid transaction, otherwise, it is fake one. 

### SPV on tron

In DPOS consensus every slot is assigned to the only legal SR, So within one schedule if verifiers know the legal SR list they can verify every block header easily. Since verifiers don't process most transaction including vote transaction. they have no way to know the voting result. In other words they are unable to know the next legal SR list. The focus of this problem is how to handle the maintenance period correctly. Based on the above reasons we can solve this problem by recording SR list in one type of BPFT messages which are sent by the previous legal SR list we trust. 

The most process of tron version SPV is the same as SPV process as above, only different is that we add SR list in the pBFT message. 


## Implementation

**Comment by Dev-Tools-VM** [comment]
Will there be official SPV-based wallets from TRON? 
Or Any wallet Demo based on SPV.
when will the testnet Be ready for this, thanks.

**Comment by spidemen** [comment]
Will there be official SPV-based wallets from TRON ??     No 
Any wallet demo based on SPV. ??  No
When will the testnet is ready for this ??    Approximately May 2021.      
TRON version SPV is design for cross-chain project, so it will be launched all together with cross-chain.

**Comment by MikumoGuynemer** [comment]
I've noticed that "TRON version SPV is design for cross-chain project", does that mean there won't be any SPV nodes? I'm eagerly excepting an available SPV, as in many scenarios, the only demand is "verifying the transaction".

**Comment by spidemen** [comment]
SPV---- simple payment verification. Any wallet or hardware clients want to do SPV, just download all block header into local disk and then start to follow SPV process do transaction verification.

**Comment by spidemen** [comment]
``` TRON version SPV is design for cross-chain project", does that mean there won't be any SPV nodes? I'm eagerly excepting an available SPV, as in many scenarios, the only demand is "verifying the transaction". ```   YES. Only verify transactions,   TRON SPV have additional SPV messages on blockhead like SR_List and SR_signature, the other chain need to those message to verify transactions and SRs
