### ISSUE TITLE
Include transaction results on the chain

### ISSUE THREAD

**Issue by lvs007** [tronprotocol/tips#250]
``` 
tip:250
title: Include transaction results on the chain
author: Kiven <kiven.liang@tron.network> 
discussions to: https://github.com/tronprotocol/TIPs/issues/250
status: draft
type: Standards Track
category: Core
created: 2021-03-25
```

## Simple Summary
This TIP provides Include transaction results on the chain  for java-tron. 

## Abstract
Currently, the result of transaction execution is written in the block. But there is no signature, so it can be tampered with. The tampered block will cause other nodes to think it is a bad block. Then disconnect the node connected to it. It will cause certain damage to the network and affect the stability of the TRON network.

## Motivation
Put the transaction results on the chain so that they cannot be tampered with and ensure the security of the TRON network.
## Rationale
public Sha256Hash calcReceiptsRoot(): Calculate the Merkel root of all transaction results
public Sha256Hash getReceiptsMerkleHash(): Get the hash value of each transaction result
public boolean allowRecieptsMarketRoot(): Whether to enable the function of trading results on the chain

## Technical Specifications：
In the stage of generating blocks. All transactions are executed, the transaction results are calculated to generate the transaction result Merkel root (receiptsRoot), and then the receiptsRoot is written into the block header. Finally, the block is signed.

Merkel root generation method of trading results.
```
public Sha256Hash calcReceiptsRoot() {
  List<Transaction> transactionsList = this.block.getTransactionsList();

  if (CollectionUtils.isEmpty(transactionsList)) {
    return Sha256Hash.ZERO_HASH;
  }

  ArrayList<Sha256Hash> ids = transactionsList.stream()
      .map(TransactionCapsule::new)
      .map(TransactionCapsule::getReceiptsMerkleHash)
      .collect(Collectors.toCollection(ArrayList::new));

  return MerkleTree.getInstance().createTree(ids).getRoot().getHash();
}
```
Get the hash value of each transaction result.
```
public Sha256Hash getReceiptsMerkleHash() {
  if (this.transaction.getRetCount() <= 0) {
    return Sha256Hash.ZERO_HASH;
  }
  byte[] transBytes = this.transaction.getRet(0).toByteArray();
  return Sha256Hash.of(CommonParameter.getInstance().isECKeyCryptoEngine(),
      transBytes);
}
```
When processing a block, it is necessary to verify the root of the transaction result while verifying the transaction root.
```
if (getDynamicPropertiesStore().allowRecieptsMarketRoot() && !block.calcReceiptsRoot().equals(block.getRecieptsRoot())) {
  throw new BadBlockException("The receipt merkle hash is not validated");
}
```
Due to the need to modify the protocol, a hard fork is required. By adding a proposal to open the transaction results on the chain function. Proposal id is: 50

## Data Structures：
The receiptsRoot field is added to the block header to store the Merkel root of the transaction result.
```
message BlockHeader {
  message raw {
    int64 timestamp = 1;
    bytes txTrieRoot = 2;
    bytes parentHash = 3;
    //bytes nonce = 5;
 //bytes difficulty = 6;
 int64 number = 7;
    int64 witness_id = 8;
    bytes witness_address = 9;
    int32 version = 10;
    bytes accountStateRoot = 11;
    bytes chainId = 12;
    bytes crossTxRoot = 13;
    bytes receiptsRoot = 14;
  }
  raw raw_data = 1;
  bytes witness_signature = 2;
}
```
## Implementation
coming soon

## Copyright
All content herein is licensed under Apache 2.0.

**Comment by Dev-Tools-VM** [comment]
The current height is close to 30Million, Based on the current block height, what is the approximate size of the Merkle tree which stored the transaction result?

**Comment by vita-coffee** [comment]
Sounds Great, looks that it can somehow improve the security level. 
Do you have any estimation when it can be released?

**Comment by cest-bon-bon** [comment]
One simple question:
`receiptsRoot` is the Merkle root of the transaction result.

here the transaction means all the transactions inside the current block or all the transactions from the genies block?

```
message BlockHeader {
  message raw {
    int64 timestamp = 1;
    bytes txTrieRoot = 2;
    bytes parentHash = 3;
    //bytes nonce = 5;
 //bytes difficulty = 6;
 int64 number = 7;
    int64 witness_id = 8;
    bytes witness_address = 9;
    int32 version = 10;
    bytes accountStateRoot = 11;
    bytes chainId = 12;
    bytes crossTxRoot = 13;
    bytes receiptsRoot = 14;
  }
  raw raw_data = 1;
  bytes witness_signature = 2;
}
```

**Comment by zhang0125** [comment]
> The current height is close to 30Million, Based on the current block height, what is the approximate size of the Merkle tree which stored the transaction result?

Only contains the transaction results of the current block, so it is not very large.

**Comment by zhang0125** [comment]
> Sounds Great, looks that it can somehow improve the security level.
> Do you have any estimation when it can be released?

It will be implemented in the next version, you won't have to wait long.

**Comment by zhang0125** [comment]
> all the transactions inside the current block

@cest-bon-bon  Only the transaction results from the current block are included here.

**Comment by lvs007** [comment]
the result already contains in Merkle root. so shouldn't do this.

**Comment by Benson0224** [comment]
As @lvs007  mentioned above, no need to do this, so close the issue. big thanks to everyone.
