### ISSUE TITLE
TIP-275: Optimize block production logic

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/tips#275]
```
tip: 275
title: Optimize block production logic
author: lucas.wu@tron.network
discussions to: https://github.com/tronprotocol/TIPs/issues/275
status: IDEA
type: Standards Track
category: Core
created: 2021-07-29
```
## Simple Summary
This TIP is to optimize the block production logic to reduce block production time.

## Abstract
Now it takes hundreds of milliseconds to produce a block. After analysis, it is found that most of the time is spent on the repeated execution of transactions in the pending queue. This article details the optimization of the block production.

## Motivation
In order to improve the performance of the blockchain, increase the TPS, and reduce the block loss rate, it is necessary to reduce the block production time. Packing transactions already in the pending queue directly will save time in block production.

## Implementation
The time consumption of block production is mainly used to execute transactions in the pending queue, in order to save the block production time, it is necessary to avoid repeated execution of the transactions. Can the pending transactions be directly assigned to the block? It is completely feasible in theory, because transactions in the pending queue are executed in order, so there is no need to re-execute them.

A new block production method:
1. Assign the transactions in the pending queue directly to the block
2. Other logic remains unchanged

The packing algorithm is a bit complicated. In order to change the code as little as possible, a new packing function is redefined. When the following conditions are met, the new packing algorithm can be used, otherwise the old packing algorithm can be used.
1. Number of anonymous transactions <= 1
2. Number of transactions for multi-signature accounts <= 1
3. Duration of pending transaction < 3s
4. Pending queue size > 20 (threshold) || (pending queue size <= 20 && re-push queue size == 0)

**Comment by diwu1989** [comment]
If you assign transactions in the pending queue directly to the block, then they won't be sorted by gas price anymore, and only sorted by validator received time, correct?

TX ordering becomes FIFO?

**Comment by wubin01** [comment]
@diwu1989 yes. If the pending transactions can be packaged at one time, if there are too many pengding transactions to be packaged at one time, and the gas ordering needs to be considered, it cannot be handled in this way.
