### ISSUE TITLE
TIP-276: Optimize block verification logic

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/tips#276]
```
tip: 276
title: Optimize block verification logic
author: lucas.wu@tron.network
discussions to: https://github.com/tronprotocol/TIPs/issues/276
status: DRAFT
category: Core
created: 2021-06-03
```
## Simple Summary
This TIP is to optimize the block verification logic to reduce block processing time.
## Abstract
According to statistics, the verification of each transaction takes about 3ms on average. After analysis, the verification of the transaction takes up nearly one-third of the time during the entire block processing. This article details the optimization of the block verification.
## Motivation
In order to improve the performance of the blockchain, increase the TPS, and reduce the block loss rate, it is necessary to reduce the block processing time. 
## Specifications
TODO
## Implementation
After testing and analysis, most of the transactions packaged in the block are also in the pending queue, and the transactions in the pending queue are successfully verified. So whether it can be considered, if the transaction in the block also exists in the pending queue, it is not necessary to verify the signature. Of course, there is a special case that needs to be considered. In the scenario of a multi-signature transaction, the multi-signature transaction will change the account permissions, so the final logic can be implemented as follows:
1. Extract the account list corresponding to the multi-signature transaction in the pending queue
2. If the transaction in the block also exists in the pending queue, and the corresponding account is not in the list of multiple signature accounts, you can skip the verification
3. Verify transaction signatures that have not skipped verification
## Rationale
TODO

**Comment by forfreeday** [comment]
This issue has been formally documented: [TIP-276 Optimize block verification logic](https://github.com/tronprotocol/tips/blob/master/tip-276.md)
