### ISSUE TITLE
TRC: Built-in message queue for event subscribe

### ISSUE THREAD

**Issue by jiangyy0824** [tronprotocol/TIPs#28]
tip: 28
title: TRC-28 Built-in message queue for event subscribe
author: jiangyy <jiangyangyang@tron.network> 
discussions to: https://github.com/tronprotocol/TIPs/issues/28
status: accepted
type: Standards Track
category: TRC
created: 2019-03-14

**Simple Summary**
Adding built-in message queue for event subscribe in java-tron. 

**Abstract**
The built-in message queue is designed for event subscribe. Developers could subscribe triggers directly from fullnode without event plugin.

**Motivation**
Developers could use event plugins to subscribe triggers from fullnode, which provide very reliable service and store very large amount of data. 

But in some cases, developers want to subscribe directly from fullnode, with short-term subscriptions. Native message queue is implemented to meet such requirement.

**Specification**
The function of native queue is configurable. It's is disabled by default. It shared the configuration of triggers with eventplugin.

The communication channel between fullnode and subscription client is socket. The bindport could be configurable to avoid conflicting.

event.subscribe = {
    native = {
      useNativeQueue = true // if true, use native message queue, else use event plugin.
      bindport = 5555 // bind port
      sendqueuelength = 1000 //max length of send queue
    }
    ......
}

Developers should subscribe triggers very conveniently. What they need to do is: connecting to the port, subscribing the topics, then receivingthe triggers.

**Comment by neshala** [comment]
How exactly I can subscribe to the topic?

I have tried to send this JSON variable in order to subscribe, but no lack:

{"triggerName": "block", enable: true, "topic": "block"}
or
{"triggerName":"block"}
or
{"id": 1, "method": "block", "params": [""]}
or just
{"block"}

but none from above is working for me and I have enabled block topic in main config.

**Comment by CerberusGR** [comment]
Does anybody has an example?
Why native queue server not running (port 5555 is not opened).

**Comment by surindergiri** [comment]
Hi,
I am also facing same issue, enabled native events within Tron Node and trying to get contract events using below code in NodeJs.
```
this.tronWeb.getEventByTransactionID(txid).then(async result => {
      console.log('getEventByTransactionID  :: result :: ', result);
      return result;
    }).catch((err) => {
      console.log('ERROR getEventByTransactionID :: ', err);
      return false;
    });
```
When I run the code then it return "parse error".
Did you figure out what exactly is the code format to subscribe contract events using Tron node native events?

Thanks,

**Comment by vdudouyt** [comment]
I'm also experiencing the same issue:
```
$ telnet localhost 5555
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

In my mainnet_conf I have:

```
event.subscribe = {
    native = {
      useNativeQueue = true // if true, use native message queue, else use event plugin.
      bindport = 5555 // bind port
      sendqueuelength = 1000 //max length of send queue
    }
...
}
```

Is there any way to perform native event subscription for me without the burdens of installing Apache Kafka / MongoDB?
