### ISSUE TITLE
Proposal: Change the bandwidth unit price and the system contract creating account fee

### ISSUE THREAD

**Issue by fbsobreira** [tronprotocol/tips#286]
# Proposal: Change the unit price of bandwidth to 1000 sun and change the system contract creating account fee to 1 TRX 

## Introduction
In order to solve the problem caused by the dramatic increase in the number of TRC10 transactions on the TRON network, the TRON community plans to adjust the unit price of bandwidth to 1000 sun, and change the system contract creating account fee to 1 TRX.

## Motivation
Increasing the unit price of bandwidth and the system contract creating account fee will increase the cost of TRC10 token transactions, restrain the growth rate of TRC10 transactions and improve the security and stability of the Tron network.

## Timeline
The estimated timeline
 - Creation time of the voting request: 23rd July. 2021 (TBD)
 - The effective time of voting request: 26th July. 2021 (TBD)

## How to initiate the voting request
 - Change the unit price of  bandwidth to 1000 sun, and change the system contract creating account fee to 1 TRX
 - createProposal 3 1000 7 1000000

## Background
TRON network is well known for its advantages of low transaction fees and fast transfer speed. However, the low transfer fee also brings some problems. Since mid-June, the number of transactions on the TRON network has risen sharply. Among them, the number of TRC10 transfers has increased the most. At present, the TRC10 transfer transactions in the past month account for nearly 60% of the total transaction volume. Some projects are fraudulent projects, which will cause harm to user assets. This affects the security of users' property, and a large number of TRC10 transactions will also cause network instability. The figure below shows the trend of the total number of transactions and TRC10 transfers in the last two weeks.
For details, see: https://tronscan.org/#/data/stats/txOverviewStatsType

![image](https://user-images.githubusercontent.com/8503176/125051180-156c0f00-e079-11eb-8675-1e344a3cbc5e.png)

### Fraud Project Examples
Some of the TRC10 transfers are fraudulent transactions that induce users to give the approval of the USDT contract to accounts controlled by malicious users. These fraudulent projects first airdrop TRC10 tokens in large quantities and induce users to exchange tokens on fraudulent websites through transaction notes. Once the user exchanges Token, in fact, it will be an USDT 'approve' transaction initiated by the fraud project. As shown below:

![image](https://user-images.githubusercontent.com/8503176/125051213-1e5ce080-e079-11eb-8054-8ac4066c9e72.png)

![image](https://user-images.githubusercontent.com/8503176/125051273-2b79cf80-e079-11eb-95dc-4c3575270727.png)

Here we just use a typical example to analyze the scam. In actual situations, the phishing pages shown in transactions from different fraudulent projects may be various, but the goal is to trick users into `approve` or `transfer` valuable Tokens to the account controlled by the fraudulent project.  
**All users must carefully check the transaction information when using Tronlink to sign transactions to prevent property loss.**

### TRC10 transfer cost analysis

When TRC10 Token transfer is performed on the `Tron` network, it is realized by executing the `transferasset` system contract. A transfer contract will consume about 300 to 500 bandwidth (depending on the size of the transaction). Users can use free 5000 bandwidth to pay or the bandwidth obtained by freezing TRX to pay.  If the bandwidth is insufficient, the user’s TRX will be burned to pay. 

## Proposals related to the cost of TRC10 transaction 

- Proposal `#8`
  - `CREATE_NEW_ACCOUNT_BANDWIDTH_RATE`
  - This is the bandwidth coefficient corresponding to the number of transaction bytes when creating an account
  -  When creating a new account, the bandwidth to consume(`netUsage`) is calculated by the bytes of the system contract(`bytes`) multiplied by a coefficient(`createNewAccountBandwidthRatio`)
  - The value of `createNewAccountBandwidthRatio` is currently 1

- Proposal `#2`
  - `CREATE_ACCOUNT_FEE`
  - This is the account activation fee.
  - During the activation process, an amount of TRX will be burnt if there is not enough bandwidth
  - The value is currently 100,000 sun

- Proposal `#3`
  - `TRANSACTION_FEE`
  - This is the amount of TRX to be burnt to obtain each unit of bandwidth
  - The value is currently 140 sun

- Proposal `#7`
  - `CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT`
  - This is the fee of the account creation by the system contract
  - A number of TRX will be burnt during account creations by the system contract
  - The value is currently 0 sun

## Recommended solution
Among the system parameters proposed in the previous section, it is recommended to increase unit price of bandwidth and system contract creation account fee, namely:

- The unit price of bandwidth needs to be changed from 0.00014 TRX to 0.001 TRX
- The value of `CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT` for creating an account in the system contract needs to be changed from 0 to 1 TRX.

### The Impact Analysis

After increasing the system contract creating account fee, the consumption of TRX increased from 0.1 TRX to (0.1 + 1) = 1.1TRX when the user's bandwidth was insufficient, and the cost increased by 10 times.

The following are the statistics for the past month:

 Category | Value
:----------------------------- | :--------------
Average bandwidth of all transactions in the past month | 393
Average bandwidth of all smart contract calls in the past month | 372
Average fee for all smart contract calls in the past month | 2.143191 TRX

From the transaction point of view, the average bandwidth of a transaction is 393, which is equivalent to `393(BandWidth) * 0.00014(TRX/BandWidth) = 0.05502 TRX`, that is, `0.05502 TRX * 0.061(USDT/TRX) = 0.003356 USDT`.

After increasing `TRANSACTION_FEE` to 0.001TRX, it is equivalent to `393(BandWidth) * 0.001(TRX/BandWidth) = 0.393 TRX`, that is, `0.393 TRX * 0.061(USDT/TRX) = 0.024 USDT`.

The cost of TRC10 transactions can be increased by about 7 times.

Taking the average bandwidth consumed by smart contract calls (372) as an example, due to the increase in `TRANSACTION_FEE`, the corresponding TRX consumption has increased by `(0.001-0.00014) * 372 = 0.32 TRX`, and the average handling fee for smart contract calls has increased `0.32 / 2.143191 = 14.927%`. It can be seen that the transaction cost of TRC10 can be greatly increased on the premise that the transaction cost of the smart contract can be affected as little as possible.

|              |  140 sun | 1000 sun | Increasement |
|:--------------------------- |:---------------:| -------------:| ------|
| The average bandwidth value of all transactions in the past month | 393 * 0.00014 = 0.05502 TRX | 393* 0.001 = 0.393 TRX | 7 times increase|
| Average fee of all transactions in the past month | 2.143191 TRX | delta = (0.001-0.00014) * 372 = 0.32 TRX | 15% increase|

**Comment by woaichixigua07** [comment]
I support this proposal. My TRON wallet address will receive a large amount of useless TRC10 tokens every day. As mentioned in the article, some of the TRC10 transfers are fraudulent transactions that induce users to give the approval of the USDT contract to accounts controlled by malicious users. And I have a question, will this proposal affect TRX transfers?
![image](https://user-images.githubusercontent.com/62126493/125059808-4df20400-e0de-11eb-8c12-895cbd4886b8.png)

**Comment by fbsobreira** [comment]
> And I have a question, will this proposal affect TRX transfers?

yes, it will also have effect on TRX transfer..

**Comment by lochuan** [comment]
It's great to see the Tron community take effort to curb fraudulent transactions on the TRON network. From a transaction perspective, it increases the intrinsic value of transactions, encourages more effective transaction, and discourages fraudulent transactions. In terms of monetary policy, it will accelerate the TRX deflation process, that's a bull case for TRX and so great for all of TRX holders.

**Comment by Cletitia** [comment]
I've recently received a slew of TRC-10 garbage coins...
This proposal, I believe, will help to alleviate the situation to some extent, but it will also have an impact on routine transactions, particularly TRX transfers.
I believe the community should carefully evaluate this idea, as TRX transfers and any other system contract transactions will be 7 times more expensive than they were previously. This is by no means a trivial sum.
Maybe the issuance cost of trc-10 tokens can be increased to alleviate this issue?

**Comment by a49688448** [comment]
I agree that I always receive airdrops from garbage coins, which is very annoying. But there is a question. The cost of garbage and deceptive projects is high. Will the cost of ordinary dapp developers increase? How to balance it? How is this cost increase ratio calculated?

**Comment by shiziwen** [comment]
This is an exciting news. The garbage airdrop is annoying and I think many have the same feeling.
I almost fell into the trap of the fraudulent transactions before.

**Comment by Dev-Tools-VM** [comment]
From my personal point of view, I agree with this proposal. TRC10 is a unique token type of TRON, which is loved by many community users due to its stability, high efficiency, and low cost.

TRC10 has also produced a lot of excellent tokens to contribute to the TRON ecosystem. According to the description in the governance plan, the bandwidth unit price will be increased by about 7 times, which means around 0.4 TRX. I have to say that although the increase is very large, But the transfer cost is still very low. While increasing the transaction cost, the cost of issue a new TRC10 token should also be appropriately increased.

Therefore, I propose to increase the cost of issuing a new TRC10 to 50,000 TRX to prevent malicious projects from using TRC10 to create more spam transactions.

**Comment by hitlxy** [comment]
Yes, the TRC-10 token is easy to issue and transfer with low cost, that makes the fraud increasing. In my account there are many trc10 tokens received by airdrop with attractive notes. because I am a blockchain developer, these tokens have effect on my project development and testing because of so many tokens. on the other hand, the fraud affects the security and stability of blockchain.  
so I expect more proposals to fight fraud. and  hope the ecology gets better.

**Comment by Guerreru** [comment]
Hello, 

I believe that the side-effects of this proposal must be revised. 

Increasing the account creation fee will affect everyone that creates a new wallet account and not just those creating a TRC-10 token with malicious intent (which can't be identified right away). 

Bandwidth fee will also have an effect to everyone, including tokens like BTT, FREE, BBST, TERC and the many other great projects that are on TRC-10. Bandwidth also is used to transfer TRX itself and used along Energy in contract based transactions.

Maybe what we need is a range of backup SRs, like if there is a big peak in transaction, the blockchain would enable from these backup SRs selected from the 28th to 127th which are SPs.  That would alleviate some work from the only 27 SRs which are centralizing the blockchain.

**Comment by call-me-nobody** [comment]
This proposal is very good. But it seems that the existing parameters cannot fix the issue mentioned in the proposal.

If you want to reduce garbage TRC10 transactions, the most important thing is to reduce the free bandwidth or increase the amount of bandwidth consumed by TRC10 transfers. let's see one example below: 

`Assuming that the current spam project has 10,000 spam accounts, even if the bandwidth cost and the cost of creating new accounts are increased, it will not affect them much. After the increase, the cost of TRC10 transfer is still about 370 bandwidth. Then the free 5000 bandwidth of an account can still transfer 13 times for free, and 10,000 accounts are 130,000 free transfers. If 100,000 accounts, then his ability is enough to affect normal transactions.`

Therefore, the content of the proposal can only limit the new spam project to enter this area, and cannot affect those existing projects.

In addition, increasing the unit price of bandwidth also has an impact on TRX transfers, which is very bad, and it is also detrimental to the ecology of TRX. Therefore, I suggest that a new proposal should be designed that can individually adjust the bandwidth consumption of TRX, TRC10, and TRC20. This is the most reasonable.

**Comment by zhangwenhua-tron** [comment]
> TRX transfers and any other system contract transactions will be 7 times more expensive than they were previously.

> Will the cost of ordinary dapp developers increase? How to balance it? How is this cost increase ratio calculated?

@Cletitia C @a49688448 

Thanks for your reply.
As we know, the fraudulent transactions have a significant negative impact on the user, and the goal of this proposal is to suppress this phenomenon to the greatest extent possible while having minimal impact on normal users. 

According to this proposal, the bandwidth unit price will be increased by about 7 times, which means the average bandwidth of one transaction will be around 0.4 TRX, although the increase is very large, but the transfer cost is still very low. Besides, this will encourage more effective transaction and more quality dapps.

**Comment by zhangwenhua-tron** [comment]
> Maybe the issuance cost of trc-10 tokens can be increased to alleviate this issue?

> the cost of issue a new TRC10 token should also be appropriately increased.

@Dev-Tools-VM @Cletitia  
Thanks for your suggestions! 
Increasing the cost of issuing a TRC10 token maybe also help, but the most important issue now is the spike in TRC10 transactions, and the first step is to alleviate the situation.

But the community will discuss this suggestion.

**Comment by zhangwenhua-tron** [comment]
> the most important thing is to reduce the free bandwidth or increase the amount of bandwidth consumed by TRC10 transfers.
> Therefore, I suggest that a new proposal should be designed that can individually adjust the bandwidth consumption of TRX, TRC10, and TRC20. This is the most reasonable.

@call-me-nobody 
Your advice is very valuable. 
Actually, the TRON community has also discussed options for modifying the 5000 free bandwidth and it has been in progress but not in this proposal.

**Comment by zhangwenhua-tron** [comment]
@lochuan  @hitlxy  
Thanks for your support, hope all goes well!

**Comment by vae520283995** [comment]
@fbsobreira Hi,
When will CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT be burnt? Normal transfers will only burnt CREATE_ACCOUNT_FEE

**Comment by renchenchang** [comment]
> @fbsobreira Hi,
> When will CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT be burnt? Normal transfers will only burnt CREATE_ACCOUNT_FEE

It will be burnt when you active a new account in a transaction and it will cost CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT + CREATE_ACCOUNT_FEE after this proposal.

**Comment by vae520283995** [comment]
> > @fbsobreira Hi,
> > When will CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT be burnt? Normal transfers will only burnt CREATE_ACCOUNT_FEE
> 
> It will be burnt when you active a new account in a transaction and it will cost CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT + CREATE_ACCOUNT_FEE after this proposal.

okay, thank you

**Comment by vae520283995** [comment]
@renchenchang Hi,
When will this proposal take effect, so I can modify my code in time

**Comment by jiangyy0824** [comment]
> @renchenchang Hi,
> When will this proposal take effect, so I can modify my code in time
As mentioned in the article.  The effective time of voting request: 9th July. 2021 (TBD)

**Comment by simbadMarino** [comment]
Please don't, TRC-10 and TRX transfers are still cheap and convenient for devs and people with no big resources. If you want to stop scammers and spammers I thing its better to remove the free 5000 Bandwidht so they stop creating spam wallets to enjoy their free transfers

**Comment by Benson0224** [comment]
> Please don't, TRC-10 and TRX transfers are still cheap and convenient for devs and people with no big resources. If you want to stop scammers and spammers I thing its better to remove the free 5000 Bandwidht so they stop creating spam wallets to enjoy their free transfers

Thanks for your suggestion, it is already included in the new TIP, check more info here:  https://github.com/tronprotocol/tips/blob/master/tip-292.md

**Comment by abhisareen2002** [comment]
I believe increasing bandwidth cost is not an effective measure, instead we should reduce the free bandwidth given to each account along with increasing transactions. The main reason why I believe this is because even if we increase bandwidth fee, an easy workaround is making many accounts which gives them wiggle room to make about 10 transactions per day per account. reducing the amount of free bandwidth will require them to create more accounts for a larger spam tx count. 

I feel that people who do not mind burning 1024 trx for making a trc10 token will definitely not mind paying a little extra for multiple accounts. Also in my case, I have about 1000 accounts that I activated because I was working on a project (that sadly didn't get launched), but my point being, for people who already have many accounts, this will not be a very useful proposal. I feel that reducing the amount of free bandwidth given will definitely help more than increasing price.

**Comment by Benson0224** [comment]
> I believe increasing bandwidth cost is not an effective measure, instead we should reduce the free bandwidth given to each account along with increasing transactions. The main reason why I believe this is because even if we increase bandwidth fee, an easy workaround is making many accounts which gives them wiggle room to make about 10 transactions per day per account. reducing the amount of free bandwidth will require them to create more accounts for a larger spam tx count.
> 
> I feel that people who do not mind burning 1024 trx for making a trc10 token will definitely not mind paying a little extra for multiple accounts. Also in my case, I have about 1000 accounts that I activated because I was working on a project (that sadly didn't get launched), but my point being, for people who already have many accounts, this will not be a very useful proposal. I feel that reducing the amount of free bandwidth given will definitely help more than increasing price.
> 
> But in the end, the main and only way is to inform every user about these problems. I think the most effective way to fix this would be to get tronlink team to actually fix the bugs and add warning messages. As a developer, I know that this is a very lengthy process, but hard times call for intensive measures. Making the wallet a bit more centralised and linked with tronscan, for example getting a team to manually approve trc10 tokens that show up in tronlink wouldn't be the worst, but should be considered as a last resort. Adding more sensitive tickers to trc10 recordings is one of the things that would help reduce the problem much more

Thanks for your suggestion and sharing.  here are some updates regarding your suggestions. 
1.  Reduce the free bandwidth is already on the way as you can see in the new TIP https://github.com/tronprotocol/tips/blob/master/tip-292.md, after this TIP is implemented in the new release, the committee can submit new proposals to change the value of the free bandwidth, at the same time, as @call-me-nobody  mentioned above, this proposal will help to limit the new spam project to enter this area as it increased the cost of creating new accounts, which is also very valuable.  
2.  Regarding your suggestion on Tronlink, I would say the tronlink team has their own opinions, and I also believe that they will make the right choice. thanks for your suggestion.

**Comment by Benson0224** [comment]
Thanks to everyone for contributing to this proposal. 
This issue will be closed as the voting request of this proposal is already approved on Tron Mainnet.  Check detail at https://tronscan.org/#/proposal/67.

**Comment by Balance2020Happiness2021** [comment]
> # Proposal: Change the unit price of bandwidth to 1000 sun and change the system contract creating account fee to 1 TRX 
> 
> ## Introduction
> In order to solve the problem caused by the dramatic increase in the number of TRC10 transactions on the TRON network, the TRON community plans to adjust the unit price of bandwidth to 1000 sun, and change the system contract creating account fee to 1 TRX.
> 
> ## Motivation
> Increasing the unit price of bandwidth and the system contract creating account fee will increase the cost of TRC10 token transactions, restrain the growth rate of TRC10 transactions and improve the security and stability of the Tron network.
> 
> ## Timeline
> The estimated timeline
>  - Creation time of the voting request: 23rd July. 2021 (TBD)
>  - The effective time of voting request: 26th July. 2021 (TBD)
> 
> ## How to initiate the voting request
>  - Change the unit price of  bandwidth to 1000 sun, and change the system contract creating account fee to 1 TRX
>  - createProposal 3 1000 7 1000000
> 
> ## Background
> TRON network is well known for its advantages of low transaction fees and fast transfer speed. However, the low transfer fee also brings some problems. Since mid-June, the number of transactions on the TRON network has risen sharply. Among them, the number of TRC10 transfers has increased the most. At present, the TRC10 transfer transactions in the past month account for nearly 60% of the total transaction volume. Some projects are fraudulent projects, which will cause harm to user assets. This affects the security of users' property, and a large number of TRC10 transactions will also cause network instability. The figure below shows the trend of the total number of transactions and TRC10 transfers in the last two weeks.
> For details, see: https://tronscan.org/#/data/stats/txOverviewStatsType
> 
> ![image](https://user-images.githubusercontent.com/8503176/125051180-156c0f00-e079-11eb-8675-1e344a3cbc5e.png)
> 
> 
> ### Fraud Project Examples
> Some of the TRC10 transfers are fraudulent transactions that induce users to give the approval of the USDT contract to accounts controlled by malicious users. These fraudulent projects first airdrop TRC10 tokens in large quantities and induce users to exchange tokens on fraudulent websites through transaction notes. Once the user exchanges Token, in fact, it will be an USDT 'approve' transaction initiated by the fraud project. As shown below:
> 
> ![image](https://user-images.githubusercontent.com/8503176/125051213-1e5ce080-e079-11eb-8054-8ac4066c9e72.png)
> 
> ![image](https://user-images.githubusercontent.com/8503176/125051273-2b79cf80-e079-11eb-95dc-4c3575270727.png)
> 
> Here we just use a typical example to analyze the scam. In actual situations, the phishing pages shown in transactions from different fraudulent projects may be various, but the goal is to trick users into `approve` or `transfer` valuable Tokens to the account controlled by the fraudulent project.  
> **All users must carefully check the transaction information when using Tronlink to sign transactions to prevent property loss.**
> 
> 
> ### TRC10 transfer cost analysis
> 
> When TRC10 Token transfer is performed on the `Tron` network, it is realized by executing the `transferasset` system contract. A transfer contract will consume about 300 to 500 bandwidth (depending on the size of the transaction). Users can use free 5000 bandwidth to pay or the bandwidth obtained by freezing TRX to pay.  If the bandwidth is insufficient, the user’s TRX will be burned to pay. 
> 
> ## Proposals related to the cost of TRC10 transaction 
> 
> - Proposal `#8`
>   - `CREATE_NEW_ACCOUNT_BANDWIDTH_RATE`
>   - This is the bandwidth coefficient corresponding to the number of transaction bytes when creating an account
>   -  When creating a new account, the bandwidth to consume(`netUsage`) is calculated by the bytes of the system contract(`bytes`) multiplied by a coefficient(`createNewAccountBandwidthRatio`)
>   - The value of `createNewAccountBandwidthRatio` is currently 1
> 
> - Proposal `#2`
>   - `CREATE_ACCOUNT_FEE`
>   - This is the account activation fee.
>   - During the activation process, an amount of TRX will be burnt if there is not enough bandwidth
>   - The value is currently 100,000 sun
> 
> - Proposal `#3`
>   - `TRANSACTION_FEE`
>   - This is the amount of TRX to be burnt to obtain each unit of bandwidth
>   - The value is currently 140 sun
> 
> - Proposal `#7`
>   - `CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT`
>   - This is the fee of the account creation by the system contract
>   - A number of TRX will be burnt during account creations by the system contract
>   - The value is currently 0 sun
> 
> ## Recommended solution
> Among the system parameters proposed in the previous section, it is recommended to increase unit price of bandwidth and system contract creation account fee, namely:
> 
> - The unit price of bandwidth needs to be changed from 0.00014 TRX to 0.001 TRX
> - The value of `CREATE_NEW_ACCOUNT_FEE_IN_SYSTEM_CONTRACT` for creating an account in the system contract needs to be changed from 0 to 1 TRX.
> 
> ### The Impact Analysis
> 
> After increasing the system contract creating account fee, the consumption of TRX increased from 0.1 TRX to (0.1 + 1) = 1.1TRX when the user's bandwidth was insufficient, and the cost increased by 10 times.
> 
> The following are the statistics for the past month:
> 
>  Category | Value
> :----------------------------- | :--------------
> Average bandwidth of all transactions in the past month | 393
> Average bandwidth of all smart contract calls in the past month | 372
> Average fee for all smart contract calls in the past month | 2.143191 TRX
> 
> From the transaction point of view, the average bandwidth of a transaction is 393, which is equivalent to `393(BandWidth) * 0.00014(TRX/BandWidth) = 0.05502 TRX`, that is, `0.05502 TRX * 0.061(USDT/TRX) = 0.003356 USDT`.
> 
> After increasing `TRANSACTION_FEE` to 0.001TRX, it is equivalent to `393(BandWidth) * 0.001(TRX/BandWidth) = 0.393 TRX`, that is, `0.393 TRX * 0.061(USDT/TRX) = 0.024 USDT`.
> 
> The cost of TRC10 transactions can be increased by about 7 times.
> 
> Taking the average bandwidth consumed by smart contract calls (372) as an example, due to the increase in `TRANSACTION_FEE`, the corresponding TRX consumption has increased by `(0.001-0.00014) * 372 = 0.32 TRX`, and the average handling fee for smart contract calls has increased `0.32 / 2.143191 = 14.927%`. It can be seen that the transaction cost of TRC10 can be greatly increased on the premise that the transaction cost of the smart contract can be affected as little as possible.
> 
> |              |  140 sun | 1000 sun | Increasement |
> |:--------------------------- |:---------------:| -------------:| ------|
> | The average bandwidth value of all transactions in the past month | 393 * 0.00014 = 0.05502 TRX | 393* 0.001 = 0.393 TRX | 7 times increase|
> | Average fee of all transactions in the past month | 2.143191 TRX | delta = (0.001-0.00014) * 372 = 0.32 TRX | 15% increase|
> 
> 
> 
> 

Thank you
