### ISSUE TITLE
TIP-289: Block broadcast optimization

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/tips#289]
```
tip: 289
title: Block Broadcast Optimization
author: lucas.wu@tron.network
discussions to: https://github.com/tronprotocol/TIPs/issues/289
status: DRAFT
category: Core
created: 2021-07-12
```
## Simple Summary
This TIP is to optimize block broadcasting.
## Abstract
The current block processing and broadcasting logic is like this: Verify block → Process block → Broadcast block. The time consumption is mainly in the block processing. Therefore, once this broadcast logic is used, the block delay will be longer. The log below shows that the block delay is close to 2 seconds.

![image](https://user-images.githubusercontent.com/37210306/125230394-46fc0900-e30b-11eb-8d9d-dac5efe156be.png)

Worse, for example, if the processing of the block takes 1 second, the next SR and the previous SR exceed 2 hops, it will directly lead to a block miss. This article details the optimization of the block broadcasting.

## Motivation
In order to speed up the block broadcast, let the block be broadcast on the whole network in a short time and improve the block miss rate, it is necessary to optimize the block broadcasting.

## Implementation
Modify the processing and broadcast block logic: Verify block → Broadcast block → Process block. As long as the network is unblocked, the block will be broadcasted on the whole network soon, and the block will not be lost.

Reasons for the feasibility of the scheme:
1. If there is no witness of cheating, it is completely feasible to broadcast first and then execute.
2. If a witness cheats, the result is only one more performance consumption of block execution. Blocks that fail to execute will not be chained, which will not have much impact on the entire system.

The main need to modify the place:
1. Processing broadcast block: verify the block, including signature and witness valid verification, broadcast directly after the verification is passed, and then process the block.
2. TCP connection: the block verification fails and the connection is disconnected; the block processing fails and the connection cannot be disconnected (currently the connection will be disconnected as long as the processing fails), otherwise a bad block may cause the entire network to be disconnected.

**Comment by wubin01** [comment]
```
tip: 289
title: Block Broadcast Optimization
author: lucas.wu@tron.network
discussions to: https://github.com/tronprotocol/TIPs/issues/289
status: DRAFT
category: Core
created: 2021-07-12
```
## Simple Summary
This TIP is to optimize block broadcasting.
## Abstract
The current block processing and broadcasting logic is like this: Verify block → Process block → Broadcast block. The time consumption is mainly in the block processing. Therefore, once this broadcast logic is used, the block delay will be longer.
![image](https://user-images.githubusercontent.com/37210306/125230394-46fc0900-e30b-11eb-8d9d-dac5efe156be.png)

Worse, for example, if the processing of the block takes 1 second, the next SR and the previous SR exceed 2 hops, it will directly lead to a block miss. This article details the optimization of the block broadcasting.

## Motivation
In order to speed up the block broadcast, let the block be broadcast on the whole network in a short time and improve the block miss rate, it is necessary to optimize the block broadcasting.

## Specifications
TODO
## Implementation
After testing and analysis, most of the transactions packaged in the block are also in the pending queue, and the transactions in the pending queue are successfully verified. So whether it can be considered, if the transaction in the block also exists in the pending queue, it is not necessary to verify the signature. Of course, there is a special case that needs to be considered. In the scenario of a multi-signature transaction, the multi-signature transaction will change the account permissions, so the final logic can be implemented as follows:
1. Extract the account list corresponding to the multi-signature transaction in the pending queue
2. If the transaction in the block also exists in the pending queue, and the corresponding account is not in the list of multiple signature accounts, you can skip the verification
3. Verify transaction signatures that have not skipped verification
## Rationale
TODO

**Comment by belka9091** [comment]
Nadya90932@gmail.com

**Comment by 138050856** [comment]
Hello world

**Comment by 138050856** [comment]
Nc
