### ISSUE TITLE
TIP-292: Change the free net limit

### ISSUE THREAD

**Issue by Federico2014** [tronprotocol/tips#292]
```
tip: 292
title: Change the free net limit 
author: federico<federico.zhen@tron.network>
discussions-to: https://github.com/tronprotocol/tips/issues/292
status: Draft
type: Standards Track
category: TRC
created: 2021-07-13
```

## Simple Summary

This TIP aims to add a proposal to make the `FREE_NET_LIMIT` parameter configurable.

## Abstract

The free net limit is the free bandwidth resource that can be used by the users to decrease the transaction fee.  At present, the free net limit is set as a fixed value `5000`. But recently,  some malicious behaviors are discovered to generate lots of fraudulent TRC10 transactions by abusing the free bandwidth resources. To restrain this situation, we propose to change the free net limit as configurable.

## Motivation 

We can restrain the fraudulent TRC10 transactions by increasing their cost.  So the free net limit value should be configurable instead of being a fixed value.  The free net value limit needs to be decreased when lots of fake TRC10 transactions appeared.  There should be a proposal to change the free net limit.

## Specification

The `FREE_NET_LIMIT` proposal type is defined as :  
```java
 public enum ProposalType {
  ...
  FREE_NET_LIMIT(61), // 5000, [0, 100_000]
  ...
 }
```
The proposal code is `61` and its initial value is set `5000`. The valid range of `FREE_NET_LIMIT`  parameter is `[0, 100,000]`.

The average bandwidth consumption is in the range `[300, 500]`, so the `FREE_NET_LIMIT` parameter can be adjusted according to the number of free transactions the users are allowed to use in a day. 

## Rationale
In addition, to restrain the fraudulent TRC10 transactions, it is quite necessary to adjust the free net limit to adapt to different situations in the TRON network.

**Comment by Federico2014** [comment]
For more detail about the harm of fradulent TRC10 transactions, please refer #286

**Comment by Cletitia** [comment]
This is good.

Too low fees are detrimental to the public chain's stability, as demonstrated by these spam transactions.

Therefore, I recommend setting the free bandwidth to zero, as there will always be opportunities to create zero-cost spam as long as there is any free bandwidth.

**Comment by a49688448** [comment]
I support it, so that I won’t receive a lot of rubbish coins inexplicably.
The cost of airdropping rubbish coins has increased.

**Comment by xiangyuan-chaoqing** [comment]
Modifying the free net limit can indeed reduce the number of free transfers by users, which indirectly increases the cost of users. Once this proposal takes effect, how much do you plan to adjust the free net limit to? How much is the appropriate free net limit, and is there any theoretical basis?

I have no opinion on making this parameter configurable, but regarding modify how much to adjust this value to , I hope to have a real theoretical basis and analysis, so that users can see the rationality and then let the SRs decide to modify it to which value. thanks.

**Comment by Federico2014** [comment]
> Modifying the free net limit can indeed reduce the number of free transfers by users, which indirectly increases the cost of users. Once this proposal takes effect, how much do you plan to adjust the free net limit to? How much is the appropriate free net limit, and is there any theoretical basis?
> 
> I have no opinion on making this parameter configurable, but regarding modify how much to adjust this value to , I hope to have a real theoretical basis and analysis, so that users can see the rationality and then let the SRs decide to modify it to which value. thanks.

Thank you for your question. As analyzed in  #286, the average transaction bandwidth consumption is 393.   The free net limit can be adjusted based it to decide the number of free  transactions for users in a day.

**Comment by hitlxy** [comment]
Strongly supported, the fixed large free bandwidth is used by the garbage TRC10 token issuer to damage the TRON ecology.  So it is necessary to adjust the free bandwidth through voting.
