### ISSUE TITLE
TIP-293: Change the total net limit 

### ISSUE THREAD

**Issue by Federico2014** [tronprotocol/tips#293]
```
tip: 293 
title: Change the total net limit 
author: federico<federico.zhen@tron.network>
discussions-to: https://github.com/tronprotocol/tips/issues/293
status: Draft
type: Standards Track
category: TRC
created: 2021-07-14
```

## Simple Summary

This TIP aims to add a proposal to make the `TOTAL_NET_LIMIT` parameter configurable.

## Abstract

The total net limit stands for the bandwidth resource distributed to all the users when they freeze their TRX balances. 
At present, the total net limit `TOTAL_NET_LIMIT` parameter is set as a fixed value of 43.2 billion according to a rough estimate, which is not flexible enough to adapt to the rapid development of the TRON network. So we propose to change the total net limit parameter as configurable.

## Motivation
The current fixed `TOTAL_NET_LIMIT` parameter is estimated by the following equation:
```
43,200,000,000 = 500 * 1000 * 86400
```
where `500` stands for the average transaction byte size, `1000` stands for TPS, and `86400` stands for the total number of seconds in a day.

However, the estimated value is not accurate. Instead of being a fixed value, it is better to make the `TOTAL_NET_LIMIT` parameter configurable. 

## Specification

The `TOTAL_NET_LIMIT` proposal type is defined as :  
```java
 public enum ProposalType {
  ...
  TOTAL_NET_LIMIT(62); // 43_200_000_000L, [0, 1000_000_000_000L]
  ...
 }
```
The proposal code is `62` and its initial value is set `43,200,000,000`. The valid range of `TOTAL_NET_LIMIT`  parameter is `[0, 1000,000,000,000]`.

## Rationale
It is quite necessary to adjust the total net limit to adapt to different situations in the TRON network.

**Comment by a49688448** [comment]
Fully supported, so that the total amount of the network can be dynamically adjusted.

**Comment by hitlxy** [comment]
Typo?      
"The valid range of **_FREE_NET_LIMIT_** parameter is [0, 1000,000,000,000]." in Specification section.     
Maybe "FREE_NET_LIMIT" is a typo

I could not agree more with this proposal, the less fixed values, the more stable and mature for TRON network.

**Comment by Federico2014** [comment]
> Typo?
> "The valid range of **_FREE_NET_LIMIT_** parameter is [0, 1000,000,000,000]." in Specification section.
> Maybe "FREE_NET_LIMIT" is a typo
> 
> I could not agree more with this proposal, the less fixed values, the more stable and mature for TRON network.

You are right, the typo is fixed. Thanks

**Comment by xiangyuan-chaoqing** [comment]
In Proposal 286, the developer made a very good suggestion (https://github.com/tronprotocol/tips/issues/286#issuecomment-877927516). I suggest you consider the possibility of this and create a new TIP based on this suggestion. 

That suggestion is very good, Different types of token transfers should consume different bandwidth. Rather than what it is now, the unit price of bandwidth consumed by TRX, TRC10, and TRC20 is the same. Based on the current design, once the bandwidth unit price is adjusted, the transfer cost of the three tokens will be impacted. I think this is not what we expected. If Proposal 286 only wants to suppress TRC10 transactions, then the parameters modified by the proposal should only affect TRC10.

In order to control these more finely and flexibly, I also reiterate Call-me-nobody’s suggestion that a TIP should be added to make the bandwidth consumed by TRX, TRC10, TRC20 transfers can be adjusted individually. More broadly, The bandwidth consumption coefficient can be set according to the type of System Contract.

**Comment by Omo-Coc** [comment]
Change to configurable, do you want to increase the TOTAL_NET_LIMIT or reduce the TOTAL_NET_LIMIT?

**Comment by Cletitia** [comment]
Customizability is consistent with the concept of decentralization.
I suggested in #292 that the free bandwidth be set to zero. I believe that the `TOTAL_NET_LIMIT` parameter can be increased, which will lower the cost to normal users and the amount of spam.

**Comment by Federico2014** [comment]
> In Proposal 286, the developer made a very good suggestion ([#286 (comment)](https://github.com/tronprotocol/tips/issues/286#issuecomment-877927516)). I suggest you consider the possibility of this and create a new TIP based on this suggestion.
> 
> That suggestion is very good, Different types of token transfers should consume different bandwidth. Rather than what it is now, the unit price of bandwidth consumed by TRX, TRC10, and TRC20 is the same. Based on the current design, once the bandwidth unit price is adjusted, the transfer cost of the three tokens will be impacted. I think this is not what we expected. If Proposal 286 only wants to suppress TRC10 transactions, then the parameters modified by the proposal should only affect TRC10.
> 
> In order to control these more finely and flexibly, I also reiterate Call-me-nobody’s suggestion that a TIP should be added to make the bandwidth consumed by TRX, TRC10, TRC20 transfers can be adjusted individually. More broadly, The bandwidth consumption coefficient can be set according to the type of System Contract.

Very nice suggestions, we will consider them. Thanks

**Comment by Federico2014** [comment]
> Change to configurable, do you want to increase the TOTAL_NET_LIMIT or reduce the TOTAL_NET_LIMIT?

I can't decide. Only the committee can make a proposal to alter the `TOTAL_NET_LIMIT`.
