### ISSUE TITLE
TIP-306: Adapt to solidity_0.8.4

### ISSUE THREAD

**Issue by Lredhdx** [tronprotocol/tips#306]
```
tip: 306
title: Adapt to solidity_0.8.4
author: neo.hong@tron.network
status: Draft
type: Standards Track
category: VM
created: 2021-07-29
```

## Simple Summary

To Adapt to solidity_0.8.4.

## Abstract

Solidity_0.8.4 supports custom errors via the `error` keyword and introduce the `revert` statement. To adapt to solidity_0.8.4 we need add `Error` type in java-tron smart contract ABI.

## Implementation

we need add `Error` EntryType in message ABI in smart_contract.proto file.

**Comment by yanghang8612** [comment]
Solidity example on ethereum solidity docs is as follows:
```
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.4;

/// Not enough funds for transfer. Requested `requested`,
/// but only `available` available.
error NotEnoughFunds(uint requested, uint available);

contract Token {
    mapping(address => uint) balances;
    function transfer(address to, uint amount) public {
        uint balance = balances[msg.sender];
        if (balance < amount)
            revert NotEnoughFunds(amount, balance);
        balances[msg.sender] -= amount;
        balances[to] += amount;
        // ...
    }
}
```
As we can see, we can write `revert(...)` like this `revert NotEnoughFunds(...)`.
I think this feature is very useful for all solidity developers.
Especially while debugging revert exception, developers can get more information.

**Comment by Benson0224** [comment]
This issue will be closed as it is already implemented in https://github.com/tronprotocol/tips/blob/master/tip-306.md
and it is already included in https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.3.0
