### ISSUE TITLE
Proposal: The unit price of energy proposed to be increased to 420 sun

### ISSUE THREAD

**Issue by Omo-Coc** [tronprotocol/tips#316]
# Proposal: The unit price of energy proposed to be increased to 420 sun

## Simple Summary
Adjust the unit price of energy to 420 sun, after this change, the fee of 1 energy will be 420 sun.
## Motivation
Increasing the energy unit price would further decrease the daily Net new TRX from positive to negative, which will decrease the inflation rate, promote the staking rate and make the overall TRX circulation deflationary.
## Timeline
The estimated timeline
- Creation time of the voting request: 17th August 2021
- The effective time of voting request: 14:00, 20th August 2021
## How to Initialize the Voting Request
Change the unit price of energy to 420 sun
- createProposal 11 420 47 10000000000
## Background
The unit price of energy and bandwidth has been increased twice, firstly increased from 10 sun to 40 sun on 25th Nov. 2020, secondly increased from 40 sun to 140 sun on 11th Feb. 2021, and in the months that followed, the daily Net new TRX has been greatly reduced due to more TRX burned. For details, see https://tronscan.org/#/data/charts/supply.
![image](https://user-images.githubusercontent.com/68627959/128834618-934eb868-eeda-462f-8557-cf161a3dae06.png)

On the other hand, due to the increased fees, users will get bandwidth or energy by staking TRX to reduce the consumption of TRX. With the increase in fees, the TRX staking ratio also shows a growing trend. From 22% in early November 2020 to 32% in mid-July 2021, the network-wide stacking rate has increased by about 10%. For detail, see https://tronscan.org/#/data/charts/OverallFreezingRate.
![image](https://user-images.githubusercontent.com/68627959/128834662-1d61a39d-6217-43ae-98bf-70e0310a10de.png)

The following two graphs show that the number of energy obtained by burning TRX starts to decrease, while the number of energy obtained by staking TRX is increasing ​​shortly after the fee increase, such as after April 2021. Check detail at https://tronscan.org/#/data/stats/EnergyConsume.
![image](https://user-images.githubusercontent.com/68627959/128834686-bf242c9a-0cd4-4931-8355-626cb7ec5b07.png)

![image](https://user-images.githubusercontent.com/68627959/128834703-4ed9e20a-e646-40ea-a7ef-fd1079dec278.png)

In addition, there was no significant change in the daily transaction volume after the two proposals to increase the unit price of energy and bandwidth on November 25, 2020, and February 11, 2021. Even after January 20, 2021, there was a significant increase in daily transaction volume, from a previous average of approximately 2 million transactions per day to a daily average of approximately 3.5 million transactions per day. In late July, the average daily number of transactions grew to 5 million transactions. The above data suggest that the increase in fees did not lead to a decrease in transaction volume. Check detail at: https://tronscan.org/#/data/stats/txOverviewStatsType.
![image](https://user-images.githubusercontent.com/68627959/128834723-c7393eb7-3e4c-4bdb-895d-403ee16d6951.png)

Other than that, the increase of the unit price of bandwidth and energy did not impact the daily active users. Check detail at: https://tronscan.org/#/data/stats/activeAccounts.
![image](https://user-images.githubusercontent.com/68627959/128834754-5577d455-3bf3-4c5c-8f4b-5dd7b03f3496.png)

## The Data Analysis
From the previous analysis, it can be seen that increasing the unit price of energy and bandwidth can increase the amount of TRX burned, while at the same time, users will stake more TRX to avoid TRX burning.

Due to the increase of the unit price of energy, a responsive adjustment of the upper limit of single smart contract fees (current value of 5000 TRX) is required. According to statistics, the highest energy cost of transactions since July is	
20,002,026, that is 8400 TRX (20002026 * 420 / 1000000), so the value of the upper limit of single smart contract fees needs to be adjusted to 10000 TRX, 10000000000 sun.

### Net new TRX

The average Energy and bandwidth consumption data from July 19, 202, to July 23, 2021, were used as the base data for the analysis. 2,974,946 TRX were burned to obtain energy and 75,222 TRX were burned to obtain bandwidth. 

On 26th July, the unit price of bandwidth was changed to 1000 sun, from August 03 to August 08, An average of 3,280,166 TRX were burned to obtain energy and 315,705 TRX were burned to obtain bandwidth. 

|                                                              | 2021.07.17~2021.07.23                           | 2021.08.03~2021.08.09                            | Future                                             |
| ------------------------------------------------------------ | ----------------------------------------------- | ------------------------------------------------ | -------------------------------------------------- |
| The price of bandwidth                                       | 140 sun                                         | 1000 sun                                         | 1000 sun                                           |
| The price of energy                                          | 140 sun                                         | 140 sun                                          | 420 sun                                            |
| TRX Burned for bandwidth                                     | 75,222 trx                                      | 315,705 trx                                      | 315,705 trx                                        |
| TRX Burned for energy                                        | 2,974,946 trx                                   | 3,280,166 trx                                    | 9,840,499 trx                                      |
| TRX produced(Block rewards + Voting Rewards)                 | 460,224 + 4,602,240 = 5,062,464 trx             | 5,062,464 trx                                    | 5,062,464 trx                                      |
| Net new TRX = TRX produced -  TRX burned for bandwidth - TRX burned for energy | 5,062,464 - 75,222 -  2,974,946 = 2,012,296 trx | 5,062,464 - 315,705 - 3,280,166 =  1,466,593 trx | 5,062,464 - 315,705  -  9,840,499 = -5,093,740 trx |
| Net new TRX Rate = Net new TRX / TRX produced                | 2,012,296 / 5,062,464 = 39.75 %                 | 1,466,593 / 5,062,464 = 28.97 %                  | -5,093,740 / 5,062,464 = -100%                     |

From the future column,  4,746,759 TRX need to be burned for obtaining energy(5,062,464 - 315,705 = 4,746,759) to make the daily Net new TRX be 0, which means the price of energy needs to be raised to 1.5 times the original. And from the previous analysis, we know that increased fees will make users get energy and bandwidth by stacking TRX, so, the TRX Burned for bandwidth of "2021.08.03 - 2021.08.09" is not increased 7 times compared to "2021.07.17 - 2021.07.23", just 4 times. Therefore, 1.5 times the price of energy is not enough to make the Net new TRX be negative, so we propose to make it 3 times(1.5 * 7 / 4), that is 420 sun.

### Staking Rate

|                        | 2020.11.16~2020.11.23 | 2020.12.14~2020.12.21 | 2021.07.17~2021.07.23 | Future         |
| :--------------------- | --------------------- | --------------------- | --------------------- | -------------- |
| The price of bandwidth | 10 sun                | 40 sun                | 140 sun               | 1000 sun       |
| The price of energy    | 10 sun                | 40 sun                | 140 sun               | 420 sun        |
| Staking rate           | 25.05%                | 28.66%                | 32.79%                | 36.79%         |
| Staking amount         | 25,389,200,153        | 29,079,397,968        | 33,399,504,580        | 37,473,857,075 |

Currently, there is no evidence that shows the specific relationship between the change in resource costs and the staking rate, so the estimated staking amount is based on assumption, here we assume the relationship between resource cost and staking amount is a linear relationship, so here is the calculation:
From 10 sun to 40 sun there is a 4-fold increase in unit price and there is about 4%(28.66% - 25.05% = 3.61%) of the staking rate, from 40 sun to 140 sun there is 3.5 times increase in unit price and there is about 4.13% increase in staking rate, so when the price of bandwidth is 1000sun and the price of energy is 420, there is at least 3 times increase in unit price, so we assume that there is 4% increase in staking rate, that is 32.79 % + 4% = 36.79%.

**Comment by woaichixigua07** [comment]
According to the data above, there will be a higher increase in the staking rate of TRX, and at the same time it will reduce the TRX inflation rate, which is a good direction for the development of TRON. For ordinary users, daily transactions will not have much impact, and making transfers on TRON is still cheap. The increase in fees is completely negligible compared to the increase in the value of TRX.

**Comment by hitlxy** [comment]
I think Tron is following Ethereum 1559 proposal which destroys partial reward of miner, up to now，the total value of destroyed ETH is about 50 million dollars, nowadays the ETH price has already up to 3100. so boss sun wants to follow ethereum, right? and the TRX price will rise soon

**Comment by Cletitia** [comment]
I'm guessing TRON presented a deflation strategy at this point in order to keep up with Ethereum's EIP1559.

This is a wonderful thing, because news that can drive the coin's price up is unquestionably excellent news for TRX holders.
However, I believe it is still impossible to predict whether this would actually improve the currency's price, but I maintain a positive attitude and await its performance.

**Comment by joker-gdb** [comment]
According to this algorithm, 50 million trx can be burned in one month, 600 million trx can be burned in a year, that  is really not a small amount.

**Comment by nobody-cares-it** [comment]
First of all, i fully agree that make TRX deflation is the right direction, But deflation can be achieveed in many ways. Increasing the fee is no doubt an option, but i believe this is not the best one. 

There are many ways to make TRX deflation, for example reduce the new generted TRX is also an opion, for example they can set up an plan to gradually reduce the output of TRX, for example, in 5 years, reduce the new genertaed TRX to 10% of the current. This is a common way adopted by many other public chains. Quickly looked to TRON scan, at least i can see following parameters which can be used to archive this. 

![image](https://user-images.githubusercontent.com/88758176/128966023-df909e79-e272-4db3-80c1-0e2635fb58c5.png)
![image](https://user-images.githubusercontent.com/88758176/128966036-7d930bf1-6264-434d-8fbd-f852d4a24b6b.png)

However,  it request 18 SR to agree on that, not sure whether all SR can agree on that or not. Sometimes, decentralization has indeed created a lot of suffering. 

Back to this issue, Whether the fee increasing can actually lead to deflation is uncertain, especially if more user started to staking.  i would say this proposal need more data or more time to verify, let us see. 

I am also waiting to see other options from other experts which can archive deflation.

**Comment by zhangwenhua-tron** [comment]
> First of all, i fully agree that make TRX deflation is the right direction, But deflation can be achieveed in many ways. Increasing the fee is no doubt an option, but i believe this is not the best one.
> 
> There are many ways to make TRX deflation, for example reduce the new generted TRX is also an opion, for example they can set up an plan to gradually reduce the output of TRX, for example, in 5 years, reduce the new genertaed TRX to 10% of the current. This is a common way adopted by many other public chains. Quickly looked to TRON scan, at least i can see following parameters which can be used to archive this.
> 
> ![image](https://user-images.githubusercontent.com/88758176/128966023-df909e79-e272-4db3-80c1-0e2635fb58c5.png)
> ![image](https://user-images.githubusercontent.com/88758176/128966036-7d930bf1-6264-434d-8fbd-f852d4a24b6b.png)
> 
> However, it request 18 SR to agree on that, not sure whether all SR can agree on that or not. Sometimes, decentralization has indeed created a lot of suffering.
> 
> Back to this issue, Whether the fee increasing can actually lead to deflation is uncertain, especially if more user started to staking. i would say this proposal need more data or more time to verify, let us see.
> 
> I am also waiting to see other options from other experts which can archive deflation.

Thanks for your suggestion.
Actually, the proposal-6 is not work after the proposal-30 has been activated(more detail check at https://tronscan.org/#/proposal/22), it means that the reward for the SR, 16 TRX for the 27 SRs and 160 TRX for the 127 SRs, will be divided to the voters.

Besides that, from the https://www.stakingrewards.com/staking we can see that the reward rate is very low compared to other blockchain. But the community will discuss your suggestions carefully.

**Comment by Dendorion** [comment]
You guys truly going this route again? You tried with proposal 50 and proposal 51 which got heavy critics from your community. Proposal 50 deemed to be the one to make tron deflationary which it only dit for 6 days. As we saw a massive decrease in daily dapp users afterwards.

Not to mention the massive outflow of dapps it has caused among the ecosystem towards other chains.

The latest energy increase you guys hoped to bring back trc10 scam transactions and maybe make tron deflationary. This also not had the effect as hoped as people are still receiving many scam tokens on the daily base.. Keeping up your burned trx count.

You mention the community has proposed this which is untrue getting the first reactions the TRON community is heavily against another increase in fee prices. Tron used to be a chain for everyone with cheap and fast transactions those days have long gone. More fee increases will drive out more little guys and more dapps as they will become to expensive to maintain.

And the efforts done by the community to bring more developers and projects to TRON will be renderered absolute as they happily return to a cheaper chain.

There are more routes to deflation instead of keep jacking up the prices. 

Just my personal view on this proposal.

**Comment by DappDevnie** [comment]
Normally we would not respond but we feel the need to respond this time as you are running wild. 

We are running a succesfull dapp on Tron for the past 2 years and have 4500 holders and 15k TG members. On which we did a survey on the above proposal of which 11000 voted. With a staggering 97% beeing AGAINST the mentioned proposal.

So the question from the TRON community is which community have you been speaking to!?

Let's crunch some numbers as you said proposal 50 and 51 didn't have any mayor impact.

When proposal 50 was initiated we saw an steep decrease in dapp users of 45% while before we kept increasing on the daily base. This kept on and recovered only slightly ending up at 35% less use and much higher maintaince costs. But we managed to survive..

Here comes proposal 51 the energy one.. Pushing another dent in our daily users with another 10% decrease and increase in maintaince costs.

Meanwhile the dapp users on tron has decreased significantly we seen a rise on other chains and have thus decided to also go multichain. Simply because the fees on chains as BSC are a lot cheaper then on TRON.

We like tron because it was cheap and fast and thus gave everyone the possibility to use crypto. You guys are changing the environment for this and turning tron slowly into a ghost chain for the rich. If the increase in fees continues we will consider taking our project off tron and move it to a more viable chain.

**Comment by renchenchang** [comment]
> Normally we would not respond but we feel the need to respond this time as you are running wild.
> 
> We are running a succesfull dapp on Tron for the past 2 years and have 4500 holders and 15k TG members. On which we did a survey on the above proposal of which 11000 voted. With a staggering 97% beeing AGAINST the mentioned proposal.
> 
> So the question from the TRON community is which community have you been speaking to!?
> 
> Let's crunch some numbers as you said proposal 50 and 51 didn't have any mayor impact.
> 
> When proposal 50 was initiated we saw an steep decrease in dapp users of 45% while before we kept increasing on the daily base. This kept on and recovered only slightly ending up at 35% less use and much higher maintaince costs. But we managed to survive..
> 
> Here comes proposal 51 the energy one.. Pushing another dent in our daily users with another 10% decrease and increase in maintaince costs.
> 
> Meanwhile the dapp users on tron has decreased significantly we seen a rise on other chains and have thus decided to also go multichain. Simply because the fees on chains as BSC are a lot cheaper then on TRON.
> 
> We like tron because it was cheap and fast and thus gave everyone the possibility to use crypto. You guys are changing the environment for this and turning tron slowly into a ghost chain for the rich. If the increase in fees continues we will consider taking our project off tron and move it to a more viable chain.

BSC is cheaper?  Could you give specific data？

**Comment by F3D3Tron** [comment]
The calculations are based on maintaining the number of users, and x3 in the increase of energy will lower the number of users in the dapps, the number of transactions and the amount of TRX burned.
We have to look for other solutions than "raising taxes". 
In the end we will have less users, less dapps and we will not burn TRX daily. Only Tron foundation dapps will continue.

**Comment by zhangwenhua-tron** [comment]
> The calculations are based on maintaining the number of users, and x3 in the increase of energy will lower the number of users in the dapps, the number of transactions and the amount of TRX burned.
> We have to look for other solutions than "raising taxes".
> In the end we will have less users, less dapps and we will not burn TRX daily. Only Tron foundation dapps will continue.

@F3D3Tron , Thanks for your suggestion.
According to the content of this proposal,  the increase of the unit price of bandwidth and energy did not impact the daily transaction volume and the daily active users. 

Let's consider the problem from a different perspective. As prices increase, users will send more valuable transactions, which in turn will improve the quality of the entire TRON ecosystem,  which can further attract more good developers to TRON.

**Comment by Lefgk** [comment]
Does the daily transaction chart in tronscan include the dust transactions that transfer 0.000001 TRX, a hundred of times per block?
Are these wallets considered as active wallets too?

**Comment by zhangwenhua-tron** [comment]
@DappDevnie @Dendorion 
Thanks for your reply.
Actually, 50 proposal has nothing to do with the unit price of energy and bandwidth, you can get more detail from https://tronscan.org/#/proposal/50.

The community is trying to enhance the quality and value of the entire TRON ecosystem not to discourage developers from joining. The community will carefully discuss and consider your concerns and suggestions.

**Comment by DappDevnie** [comment]
> > Normally we would not respond but we feel the need to respond this time as you are running wild.
> > We are running a succesfull dapp on Tron for the past 2 years and have 4500 holders and 15k TG members. On which we did a survey on the above proposal of which 11000 voted. With a staggering 97% beeing AGAINST the mentioned proposal.
> > So the question from the TRON community is which community have you been speaking to!?
> > Let's crunch some numbers as you said proposal 50 and 51 didn't have any mayor impact.
> > When proposal 50 was initiated we saw an steep decrease in dapp users of 45% while before we kept increasing on the daily base. This kept on and recovered only slightly ending up at 35% less use and much higher maintaince costs. But we managed to survive..
> > Here comes proposal 51 the energy one.. Pushing another dent in our daily users with another 10% decrease and increase in maintaince costs.
> > Meanwhile the dapp users on tron has decreased significantly we seen a rise on other chains and have thus decided to also go multichain. Simply because the fees on chains as BSC are a lot cheaper then on TRON.
> > We like tron because it was cheap and fast and thus gave everyone the possibility to use crypto. You guys are changing the environment for this and turning tron slowly into a ghost chain for the rich. If the increase in fees continues we will consider taking our project off tron and move it to a more viable chain.
> 
> BSC is cheaper? Could you give specific data？

Most certainly in the case one of our investors does not have enough energy or bandwidth a transaction will cost them between 20 or 30 trx ( $1.6 - $2.4) while the same transaction on bsc would cost them ( $0.42-$0.65).

Not to mention the failed transactions sucking out 100 trx from the wallets.

By making the costs of these resources more expensive the smaller users will be driven away from tron. These cost alterations won't hurt the bigger whales because they got all their resources frozen the everyday smaller users are the ones who are beeing hit. And these are the investors which make the ecosystem thrive.

**Comment by DappDevnie** [comment]
> > The calculations are based on maintaining the number of users, and x3 in the increase of energy will lower the number of users in the dapps, the number of transactions and the amount of TRX burned.
> > We have to look for other solutions than "raising taxes".
> > In the end we will have less users, less dapps and we will not burn TRX daily. Only Tron foundation dapps will continue.
> 
> @F3D3Tron , Thanks for your suggestion.
> According to the content of this proposal, the increase of the unit price of bandwidth and energy did not impact the daily transaction volume and the daily active users.
> 
> Let's consider the problem from a different perspective. As prices increase, users will send more valuable transactions, which in turn will improve the quality of the entire TRON ecosystem, which can further attract more good developers to TRON.

The statistics on this can not be taken serious as it also takes in account the dust attacks many wallets get and the received trc10 scam transactions.

As we can see from the start of 2021 we have a tremendous increase in trc10 transactions and its still on the rise. Mainly the scam tokens tron investors receive daily. Plus we can see a great increase in usdt transfers. 

To find more specific data on this talk with dapp owners and they will tell you what has happened.

**Comment by Dendorion** [comment]
> @DappDevnie @Dendorion
> Thanks for your reply.
> Actually, 50 proposal has nothing to do with the unit price of energy and bandwidth, you can get more detail from https://tronscan.org/#/proposal/50.
> 
> The community is trying to enhance the quality and value of the entire TRON ecosystem not to discourage developers from joining. The community will carefully discuss and consider your concerns and suggestions.

Correct we've had so many proposals lately offcourse I ment proposal 51 and the recently passed 67.

Who exactly is this community you are talking about and how can we tronics get a voice in there?  Feel free to reach out to me.

**Comment by renchenchang** [comment]
> > > Normally we would not respond but we feel the need to respond this time as you are running wild.
> > > We are running a succesfull dapp on Tron for the past 2 years and have 4500 holders and 15k TG members. On which we did a survey on the above proposal of which 11000 voted. With a staggering 97% beeing AGAINST the mentioned proposal.
> > > So the question from the TRON community is which community have you been speaking to!?
> > > Let's crunch some numbers as you said proposal 50 and 51 didn't have any mayor impact.
> > > When proposal 50 was initiated we saw an steep decrease in dapp users of 45% while before we kept increasing on the daily base. This kept on and recovered only slightly ending up at 35% less use and much higher maintaince costs. But we managed to survive..
> > > Here comes proposal 51 the energy one.. Pushing another dent in our daily users with another 10% decrease and increase in maintaince costs.
> > > Meanwhile the dapp users on tron has decreased significantly we seen a rise on other chains and have thus decided to also go multichain. Simply because the fees on chains as BSC are a lot cheaper then on TRON.
> > > We like tron because it was cheap and fast and thus gave everyone the possibility to use crypto. You guys are changing the environment for this and turning tron slowly into a ghost chain for the rich. If the increase in fees continues we will consider taking our project off tron and move it to a more viable chain.
> > 
> > 
> > BSC is cheaper? Could you give specific data？
> 
> Most certainly in the case one of our investors does not have enough energy or bandwidth a transaction will cost them between 20 or 30 trx ( $1.6 - $2.4) while the same transaction on bsc would cost them ( $0.42-$0.65).
> 
> Not to mention the failed transactions sucking out 100 trx from the wallets.
> 
> By making the costs of these resources more expensive the smaller users will be driven away from tron. These cost alterations won't hurt the bigger whales because they got all their resources frozen the everyday smaller users are the ones who are beeing hit. And these are the investors which make the ecosystem thrive.

Is your solidity code same on Tron and BSC?

**Comment by simbadMarino** [comment]
Please please don’t do it!!! You are using wrong data to support your proposal. The increase on activity is for sure due to USDT and dust attacks, no significant dApp usage. Just go to wink telegram group and you will know how the increase on fees have deteriorated dApps (even the ones under JSun name) the DICE section is constantly running out of energy and bandwidth just after the last increase in energy fees occurred, if this is happening to a JS dApp just imagine how this is hurting small developers??? 

I’m also interested on knowing which community are your talking to… maybe you are listening the short term trading community wanting a high spike on TRX price to sell their bags and move on to BSC or any other chain. Listen to your true community which is on the devs and users of those dApps. Having a higher number of dApps and valuable projects will increase transactions and thus burning will occur without increasing fees. 
Thanks for reading

**Comment by marcosjimenezgonzalez** [comment]
This proposal is a mistake, do not charge users with more problems.  more fees, failed transactions, losses and new impediments for new users or low-income users ... in short, a bad idea

**Comment by WindsofChange92** [comment]
This proposal will kill users period. Might as well switch to bsc.

**Comment by zhangwenhua-tron** [comment]
> To find more specific data on this talk with dapp owners and they will tell you what has happened.

@DappDevnie Thanks for your reply.
The community will try to do more data analysis and research.

And if you have more specific data, you can how us here, thank you.

**Comment by sai-voiddev** [comment]
These proposals of increasing fees . is one of the greadiest and most stupid thing i have ever seen in any of the top blokchains in the scene .

we are losing users base and I can feel that on all the projects in the tron scene . 

most of the developers have already left tron and those who stayed are thinking to leave . this will just pull the trigger and tron will be "just" managed and used by the tron foundation leteraly a waistland.

please stop this joke and decrease the fees already .

**Comment by InterCroneworld** [comment]
fee need to decrease again. we need to work on the demand and not on the fees.

**Comment by DeamonDJ** [comment]
> You guys truly going this route again? You tried with proposal 50 and proposal 51 which got heavy critics from your community. Proposal 50 deemed to be the one to make tron deflationary which it only dit for 6 days. As we saw a massive decrease in daily dapp users afterwards.
> 
> 
> 
> Not to mention the massive outflow of dapps it has caused among the ecosystem towards other chains.
> 
> 
> 
> The latest energy increase you guys hoped to bring back trc10 scam transactions and maybe make tron deflationary. This also not had the effect as hoped as people are still receiving many scam tokens on the daily base.. Keeping up your burned trx count.
> 
> 
> 
> You mention the community has proposed this which is untrue getting the first reactions the TRON community is heavily against another increase in fee prices. Tron used to be a chain for everyone with cheap and fast transactions those days have long gone. More fee increases will drive out more little guys and more dapps as they will become to expensive to maintain.
> 
> 
> 
> And the efforts done by the community to bring more developers and projects to TRON will be renderered absolute as they happily return to a cheaper chain.
> 
> 
> 
> There are more routes to deflation instead of keep jacking up the prices. 
> 
> 
> 
> Just my personal view on this proposal.
> 
> 
> 
> 

I fully agree with this and would say a big 'NO' is a logical road to follow. Big whales have got lots of frozen TRX thus making transaction free and cheap. New entrants and the smaller guys have not got these kind of resources and transaction fee's of more than 1 USD are absolutely absurd. You are treading a slippery slope ands raising prices is not the path to follow. Grow the platform by having more Dapps and smaller fish do transactions. The power is in the masses and they will make or break (in this case break) the future of Tron. 

Don't do this and find another way to be more deflationary as a coin. Focus on low fee's and fast transactions. 

Just my humble opinion as a specialist in payments for more than 20 years.

**Comment by zhangwenhua-tron** [comment]
@DeamonDJ @sai-voiddev 
Thanks for your feedbacks, and we will send your suggestions and ideas back to the community.
The community will carefully consider your views as well as those of other developers.

**Comment by zhangwenhua-tron** [comment]
> Most certainly in the case one of our investors does not have enough energy or bandwidth a transaction will cost them between 20 or 30 trx ( $1.6 - $2.4) while the same transaction on bsc would cost them ( $0.42-$0.65).

@DappDevnie Hi, can you provide the detailed calculation process?

**Comment by joker-gdb** [comment]
> Most certainly in the case one of our investors does not have enough energy or bandwidth a transaction will cost them between 20 or 30 trx ( $1.6 - $2.4) while the same transaction on bsc would cost them ( $0.42-$0.65).
> 
> Not to mention the failed transactions sucking out 100 trx from the wallets.
> 
> By making the costs of these resources more expensive the smaller users will be driven away from tron. These cost alterations won't hurt the bigger whales because they got all their resources frozen the everyday smaller users are the ones who are beeing hit. And these are the investors which make the ecosystem thrive.

@DappDevnie 

It is meaningless compared to bsc, because from the current unit price of 140sun, TRON is originally more expensive than BSC, but I don’t think BSC has any advantages. The public chain of the exchange itself has no advantage, because it will be rejected by other mainstream exchanges.

Continue to increase prices TRON continues to lose its price advantage, but I think TRON’s competitors will not be exchange public chains such as BSC, HECO, etc.

**Comment by zhangwenhua-tron** [comment]
> We have been looking into migrating to SUN chain to cut costs for our users , but the documentation provided for this is not nearly sufficient . Tron foundation should show more openness and willingness to help developers build on this chain . Proper documentation should always be available .

@DappDevnie What type of documents do you need? Till now, you can find the relevant developer documentation at https://developers.tron.network/, for example, you can find the api document at https://developers.tron.network/reference#api-key.

**Comment by ustx** [comment]
This a bad proposal for the whole Tron dApp ecosystem. The main reason developers look at Tron is the low fees compared to Ethereum. Now Ethereum will probably see a decrease in the fees in the near future and this proposal will have the immediate effect of increasing Tron smart contracts fees. It really does not make any sense.
Ask yourself: why USDT TRC20 ha beaten the other networks? Because of the lower fees.
The same goes for many dApps, that if this proposal passes will look elsewhere.
Think again, cancel this proposal, for the good of the Tron future.
An average smart contract operation will cost over 3$, compared to the current <1$.
Tron's value is in the ecosystem, not in the TRX token itself. If you want the token price to increase, we need to increase the adoption of Tron as the building block for more and more dApps, otherwise this project is just like many other deflationary tokens out there.

**Comment by zhangwenhua-tron** [comment]
@ustx  Thanks for your reply, and for me personally, I think it is valuable. But there are several aspects that need to be discussed with you again. 

These are my personal views and do not represent the community, we are free to discuss.

> why USDT TRC20 ha beaten the other networks? Because of the lower fees.

There is no denying that low prices can attract many developers, but at the same time, too low prices can have some negative effects, such as airdrops with fraudulent purposes.
In fact, I think TRON community not only wants to attract more developers, but also wants to attract more good developers, so as to bring more high quality applications and drive the development of TRON ecosystem.

Raising the price will bring some impact to some developers, but I believe the community will consider these factors and make the right decision.


> An average smart contract operation will cost over 3$, compared to the current <1$.

I counted the smart contract calls after 7.27 and got a different result than you.
From 7.27 till now, an average smart contract requires 360 bandwidth and 22,142 energy, that is 360 * 1000/ 1000000.0 + 22142 * 140  / 1000000.0 = 3.45988 trx, about $0.2768. Even after the unit price of energy is increased to be 430, the total coat is 360 * 1000/ 1000000.0 + 22142 * 430  / 1000000.0 = 9.88106 trx, about $0.79.

 

> Now Ethereum will probably see a decrease in the fees in the near future and this proposal will have the immediate effect of increasing Tron smart contracts fees.

If you are talking about EIP1559 here, I think this is not the intent of the EIP. As a side effect of a more predictable base fee, EIP-1559 may lead to some reduction in gas prices if we assume that fee predictability means users will overpay for gas less frequently.  
The ongoing movement of applications to rollups and Layer 2s will be what greatly reduce fees. 



> Tron's value is in the ecosystem, not in the TRX token itself. If you want the token price to increase, we need to increase the adoption of Tron as the building block for more and more dApps, otherwise this project is just like many other deflationary tokens out there.

I couldn't agree with you more.  The community has also been following the latest developments in the current blockchain system and finding ways to promote the TRON ecosystem, such as NFT and some great ethereum Dapps.


Thanks again for your reply!

**Comment by InterCroneworld** [comment]
@zhangwenhua-tron which contract requiere only 22,142. send maybe but if you stake or unstake in liqu pools or trade you need 60,000 -150,000 energy and if you compare this to BSC its much cheaper on BSC already than on tron. Tron growing greate in the last month but if we rais again the fees it kill the system.

**Comment by zhangwenhua-tron** [comment]
> @zhangwenhua-tron which contract requiere only 22,142. send maybe but if you stake or unstake in liqu pools or trade you need 60,000 -150,000 energy and if you compare this to BSC its much cheaper on BSC already than on tron. Tron growing greate in the last month but if we rais again the fees it kill the system.

@InterCroneworld  22,142 is the average energy which smart contract requires, from 7.27 till the time I commented the previous message, there 23801216 smart contract calls in total which costed 527028126437 energy, and 527028126437 / 23801216 = 22142.

**Comment by infoglitz** [comment]
Proposal got rejected .. :)

**Comment by Benson0224** [comment]
Thank everyone for contributing to this proposal. 

This issue will be closed, check detail of the voting request at https://tronscan.org/#/proposal/68
