### ISSUE TITLE
usdt sent to the anonymous address is always displayed in synchronization

### ISSUE THREAD

**Issue by Admini123** [tronprotocol/tips#321]
![111122](https://user-images.githubusercontent.com/12041836/129860560-f93438a5-6d12-4fd7-b308-d81fca817db1.png)
 is always displayed in synchronization
The USDT sent to the anonymous asset is not displayed, it has been synchronized for three days.

**Comment by Benson0224** [comment]
This issue is already followed with https://github.com/tronprotocol/java-tron/issues/3997
And the team is checking now. this issue will be closed and let us use https://github.com/tronprotocol/java-tron/issues/3997 to follow it.
