### ISSUE TITLE
Proposal: Enable TVM freezing balance and voting SR related instructions

### ISSUE THREAD

**Issue by fbsobreira** [tronprotocol/tips#325]
## Introduction

Enable `#52(allowTvmFreeze)` and `#59(allowTvmVote)` proposals, so that smart contracts can freeze and unfreeze their balance, vote SR and share the block reward by using newly provided instructions.

## Motivation

Common user can freeze TRX to get resource, such as TRON power, bandwidth, energy. Meanwhile they can vote for activated witness to share the block reward. However, none privatekey accounts, like smart contracts, can't benefit from the staking mechanism. 

By providing related instructions, smart contracts will take fully advantage of their balance. For example, getting delegated resouce such as bandwidth or energy, voting witness, keeping the network safe, sharing the block reward. On the other hand, developer could write some special contracts such as energy bank contracts, voting contracts which are different from system voting contracts.

## Timeline

Any opinions or discussions about this proposal are welcomed in the next two weeks.

The estimated timeline

- Creation time of the voting request: 12th October 2021
- The effective time of voting request: 14:00, 15th October 2021

## How to Initialize the Voting Request

This is the command of initiating the voting request

- CreateProposal 52 1 59 1

#### `0xd5`: `FREEZE`

The `FREEZE` takes 3 operands pop up from stack:

`receiverAddress`: account address to receive generated resource.

`freezeAmount`: amount to freeze in SUN.

`resourceType`: 0 as bandwidth, 1 as energy.

Execute freeze funtion. If operation succeed, push 1 to stack, otherwise push 0 to stack.

#### `0xd6`: `UNFREEZE`

The `UNFREEZE` takes 2 operands pop up from stack.

`receiverAddress`: account address which received resource.

`resourceType`: 0 as bandwidth, 1 as energy.

Execute unfreeze funtion. If operation succeed, push 1 to stack, otherwise push 0 to stack.

#### `0xd7`: `FREEZEEXPIRETIME`

The `FREEZEEXPIRETIME` takes 2 operands pop up from stack.

`targetAddress`: target account address.

`resourceType`: 0 as bandwidth, 1 as energy.

Query expire time for special frozen balance. If operation succeed, push the expire time to stack, otherwise push 0 to stack.

#### `0xd8`: `VOTEWITNESS`

The `VOTE` takes 4 operands pop up from stack:

`tronPowerArrayLength`: witness address array offset.

`tronPowerArrayOffset`: witness address array size.

`witnessAddressArrayLength`: tron power number array offset.

`witnessAddressArrayOffset`: tron power number array size.

TVM will get witness array from memory by using `witnessOffset` and `witnessSize`.

TVM will get tron power array from memory by using `tronPowerOffset` and `tronPowerSize`.

Execute vote function. If operation succeed, push 1 to stack, otherwise push 0 to stack.

#### `0xd9`: `WITHDRAWREWARD`

The `WITHDRAWREWARD` takes no operand pop up from stack.

Execute withdraw function. Push actually withdrawed reward amount to stack.

#### `0x1000005`: `RewardBalance`

The `RewardBalance` takes no operand pop up from stack.

Execute query reward function and push reward amount which can be withdrawed to stack.

#### `0x1000006`: `IsSrCandidate`

The `IsSrCandidate` takes 1 operand pop up from stack:

`targetAddress`: target account address.

Push 0 if target address is not a witness, otherwise push 1.

#### `0x1000007`: `VoteCount`

The `VoteCount` takes 2 operand pop up from stack:

`voteAddress`: vote account address.

`targetAddress`: target account address.

Execute query vote count function and push vote count to stack.

#### `0x1000008`: `UsedVoteCount`

The `UsedVoteCount` takes 1 operand pop up from stack:

`voteAddress`: vote account address.

Execute query total used vote count function.

#### `0x1000009`: `ReceivedVoteCount`

The `ReceviedVoteCount` takes 1 operand pop up from stack:

`receivedAddress`: witness address.

Excute query witness total received vote count.

#### `0x100000a`: `TotalVoteCount`

The `TotalVoteCount` takes 1 operand pop up from stack:

`voteAddress`: vote account address.

Execute query total vote count function.

See more details about these instructions and precompile contracts, solidity examples at [TIP-157](https://github.com/tronprotocol/tips/blob/master/tip-157.md) and [TIP-271](https://github.com/tronprotocol/tips/blob/master/tip-271.md).

## Example on Nile test net

A contract named `FreezeAndVote` was deploied on nile test net. This contract contains serval external functions and view functions. Defination of some key functions are as follows.

- `freezeBalance(address payable receiver, uint amount, uint res)`: Freeze `amount` balance of contract to get resource for `receiver` which type is `res` (0 for bandwidth, 1 for energy).
- `unfreezeBalance(address payable receiver, uint res)`: Unfreeze specific balance to get corresponding balance. You can use `receiver` and `res`  (0 for bandwidth, 1 for energy) parameters to unfreeze specific balance.
- `voteWitness(address[] calldata srList, uint[] calldata tpList)`: Vote witness in `srList` array and every witness will get correspond tron power in `tpList` array.
- `withdrawReward()`: Withdraw all allowance and reward to contract balance.

Check contract details at [FreezeAndVote](https://nile.tronscan.org/?_ga=2.12700658.432936401.1630552781-773348445.1604564136#/contract/TStEnCxN8cjqSC8EohWGcxqkQzRpHUsrQT/code)

![image](https://user-images.githubusercontent.com/6821662/131986261-fc487120-800c-4014-a5b0-0c1b2e46f52d.png)

Then triggered twice `freeze` operations to obtain the resources including tron power, and voted the sr called `sr-27`. The transaction list is as follows.

![image](https://user-images.githubusercontent.com/6821662/131986307-92f84c33-def6-4eb2-85c9-272a62a777c8.png)

After two maintenance periods, there are some block rewards which can be withdrawn.  We can query the reward amount through `queryRewardBalance`.

![image](https://user-images.githubusercontent.com/6821662/131986350-06652cf7-89e3-4ada-aafd-ae05bce1d0eb.png)

The rewards can be withdrawn through writing contracts. After this operation, rewards have been withdrawn to contract balance.

![image](https://user-images.githubusercontent.com/6821662/131986380-b8f9a959-ab81-40b0-98b1-8ecec389dbde.png)

### Welcome to discuss.

**Comment by joker-gdb** [comment]
It seems that only new contracts can use this feature. Old contracts with a lot of trx seem to be unable to enjoy this feature, but this is indeed a big improvement.

**Comment by a49688448** [comment]
This proposal improves the smart contract and enables the project developer to actively participate in the governance of the TRON. The TRON network will be more stable and more TRX will vote. Good to TRON community.

**Comment by hitlxy** [comment]
This proposal will enable contract to take full advantage of its balance, there are many projects need to delegate energy to others, as the demo contract, the energy bank will be more convenience for them. on the other hand, for the contract not used as energy bank, owner also can write reserved freeze/unfreeze/vote/withdraw function to benefit from balance later, great.

**Comment by Cletitia** [comment]
It's a good idea to have this proposal that contract devs can make full use of the balances in smart contracts. Seems like this year we've got some other proposals, such as raising the energy fee, that are encourage holding and staking TRX, and I think this proposal can bring benefits to TRX holders.

**Comment by call-me-nobody** [comment]
From the perspective of functions themselves and contract application scenarios, this is indeed a good suggestion.

But from another perspective, if the TRX Staked in the contract also participates in the sharing of resources, it will inevitably affect the interests of existing users. Now the total energy of the entire network is fixed, and the more users participate, It will inevitably cause existing users to use the same TRX to obtain less energy. If there are any charts shows the status of TRX holding of top contracts from the entire network(such as the TOP10 contracts), it will help us to understand what is the impact if these users start to share the resources.

Thanks a lot

**Comment by woaichixigua07** [comment]
This proposal is very useful and necessary for contract developers, and with the examples shown above, I think most developers would like to see this proposal passed as soon as possible.

**Comment by yanghang8612** [comment]
@joker-gdb yes, it is. But i think some old contracts can still benefit from this through `delegatecall`.
If interested, take a try on nile test net. Thanks~

**Comment by yanghang8612** [comment]
@a49688448 That is also our purpose to add those new instructions.
Glad to agree with you.

**Comment by yanghang8612** [comment]
@hitlxy @Cletitia Yes. Not only smart contracts will benefit from its balance, but also the whole net work will become more stable and safer because of more staking TRX.

**Comment by yanghang8612** [comment]
@call-me-nobody Your opinion is very valuable.
We will make a statistics and send it to this issue as soon as possible in the near future
Thank you very much.

**Comment by yanghang8612** [comment]
@woaichixigua07 Thank you for your approval.  ^ _ ^

**Comment by tronfamily** [comment]
What happens to the active votes when a partial unfreeze occurs? Will the votes be completely removed as before or will the feature of separating bandwidth/energy and TronPower take place immediately with this proposal?

**Comment by yanghang8612** [comment]
@tronfamily Good question! Unlike system contracts, votes will not be removed if tron power of contract is still enough for its votes after unfreeze operation. Please see comments for `unfreezeBalance()` function in [TIP-271 Solidity Example](https://github.com/tronprotocol/tips/blob/master/tip-271.md#solidity-example).

Considering that freeze and unfreeze operations are very frequent for some contracts like energy bank, clearing all votes after every unfreeze operation are not friendly to developers. So we design the new logic for unfreeze operation of contract.

**Comment by otakuinny** [comment]
Bad idea! There are a lot of bad players that run scam dapps with a lot of trx in it. Giving them the ability to vote and receive rewards will further enrich them before they exit scam.

This will increase energy costs for everybody and also will decrease the staking rewards for the regular tron users which makes tron less attractive. 

And please stop saying "this proposal will make TRON. Network more stable" in every proposal🤦‍♂. These proposals have nothing to do with TRON network stability!!!

**Comment by yanghang8612** [comment]
@otakuinny Thank for your opinion!
Bad players can easily transfer balance of the scam dapps to EOA account, do voting operation through system contract and share block rewards.
More staking trx will always decrease the gaining energy from freezing balance. But we can not prevent users doing this. As for the impact from contract freezing operations, we are now working on it and doing some analysis.
In general, the top contract holders of TRX are `WTRX`, `jTRX Token`, `Trading pair on JustSwap` and so on. Those contracts `MUST` not use their balances to vote witness or receive reward.
We think right and sanity using of smart contract freezing and voting operations can truly bring stability to the whole net work.

**Comment by otakuinny** [comment]
> @otakuinny Thank for your opinion!
> Bad players can easily transfer balance of the scam dapps to EOA account, do voting operation through system contract and share block rewards.
> More staking trx will always decrease the gaining energy from freezing balance. But we can not prevent users doing this. As for the impact from contract freezing operations, we are now working on it and doing some analysis.
> In general, the top contract holders of TRX are `WTRX`, `jTRX Token`, `Trading pair on JustSwap` and so on. Those contracts `MUST` not use their balances to vote witness or receive reward.
> We think right and sanity using of smart contract freezing and voting operations can truly bring stability to the whole net work.

@yanghang8612, bad players can't easily transfer trx to an EOA account because they need to keep that trx on the contract to convince their users that their scam dapp is running fine. So, your argument that scam dapps can already do this is not valid. This proposal will just make it super easy for all the scam dapps out there to vote and dilute the rewards for the whole TRON community.

And what stops the contracts you mentioned from voting and diluting the voter rewards for everybody even further? More to the point, who does this proposal help at all?? TRX are sent to the contracts for different use cases, locking them up and making them unusable is not one of those use cases. 

You are proposing a proposal that benefits nobody at all but hurts all tron holders who receive voting rewards. There is absolute no reason whatsoever for this proposal. I hope the SRs will keep that in mind when they vote.

**Comment by infoglitz** [comment]
I think this proposal is for stake and utilise the energy or bandwidth by using tron available in the smart contract account. But Voting will affect the people staked for block rewards. Most of the smart contract owners getting the reward as fee for using the smart contracts. This proposal will enable another reward for smart contract owners, will be a burden for normal staking people. The tron power mechanism must be changed. The mechanism must be either energy or bandwidth else vote and block reward. First implement this then approve this proposal. This proposal good only for large players, small players always crucifying while implementing new proposals in TRON.

**Comment by yanghang8612** [comment]
@infoglitz Your consideration is valuable.
We will discuss in the community as soom as possible.

**Comment by yanghang8612** [comment]
@otakuinny I can`t agree more with your worries about the abuse of those new instructions.

But as i mentioned in before issues, contracts which are aleady deployed on main net can`t easily use those new instructions unless they are upgradeable or they have some message call`s delegate mechanism.

If some dapps truly need to use their contract`s balance to vote and get reward, we think the dapp party must point this feature out in their white paper.

Thanks again for your reply.  ^ _ ^

**Comment by otakuinny** [comment]
> @otakuinny I can`t agree more with your worries about the abuse of those new instructions.
> 
> But as i mentioned in before issues, contracts which are aleady deployed on main net can`t easily use those new instructions unless they are upgradeable or they have some message call`s delegate mechanism.
> 
> If some dapps truly need to use their contract`s balance to vote and get reward, we think the dapp party must point this feature out in their white paper.
> 
> Thanks again for your reply. ^ _ ^

@yanghang8612, my concern wasn't just about existing scam contracts. Scam ROI dapps are created every week. They'll definitely make use of this feature to vote/get rewards which will mean less rewards for everyone else. I don't mind legitimate dapps participating in voting but most contracts that hold large balances are scam dapps. They should not have means to profit more.

I don't understand what you mean by dapp must point out the need for voting in their white paper. How would you enforce this? Some scam dapps don't even have a whitepaper. Even if they have one, they don't have to mention it in their whitepaper. They'll just do it. They are scam dapps after all! They don't follow your rules. I just don't understand who this proposal benefits.

**Comment by yanghang8612** [comment]
@otakuinny Thank you for your clarification! We will discuss your opinions about the abuse of those new instructions in some badly scam dapps as soon as possible.

**Comment by yanghang8612** [comment]
Thanks to everyone's contribution to this proposal.

This issue will be closed because another, more friendly and flexible, staking mechanism is now online and voted into effect.
Check the issue at: https://github.com/tronprotocol/tips/issues/467
Check the TIP at: https://github.com/tronprotocol/tips/blob/master/tip-467.md
Check the proposal at: https://github.com/tronprotocol/tips/issues/519
Check the voting detail at: https://tronscan.org/#/proposal/84
