### ISSUE TITLE
Proposal: The unit price of energy proposed to be increased to 280 sun

### ISSUE THREAD

**Issue by waynercheung** [tronprotocol/tips#338]
# Proposal: The unit price of energy proposed to be increased to 280 sun

## Simple Summary
Adjust the unit price of energy to 280 sun, after this proposal going to effect, the fee of 1 energy will be 280 sun.

## Motivation
Increasing the energy unit price would further decrease the daily Net new TRX from positive to negative, which will decrease the inflation rate, promote the staking rate and make the overall TRX circulation deflationary.

## Timeline
The estimated timeline
- Creation time of the voting request: 25th October 2021
- The effective time of voting request: 28th October 2021

I wish the SR BlockchainOrg can help us to submit the voting request, thanks . https://tronscan.org/#/address/TVFKwzE8qeETLaZEHMx2tjEsdnujAgAWaA

## How to Initialize the Voting Request
Change the unit price of energy to 280 sun
- createProposal 11 280 47 10000000000

## Background
The unit price of energy and bandwidth has been increased twice, firstly increased from 10 sun to 40 sun on 25th Nov. 2020, secondly increased from 40 sun to 140 sun on 11th Feb. 2021, and in the months that followed, the daily Net new TRX has been greatly reduced due to more TRX burned. For details, see https://tronscan.org/#/data/charts/supply
https://tronscan.org/#/data/charts/supplyAndDestroy
![image](https://user-images.githubusercontent.com/92922492/138379159-644ffc1d-55f4-4246-8798-6715afad0eea.png)

![image](https://user-images.githubusercontent.com/92922492/138379050-da663cb4-1dce-4807-b387-c43853ae7761.png)

On the other hand, due to the increased fees, users will get bandwidth or energy by staking TRX to reduce the consumption of TRX. With the increase in fees, the TRX staking ratio also shows a growing trend. From 22% in early November 2020 to 32% in October 2021, the network-wide stacking rate has increased by about 10%. For detail, see https://tronscan.org/#/data/charts/OverallFreezingRate.
![image](https://user-images.githubusercontent.com/92922492/138375356-946b4c73-7f67-4885-8aae-5f0773b5bc55.png)

The following two graphs show that the number of energy obtained by burning TRX starts to decrease, while the number of energy obtained by staking TRX is increasing ​​shortly after the fee increase, such as after April 2021. Check detail at https://tronscan.org/#/data/stats/EnergyConsume.
![image](https://user-images.githubusercontent.com/92922492/138375723-b593ac57-4bbd-4008-8908-874762451765.png)

![image](https://user-images.githubusercontent.com/92922492/138379326-52aeeda6-84bd-4747-94c4-900c1696c5cf.png)

In addition, there was no significant change in the daily smart contract transaction volume after the two proposals to increase the unit price of energy on November 25, 2020, and February 11, 2021. Even after January 20, 2021, there was a significant increase in daily transaction volume. The data shows that the increase in energy fees did not lead to a decrease in smart contract transaction volume. Check detail at: https://tronscan.org/#/data/stats/txOverviewStatsType 
![image](https://user-images.githubusercontent.com/92922492/138376110-e5e3bcc6-164b-43e6-92f0-744a606822c2.png)

## The Data Analysis
From the previous analysis, it can be seen that increasing the unit price of energy can increase the amount of TRX burned, while at the same time, users will stake more TRX to avoid TRX burning.

Due to the increase of the unit price of energy, a responsive adjustment of the upper limit of single smart contract fees (current value of 5000 TRX) is required. According to statistics, the highest energy cost of transactions since July is	
20,002,026, that is 5600 TRX (20002026 * 280 / 1000000), so the value of the upper limit of single smart contract fees needs to be adjusted to 10000 TRX, 10000000000 sun.

### Net new TRX

The average Energy and bandwidth consumption data from July 19, 2021, to July 23, 2021, were used as the base data for the analysis. 2,430,116 TRX were burned to obtain energy and 75,222 TRX were burned to obtain bandwidth. 

On 26th July, the unit price of bandwidth was changed to 1000 sun, from August 03 to August 08, An average of 3,387,927 TRX were burned to obtain energy and 315,705 TRX were burned to obtain bandwidth. 

|                                                              | 2021.07.17~2021.07.23                           | 2021.08.03~2021.08.09                            | Future                                             |
| ------------------------------------------------------------ | ----------------------------------------------- | ------------------------------------------------ | -------------------------------------------------- |
| The price of bandwidth                                       | 140 sun                                         | 1000 sun                                         | 1000 sun                                           |
| The price of energy                                          | 140 sun                                         | 140 sun                                          | 280 sun                                            |
| TRX Burned for bandwidth                                     | 75,222 trx                                      | 315,705 trx                                      | 315,705 trx                                        |
| Everage TRX Burned for energy                                        | 2,430,116 trx                                   | 3,387,927 trx                                    |  6,775,854 trx                                      |
| TRX produced(Block rewards + Voting Rewards)                 | 460,224 + 4,602,240 = 5,062,464 trx             | 5,062,464 trx                                    | 5,062,464 trx                                      |
| Net new TRX = TRX produced -  TRX burned for bandwidth - TRX burned for energy | 5,062,464 - 75,222 - 2,430,116 =  2,557,126 trx| 5,062,464 - 315,705 - 3,387,927 = 1,358,832 trx | 5,062,464 - 315,705 - 6,775,854  = -2,029,095 trx |
| Net new TRX Rate = Net new TRX / TRX produced                |  2,557,126 / 5,062,464 = 50.51 %                 | 1,358,832 / 5,062,464 = 26.84 %                 | -2,093,740 / 5,062,464 = - 40.08%                   |

From the future column,  4,746,759 TRX need to be burned for obtaining energy(5,062,464 - 315,705 = 4,746,759) to make the daily Net new TRX be 0, which means the price of energy needs to be raised to 1.9 times the original. Therefore, we propose to make it 2 times, that is 280 sun.

### Staking Rate

|                        | 2020.11.16~2020.11.23 | 2020.12.14~2020.12.21 | 2021.07.17~2021.07.23 | Future         |
| :--------------------- | --------------------- | --------------------- | --------------------- | -------------- |
| The price of bandwidth | 10 sun                | 40 sun                | 140 sun               | 1000 sun       |
| The price of energy    | 10 sun                | 40 sun                | 140 sun               | 280 sun        |
| Staking rate           | 25.05%                | 28.66%                | 32.79%                | 36.79%         |
| Staking amount         | 25,389,200,153        | 29,079,397,968        | 33,399,504,580        | 37,473,857,075 |

Currently, there is no evidence that shows the specific relationship between the change in resource costs and the staking rate, so the estimated staking amount is based on assumption, here we assume the relationship between resource cost and staking amount is a linear relationship, so here is the calculation:
From 10 sun to 40 sun there is a 4-fold increase in unit price and there is about 4%(28.66% - 25.05% = 3.61%) of the staking rate, from 40 sun to 140 sun there is 3.5 times increase in unit price and there is about 4.13% increase in staking rate, so when the price of bandwidth is 1000sun and the price of energy is 280, there is at least 2 times increase in unit price, so we assume that there is 4% increase in staking rate, that is 32.79 % + 4% = 36.79%.

**Comment by Benson0224** [comment]
> I feel the voting and SR rewards should be reduced now !
> 
> By continuously increasing the resource cost only the poor suffer ! While the 5m TRX generated daily keeps dumping IN the market

Thanks for your suggestion.

**Comment by Benson0224** [comment]
> your charts do not show how all users spend more money to do same actions. Could you also add a chart showing the rewards of the SR? How they increase with these changes? By showing only the data that you like, you don't convince anyone. Who exactly is the community that proposes these changes?

Thanks for your reply, the burned TRX does not go to any SR, I would say this proposal will not impact the SR reward at all. 
SR reward is based on how many votes they get. check detail at https://developers.tron.network/docs/mechanism
