### ISSUE TITLE
`chainid` opcode doesn't work

### ISSUE THREAD

**Issue by yidongw** [tronprotocol/tips#340]
I'm trying to deploy this following code
```
        uint256 chainID;
        assembly {
            chainID := chainid()
        }
```
but it would give me `"contractRet": "ILLEGAL_OPERATION"`
Can you please let me know what is the alternative?

**Comment by yanghang8612** [comment]
Hey, what kind of network did you perform the failed deploying operation on?

**Comment by yidongw** [comment]
> Hey, what kind of network did you perform the failed deploying operation on?

[trontools/quickstart](https://developers.tron.network/v4.0/docs/quickstart), but I haven't tried it on testnet or mainnet yet. Are they behaving differently?

**Comment by yanghang8612** [comment]
It looks like you are deploying smmart contract on a private network.
The `chianid` opcode is enabled when the value of `getAllowTvmIstanbul` chain parameter is `1`.
So please check your chain parameters through rpc interface `GetChainParameters`.
If the value of `getAllowTvmIstanbul` is not present, it means zero. You can adjust it by the follow two options.

Option A: insert a key-value into `committee` section of `config.conf` file
```
committee {
    ...
    allowTvmIstanbul = 1
    ...
}
```
Then delete your db directory and restart node. But this means that all old chain data will be lost.

Option B: make a proposal to change it. 

If there is no important data on your private network,  i suggest using the Option A.
As if Option B, please check the details at [Committee and Proposal](https://developers.tron.network/docs/committee-and-proposal#proposal)

**Comment by yidongw** [comment]
@yanghang8612 for [quickstart](https://developers.tron.network/v4.0/docs/quickstart), how do I insert the value into `config.conf` file?
I couldn't find the chainId of Mainnet, Shasta Testnet and Nile Testnet anywhere.
Can you please let me know what they are or how to find them?
Thanks

**Comment by yanghang8612** [comment]
`Pre-approved proposals`, in this section, there is an example starting shell. You can add pre-approved setting like below.
```
docker run -it \
  -p 9090:9090 \
  --rm \
  --name tron \
  -e "preapprove=allowTvmIstanbul:1" \
  trontools/quickstart
```

**Comment by yidongw** [comment]
It doesn't seem to be working. After I started the quickstart with the command that you provided, the transaction would still fall.

What is the chainId of TRON Mainnet, Shasta Testnet and Nile Testnet?

**Comment by vivian-kang** [comment]
Hi @yidongw,  The [document](https://developers.tron.network/v4.0/docs/quickstart) you refer to is not the latest, and the project in the page is no longer maintained, the java-tron version it used is 3.6.6 (a very old one). 
In addition, CHAINID is supported from v4.1.1. 
So please refer to the[ latest document](https://developers.tron.network/) and use the latest version of [java-tron](https://github.com/tronprotocol/java-tron). 
Thanks.
