### ISSUE TITLE
Discussion: an alternative to indicate fee limit for smart contract transactions

### ISSUE THREAD

**Issue by yanghang8612** [tronprotocol/tips#341]
Define `sc` of smart contract, `tx` of transaction.

According to Tron Protocol, we can indicate a upper limit for trx cost of sc txs and this field is defined in `raw_data` of tx header like below.

```protobuf
message raw {
    ...
    int64 timestamp = 14;
    int64 fee_limit = 18;
 }
```

Before sending sc txs, the field `fee_limit` can be set by formula like `estimated_energy * energy_fee`. The `estimated_energy` variable can be obtained through rpc interface `TriggerConstantContract` and the `energy_fee` is a Tron network parameter which can be adjusted by Tron Committee.

But the mutative `energy_fee` brings a breaking risk for some wallets or dapps which sending sc txs with a constant `fee_limit`. In opposite, the `energy_cost` of sc txs with same parameters are relatively stable. If we can set `energy_limit` for sc txs instead of `fee_limit`, the breaking risk can be reduced.

- Option A: add  `energy_limit` field to `CreateSmartContract` and `TriggerSmartContract` defination

  ```protobuf
  message CreateSmartContract {
    ...
    int64 energy_limit = 5;
  }
  
  message TriggerSmartContract {
    ...
    int64 energy_limit = 7;
  }
  ```

- Option B: add a new contract named `InvokeSmartContract`

  ```protobuf
  message InvokeSmartContract {
    bytes owner_address = 1;
    bytes to_address = 2;
    int64 energy_limit = 3;
    int64 call_value = 4;
    bytes call_data = 5;
    int64 call_token_value = 6;
    int64 call_token_id = 7;
    int64 consume_user_resource_percent = 8;
    int64 origin_energy_limit = 9;
  }
  ```

  When `to_address` is empty, like `CreateSmartContract`, txs containing this kind of contract will create a new sc which runtime code is a clone of the returned byte array by running `call_data` in TVM.

  Otherwise, like `TriggerSmartContract`, a message call to `to_address` will be made.

  By this option, the whole chain can no longer save `abi` and `bytecode(actually creation code)` of sc. Developers can no longer have to design two different functions in order to create or call sc.

Welcome discussion.

--- Updated at 11.15:

Either option A or option B requires a hard fork.

--- Updated at 11.17:

After discussion, we decide to move `energy_limit` into `raw` defination.

- Option A: add  `energy_limit` field to `raw` in `message Transaction { ... }`

  ```protobuf
  message Transaction {
    ...
    message raw {
        ...
        int64 fee_limit = 18;
        int64 energy_limit = 19;
    }
  }
  ```

**Comment by call-me-nobody** [comment]
I would say this feature is really great, with this we can directly use estimated_energy. 

One more question, what is the logic if both `energy_limit` and `fee_limit` were present in a transaction, who gets the higher priority? thanks.

**Comment by yanghang8612** [comment]
@call-me-nobody `fee_limit` has higher priority than `energy_limit`.
If you want to make `energy_limit` effective, `fee_limit`   must not be set.

**Comment by LegendaryLionS** [comment]
I would personally say, do not implement the second option. I feel the use-case of it is comparatively low as compared to the breaking changes it will cause, like `abi` not being stored on blockchain and even the `bytecode`.  Since the use-case is creating a contract when a sc address doesn't exist in `to_address`, I don't think many people will use it. 

If the blockchain won't save the bytecode or abi, how will it execute the sc code then?

**Comment by joker-gdb** [comment]
New developers are very confused about `feelimit`, `feelimit` seems to be the limit of all fees of  transaction, but it only includes the limit of  energy fee, it`s  too difficult to understand.

Change to energy_limit to make it easier to understand~

**Comment by yanghang8612** [comment]
@call-me-nobody Thanks for your reply.
After discussion, we decide to add a new rule for tx validation to solve the priority problem.
At least one of `fee_limit` and `energy_limit` must be set to `0`, otherwise throw `ContractValidateException`.

**Comment by tofudefi** [comment]
Option A looks better. No need to add new message type for such small change.

**Comment by vae520283995** [comment]
Is it compatible with the old feelimit format transaction?
I am a wallet developer and I don't want to modify my code, so will there be any impact?

**Comment by Benson0224** [comment]
> Is it compatible with the old feelimit format transaction? I am a wallet developer and I don't want to modify my code, so will there be any impact?

it is just another option to set fee limit.  
it will not impact the current solution, even after it is enabled, the current option still work

**Comment by vae520283995** [comment]
> > Is it compatible with the old feelimit format transaction? I am a wallet developer and I don't want to modify my code, so will there be any impact?
> 
> it is just another option to set fee limit. it will not impact the current solution, even after it is enabled, the current option still work

okay

**Comment by yanghang8612** [comment]
Close this issue as there has been no new discussion for more than 6 months.
