### ISSUE TITLE
Discussion: cache protobuf definition and runtime code for hot smart contract with LRU

### ISSUE THREAD

**Issue by yanghang8612** [tronprotocol/tips#379]
## Motivation

Once smart contract is deployed, its definition and code cannot be changed.

So we can cache some smart contracts that are frequently called for transaction execution. This will reduce the overhead of contract transaction execution.

## Specifications

After a full node is started, data of hot contracts will be cached by maintaining an LRU. The logic when executing contract transactions is adjusted as follows.

```
def validate(tx Transaction) {
    lru = db_manager.getLRU()
    if lru.contains(tx.to) {
        contract = lru.get(tx.to)
    } else {
        contract = db_manager.getContract(tx.to)
    }

    ...
}

def execute(tx Transaction) {
    ...
}
```

## Implementation

TODO.

## Backwards Compatibility

None.

## Security Considerations

None.

**Comment by Lredhdx** [comment]
It's a good idea to improve tvm performance. By caching hot contract, contract execution will reduce storage I/O times. How many hot contracts will be cached and why?
