### ISSUE TITLE
Proposal:  Enable the TVM London instruction

### ISSUE THREAD

**Issue by Omo-Coc** [tronprotocol/tips#380]
# Introduction
Enable `#63(ALLOW_TVM_LONDON)` proposal, so that TVM can be better compatible with EVM.

# Motivation
The Ethernet London Upgrade has already been activated on its mainnet on August 5, 2021. As a EVM-compatible vm implementation for TRON network, TVM  introduced two changes involving virtual machines in [GreatVoyage-v4.4.0(Rousseau)](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.4.0) to support London upgrade, but these two changes have not been activated in TVM yet.

Take the following solidity code as an example:

    pragma solidity ^0.8.7;

    contract BaseFee {

        function getBaseFee() view external returns(uint) {
            return block.basefee;
        }
    }

The code can compile and run successfully on Ethereum, but failed on Tron. That is inconvenient migrating between the two networks.

Enable the `#63(ALLOW_TVM_LONDON)` proposal, and after TRON solidity team upgrade the solidity compiler to support Ethereum Solidity v0.8.7, that will bring users a more friendly development experience.

# Timeline
Any opinions or discussions about this proposal are welcomed in the next two weeks.

The estimated timeline

* Creation time of the voting request: 15th March 2022
* The effective time of voting request: 14:00, 18th March 2022

Hi @TronSpark @fbsobreira, would you please help to raise a proposal to activate `#63` parameter to support London upgrade, or notify other SRs you know to initiate the proposal. Thanks a lot.

# How to Initialize the Voting Request

This is the command of initiating the voting request

* CreateProposal 63 1

# Technical Specs

**New instruction**

**```0x48```**: **```BASEFEE```**

The ```BASEFEE``` takes no operand pop up from the stack and pushes the value of the fee for 1 energy to the stack.

**New Logic**

Reject new contract code starting with the 0xEF byte.

New contract creation (via deploy transaction, ```CREATE``` or ```CREATE2``` instructions) results in an exceptional abort if the code’s first byte is ```0xEF```.

Remarks:

The initcode is the code executed in the context of the deploy transaction, ```CREATE```, or ```CREATE2``` instructions. The initcode returns code (via the RETURN instruction), which is inserted into the code store.

The opcode ```0xEF``` is currently an undefined instruction, therefore: It pops no stack items and pushes no stack items, and it causes an exceptional abort when executed. This means initcode or already deployed code starting with this instruction will continue to abort execution.

The exceptional abort due to code starting with ```0xEF``` behaves exactly the same as any other exceptional abort that can occur during initcode execution, i.e. in case of abort all gas provided to a ```CREATE*``` or deploy transactions are consumed.

**Welcome to discuss.**

**Comment by okwapa540** [comment]
Hi brother, TRON does not have the concept of basefee, what will `block.basefee` return?

**Comment by hitlxy** [comment]
block.basefee returns the energy unit price

**Comment by Omo-Coc** [comment]
> Hi brother, TRON does not have the concept of basefee, what will `block.basefee` return?

Yeah, no `basefee` in TRON's resource model, this is only compatible at the virtual machine level, as I said in the proposal, `block.basefee`  will give you the energy unit price, and guarantee such code can run on TRON, this will bring great convenience to code compatibility.

**Comment by L-Reid** [comment]
The TRON network is always improving step by step.

**Comment by ethan1844** [comment]
Thanks to everyone's contribution to this proposal.
This issue will be closed as it is already going to effect, check detail at: https://tronscan.org/#/proposal/72
