### ISSUE TITLE
TRC: Reduce block confirm time with PBFT

### ISSUE THREAD

**Issue by jiangyy0824** [tronprotocol/tips#39]
```
tip: 39
title: TRC-39 Reduce block confirm time with PBFT
author: liangzhiyan@tron.network, jiangyy<jiangyangyang@tron.network> 
discussions to: https://github.com/tronprotocol/TIPs/issues/39
status: draft
type: Standards Track
category: TRC
created: 2019-5-17
```

# Simple Summary
This doc describes the PBFT solution to reduce block confirm time.

# Abstract
In current consensus model, block need to be confirmed by 2/3 SR nodes. In that case, there is a gap of 18 blocks between the main-network's chain height and consensus height, and it takes about 1 minutes for the solidification/confirmation. With PBFT, the confirmation time could be reduced to seconds level.

It could also help improving the TPS on main-net, and providing technical support for Cross-Chain.

# Motivation
Support more business scenarios and provide better user experience. 

# Specification
The reason of the block gap is TRON's consensus algorithm. For example, SR0 produces a new block BLK0, other SR nodes need to wait until their schedule to confirm BLK0. Other SR nodes verify BLK0 one after another according to the block produce schedule. After more than 2/3 of SR confirm the block, the block is Irreversible. The transaction confirm time is: 27 * 2/3 *3 = 54 seconds.

To reach a real-time consensus speed, the block currently being produced should be confirmed by other SR nodes immediately. PBFT needs to be integrated.

# Challenges
1. Network overhead, additional PBFT messages are needed.
2. Compatibility with current consensus model DPOS. 
3. Security issues.

# Optimization of PBFT
1.Combined with Dpos, the pbft algorithm is used to implement block consensus.
2.Remove view changes and data requests
3.Sr node's block productivity will not be influenced.
4.The fullnode node is free to choose the number of consensus(confirmed) SR nodes.

# Algorithm
1.Each SR node will only sign a block of a specific height once. 
2.A block will be treated as a timeout if it is not confirmed by more than 2/3 SR nodes. 
3.The fullNode node can fix the current block by setting a commit message that receives 27 SR signatures to achieve security and reliability, except two consecutive SR node is cheating together.
# Proto
message PbftMessage {
  enum Type {
    VIEW_CHANGE = 0;
    REQUEST = 1;
    PREPREPARE = 2;
    PREPARE = 3;
    COMMIT = 4;
  }
  message Raw {
    Type pbftMsgType = 1;
    int64 blockNum = 2;
    int64 time = 3;
    bytes publicKey = 4;
    bytes data = 5;
  }
  Raw raw_data = 1;
  bytes sign = 2;
}

**Comment by jiangyy0824** [comment]
TIP：

```
tip: 39
title: TRC-39 Acceleration of transaction confirm time with PBFT
author: liangzhiyan@tron.network, jiangyy<jiangyangyang@tron.network> 
discussions to: https://github.com/tronprotocol/TIPs/issues/39
status: draft
type: Standards Track
category: TRC
created: 2019-5-17
```

# Simple Summary
This doc describes PBFT solution to accelerate transaction confirm time.

# Abstract

# Motivation

# Specification

**Comment by lvs007** [comment]
Sr does not need to confirm the curing block through pbft. The fullNode node can achieve a safe and reliable non-retractable block consensus by setting the consensus sr signature number and the interval of several consensus blocks.

**Comment by lvs007** [comment]
I think of it then we can use pbft to implement the signature of the sr change, so that we can know the sr list of changes without syncing the block, in order to achieve cross-chain
