### ISSUE TITLE
One of the multiple signature addresses cannot be signed.

### ISSUE THREAD

**Issue by hoitmiki** [tronprotocol/tips#399]
One of the Tron Link addresses is not approved, so I can't withdraw money.

Is there a way to change the address?

I'll pay the commission.

**Comment by ethan1844** [comment]
Please go to https://github.com/tronprotocol/java-tron to submit the issue and describe the issue in detail, thanks.

**Comment by hoitmiki** [comment]
The address is not correct

Could you send it again?

2022년 4월 15일 (금) 오후 2:33, ethan1844 ***@***.***>님이 작성:
