### ISSUE TITLE
Why does tronLink interact differently than metamask?

### ISSUE THREAD

**Issue by AaronLuoTron** [tronprotocol/tips#460]
According to my comparison, Metamask supports dapp requests to switch networks, but tronLink does not
When Metamask is locked, it can directly evoke a pop-up window, but tronLink does not support it.
Are there any plans to support it in the future?
<img width="360" alt="image" src="https://user-images.githubusercontent.com/112167408/186881237-db8f38ce-61cc-4e27-8c08-5644dfe34bab.png">

**Comment by ethan1844** [comment]
This repo is for TRON Improvement Proposals, so I recommend closing this issue.
For TronLink issues you can creat a issue here:https://github.com/TronLink
