### ISSUE TITLE
TIP-1102: Opt-in account exposure

### ISSUE THREAD

**Issue by AaronLuoTron** [tronprotocol/tips#463]
```
tip: 1102
title: Opt-in account exposure
author: Aaron <aaronluotron@gmail.com>
discussions to: 
category: Interface
status: Last Call
created: 2022-09-05
```
## Table of Contents
- [Table of Contents](#table-of-contents)
- [Simple Summary](#simple-summary)
- [Motivation](#motivation)
- [Specification](#specification)
    - [Examples](#examples)
    - [Returns](#returns)
    - [Error Code](#error-code)
    - [Constraints](#constraints)
- [Backwards Compatibility](#backwards-compatibility)

## Simple Summary
This protocol is used to describe the communication between a DApp and a wallet. It allows the wallet to determine what information and when to provide it to the DApp.

## Motivation
Currently, there is no such protocol on TRON. This leads to inconsistent implementation of DApps connected to TRON, which objectively increases the development workload of DApp developers.
The goal of this proposal is to standardize the method for DApps to obtain user information from the wallet.
Description of the proposal: Wallet will not disclose any account information until the user agrees, so as to ensure the security of the user's information.
Ethereum's [EIP-1102](https://eips.ethereum.org/EIPS/eip-1102) is a similar protocol that can be followed.

## Specification
`eth_requestAccounts`
#### Examples
```javascript
try {
  await tron.request({method: 'eth_requestAccounts'});
} catch (e) {}
```
#### Returns
If successful, an array will be returned, the array has one element, which is the address of the current account, like：
`['TQKLs3GzCNLjzyCvaPWSrqcpUGUhadxm7P']`.

If it fails, an error code and an error message will be returned. See the [Error Code](error-code) section for details.
#### Error Code
|  Code   | Message  | Description |
|  ----  | ----  | ---- |
| -32002  | Other requests are being processed | current DApp is processed, it cannot execute the current request |
| -32602  | Invalid params | invalid parameters, or added additional parameters |
| 4001  | User rejected request | the user has rejected this request |
| 4200  | Unsupported method | unsupported method |

#### Constraints
 - The wallet must define an `eth_requestAccounts` method.
 - If Promise is resolved, the wallet must return an array containing at least one account.
 - If no account is available, the wallet must reject the Promise and return an error message
 - If the user rejects, the wallet must reject the Promise and return an error message.
 - If the user can no longer accept the Promise, for example, the user interface is closed and the user interface cannot be invoked again, the wallet must reject the Promise and return an error message.

## Backwards Compatibility
This protocol has no impact on existing wallets and DApps, but it is recommended that all wallets and DApps implement this protocol.
It is also recommended to implement this protocol for DApps that have already implemented other similar functional protocols.

**Comment by chendatony31** [comment]
Why not use `tron_requestAccounts` instead?

**Comment by AaronLuoTron** [comment]
> Why not use tron_requestAccounts instead?

@chendatony31 
TRON DAO hopes that from the perspective of convenience for DApp developers, the same set of codes can run on Ethereum and TRON chain at the same time.
`eth_requestAccounts` is a method name, and TRON DAO hopes to make the method name as consistent as possible with Ethereum, so that DApp developers can develop easily.

**Comment by ramiltanker** [comment]
What should I do if I get an error: "[commonRequest]: The wallet is locked." ?

**Comment by Jones098** [comment]
> ```
> tip: 1102
> title: Opt-in account exposure
> author: Aaron <aaronluotron@gmail.com>
> discussions to: 
> category: Interface
> status: Last Call
> created: 2022-09-05
> ```
> ## Table of Contents
> - [Table of Contents](#table-of-contents)
> - [Simple Summary](#simple-summary)
> - [Motivation](#motivation)
> - [Specification](#specification)
>     - [Examples](#examples)
>     - [Returns](#returns)
>     - [Error Code](#error-code)
>     - [Constraints](#constraints)
> - [Backwards Compatibility](#backwards-compatibility)
> 
> 
> ## Simple Summary
> This protocol is used to describe the communication between a DApp and a wallet. It allows the wallet to determine what information and when to provide it to the DApp.
> 
> ## Motivation
> Currently, there is no such protocol on TRON. This leads to inconsistent implementation of DApps connected to TRON, which objectively increases the development workload of DApp developers.
> The goal of this proposal is to standardize the method for DApps to obtain user information from the wallet.
> Description of the proposal: Wallet will not disclose any account information until the user agrees, so as to ensure the security of the user's information.
> Ethereum's [EIP-1102](https://eips.ethereum.org/EIPS/eip-1102) is a similar protocol that can be followed.
> 
> ## Specification
> `eth_requestAccounts`
> #### Examples
> ```javascript
> try {
>   await tron.request({method: 'eth_requestAccounts'});
> } catch (e) {}
> ```
> #### Returns
> If successful, an array will be returned, the array has one element, which is the address of the current account, like：
> `['TQKLs3GzCNLjzyCvaPWSrqcpUGUhadxm7P']`.
> 
> If it fails, an error code and an error message will be returned. See the [Error Code](error-code) section for details.
> #### Error Code
> |  Code   | Message  | Description |
> |  ----  | ----  | ---- |
> | -32002  | Other requests are being processed | current DApp is processed, it cannot execute the current request |
> | -32602  | Invalid params | invalid parameters, or added additional parameters |
> | 4001  | User rejected request | the user has rejected this request |
> | 4200  | Unsupported method | unsupported method |
> 
> #### Constraints
>  - The wallet must define an `eth_requestAccounts` method.
>  - If Promise is resolved, the wallet must return an array containing at least one account.
>  - If no account is available, the wallet must reject the Promise and return an error message
>  - If the user rejects, the wallet must reject the Promise and return an error message.
>  - If the user can no longer accept the Promise, for example, the user interface is closed and the user interface cannot be invoked again, the wallet must reject the Promise and return an error message.
> 
> 
> ## Backwards Compatibility
> This protocol has no impact on existing wallets and DApps, but it is recommended that all wallets and DApps implement this protocol.
> It is also recommended to implement this protocol for DApps that have already implemented other similar functional protocols.
> 

Hello

**Comment by Godwinlawrence** [comment]
Binance connect

**Comment by MatthewShelby** [comment]
**Title**: Is ` eth_requestAccounts ` currently supported in TronLink?

**Body**:
I tested the following code:


`await window.tronLink.request({ method: 'eth_requestAccounts' });
`


However, it does not seem to work in TronLink. Previously, I was using:


`await window.tronLink.request({ method: 'tron_requestAccounts' });
`

which worked as expected.

Since TIP-1102 recommends eth_requestAccounts for consistency with Ethereum, I wanted to confirm:

- Is eth_requestAccounts currently supported in TronLink or other TRON wallets?
- If not, when can we expect support for it?
- Should developers continue using tron_requestAccounts for now?


Would appreciate any clarification. Thanks!
