### ISSUE TITLE
TRC-CRS03: Node interconnect communication

### ISSUE THREAD

**Issue by lvs007** [tronprotocol/tips#47]
# Simple Summary
This doc describes the a solution to node interconnect communication

# Abstract
It defines how nodes connect and communicate between each other. Cross-chain node communication needs to be relayed, relay is the main chain, and other chains connected to the main chain are called branches.

# Motivation
Support the IBC communication

# Specification
Configure the main chain and the branch chain seeds. When the node is connected to the handshake, we need to exchange the node information of each other. Link pool contains this chain connection and cross-chain connection.

Previously, if the version or genesisBlockId were inconsistent, the connection would be disconnected. Now, after adding the cross-chain mechanism, it will not be disconnected. Only the branch and the main chain are allowed to be interconnected, and the branches cannot be interconnected.

The main chain can also act as a branch chain character. When the node is started, it is determined whether to start main or branch by setting a parameter. If it is to start main, it needs to manage the connection and block header of different branches, which is responsible for the cross-chain forwarding function. If it is branch, it needs to register with main and download the main chain block header.

# Algorithm

# Proto
message HelloMessage {
  message BlockId {
    bytes hash = 1;
    int64 number = 2;
  }

  Endpoint from = 1;
  int32 version = 2;
  int64 timestamp = 3;
  BlockId genesisBlockId = 4;
  BlockId solidBlockId = 5;
  BlockId headBlockId = 6;
}

**Comment by shydesky** [comment]
The tip about cross-chain is moved to the folder "tp/ticp". So we close this issue.
