### ISSUE TITLE
TRC-CRS04: Block header download

### ISSUE THREAD

**Issue by lvs007** [tronprotocol/tips#48]
# Simple Summary
This doc describes a solution to block header downloading.

# Abstract
The main chain and the branch chain need to synchronize the block header of the other party. The block header synchronization is to provide security for the SPV.

# Motivation
Support SPV features in the future

# Specification
Block header synchronization: 
The main chain needs to synchronize their block headers from different branches. The branch chain needs to synchronize the block header of the main chain from the main chain.

The main chain node preferentially synchronizes from the corresponding branch chain sync block header. If there is no corresponding branch chain connection,the block header of the branch chain is synchronized from the other main chain nodes.

The branch chain node preferentially synchronizes the main chain block header from the main chain. If there is no main connection, the main chain block header is synchronized from the other nodes of the branch chain.

Block header broadcast: 
Main chain broadcasts its own block header to all branches (if main chain node does not have a corresponding connection to main chain node, it does not need to be processed).
Branch chain broadcasts its own block header to main chain (if there is no main chain connection, it does not need to be processed).
If the received block header occurs unlink, then trigger synchronization.

Block header storage: 
Main is based on version and genesisBlockId as a chain key, corresponding to <key, <blockId, head>>; branch only needs to store the main header so only one storage structure <blockId, head>.

# Algorithm

# Proto
message BlockHeader {
message raw {
int64 timestamp = 1;
bytes txTrieRoot = 2;
bytes parentHash = 3;
//bytes nonce = 5;
//bytes difficulty = 6;
int64 number = 7;
int64 witness_id = 8;
bytes witness_address = 9;
int32 version = 10;
bytes accountStateRoot = 11;
SrList srList = 12;
bytes genesisBlockId = 13;
}
raw raw_data = 1;
bytes witness_signature = 2;
}

message SrList {
message raw {
bytes currentSrList = 1;
bytes nextSrList = 2;
}
bytes sr_signature = 3;
}

**Comment by shydesky** [comment]
The tip about cross-chain is moved to the folder "tp/ticp". So we close this issue.
