### ISSUE TITLE
> Adding a 1trx fee for memo is not very fair to people who actually have a need to use memo. I think we should restrict the ability to attach memo to transactions with transfers of less than 1trx.

### ISSUE THREAD

**Issue by JJamesBROWN** [tronprotocol/tips#485]
> Adding a 1trx fee for memo is not very fair to people who actually have a need to use memo. I think we should restrict the ability to attach memo to transactions with transfers of less than 1trx.
> 
> Of course, the number of trx can be a parameter modified by the poll.
> 
> For many people, if it costs an additional fee to attach a memo to a transfer, they may forgo attaching a memo, this is not good for the tron community.

I think this is reasonable, memos for people sending TRX to pay bills or to friends etc should get free memos, but only if the TRX value is above 1 TRX.  Any memo attached to a lower value send, or to a different TRC10 send would then cost 1 TRX.  This would allow memo functionality for core TRX token and valid use case while limiting low value spam memo transactions.

_Originally posted by @dmf3030 in https://github.com/tronprotocol/tips/issues/387#issuecomment-1297114668_

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, for better community discussion, we kindly remind you to check out [TIP template](https://github.com/tronprotocol/TIPs/blob/master/template.md) for guidance.
