### ISSUE TITLE
Proposal: change the transaction memo fee to 1 TRX

### ISSUE THREAD

**Issue by Omo-Coc** [tronprotocol/tips#486]
# Simple Summary

In order to solve the problem caused by the dramatic increase in the number of low-value transactions on the TRON network, it is recommended to change the transaction memo fee to 1 TRX. For more details, please refer to: [TIP-387](https://github.com/tronprotocol/tips/blob/master/tip-387.md).

# Motivation
Transferring TRX/TRC10 token is equivalent to free because of the daily free bandwidth and the uncharged memo. So everyday there are tens of thousands of transactions using memo to broadcast fake news, scam links.

Below is a statistic of the number of transactions with memo in the network from July 1, 2022 to October 1, 2022:

| |Total Value | Smart Contract Call| TRX Transfer	| TRC10 Transfer |
| -------- | -------- | -------- | -------- | -------- |
|Transaction|	499,061,345|	131,973,648|	298,642,527|	63,428,239	|
|Transaction with memo|18,136,783|	197,087	|2,673,435|	15,265,761	|
|Transaction with URL in memo|	7,725,151	|4,127	|785,831|	6,935,193	|

In these three months, we saw 18,136,783 transactions with memos, of which 7,725,151 transactions were with URLs, which accounted for 42.59%. We can clearly see that these memos with url are almost all deceptive, they hope users will open the url and jump to the scam they designed.

7,725,151 transactions with memo with url, of which 6,935,193 are TRC10 transfers, accounting for 89.77%, indicating that scammers prefer to use low-cost TRC10 transactions to implement their scam plans.If each memo needs to pay 1 TRX, the cost of scamming in these 3 months will reach 7,725,151 TRX, which will be a huge challenge for scammers.

We can also see that in these 3 months, transactions with memo only accounted for 3.63% of the total network transaction volume, so the memo fee will have no negative impact on most users.

Charging 1 TRX for transaction memo will increase the cost of transactions with memo, restrain the growth rate of low-value transactions and improve the security and reliability of the TRON network.

# Timeline
Any opinions or discussions about this proposal are welcomed.

The estimated timeline

* Creation time of the voting request: December 13, 2022
* The effective time of voting request: December 16，2022

# How to initiate the voting request
This is the command of initiating the voting request to change the transaction memo fee to 1 TRX:
* createProposal 68 1000000

# Specifications
The `raw_data.data` field in the transaction is used as a memo. After setting the `#68(MEMO_FEE)` parameter to 1TRX takes effect, if `raw_data.data` is not empty, the transaction will burn an extra 1 TRX.

**Comment by mogtaba24177** [comment]
1

**Comment by jettang2019** [comment]
As you already know these transactions with URL, so make it 10 TRX.
Don't be like you want to stop these scammers, and also you want to earn these fees.
Protect users first.

**Comment by githubnonono** [comment]
I think this is a very good idea,  charging 1 TRX for transaction memo will increase the cost of memo cheating, and improve TRON network security.

**Comment by okwapa210** [comment]
Spam advertising transactions have always existed on the TRON network, almost half of memo transactions are spam transactions. The fee of 1TRX will increase their costs, I think this problem can be solved. Memo is a very low-frequency scenario, and 1TRX fee will not have a great impact on them.

**Comment by brooklynn1212** [comment]
> 

Do dapps use memos a lot？Most of them are ads for scammers.

**Comment by LauraYH** [comment]
> > 
> 
> Do dapps use memos a lot？Most of them are ads for scammers.

That is right! Once the cost is raised, the users in TRON have to take a more prudential consideration of utilizing this function. At present, I see many more malicious transactions with redirect URLs in memos than legitimate transactions with memos.

At least this proposal is going in the right direction. I hope the memo fee could be a TRON network parameter since it would affect the whole community.

**Comment by souppopnix** [comment]
Finally someone try to stop scammers and ads, hope the new tip can slow them even a little, definitely gonna support this proposal. So annoyed by those 0 USDT transactions with url, plus I've seen many link their wallet without thinking and signed unlimited withdrawal contract and say goodbye to their assets.

**Comment by m-o-m12** [comment]
Transactions with advertisements memo are really annoying. I receive lots of airdropped TRC10 tokens every day, these meaningless tokens makes my asset list very large. Expected to see the actual result by this proposal.

**Comment by otakuinny** [comment]
> Transactions with advertisements memo are really annoying. I receive lots of airdropped TRC10 tokens every day, these meaningless tokens makes my asset list very large. Expected to see the actual result by this proposal.

Then you should be asking for a feature on tronscan and tronlink app to hide or filter the tokens so you can only see the tokens you want instead of increasing the fees for memos which will hurt legitimate dapps that rely on memos in their transactions. 

This has always been an issue with these proposals. Everytime there's a problem to be solved, a proposal is offered that hurts the whole community just to fix a minor inconvenience. And, oftentimes, it doesn't even work. This is why the energy price has been increased like 5 times so far. Seriously, this makes tron look like a clown outfit.

**Comment by Omo-Coc** [comment]
In the chart below, we can see the comparison of on-chain data between the last week and the week before the proposal took effect,

| |Total Value | Smart Contract Call| TRX Transfer	| TRC10 Transfer |
| -------- | -------- | -------- | -------- | -------- |
|Transaction|	6,013,286 (-24.10%)|	2,218,125(-2.92%)|	4,534,237(-2.86%)|	271,964(-57.47%)	|
|Transaction with memo|176,344(-92.21%)|	11,333(-27.03%)	|15,144(-99.11%)|	27(-99.995%)	|
|Transaction with URL in memo|	89,607(-93.55%)	|10(-97.12%)	|346(-99.97%)|	16(-99.994%)|


We can see the a big drop in low value TRX and TRC10 transactions, and the data meet our expectation, I will continue to focus on the data on-chain and bring you more effects of this proposal.

**Comment by ethan1844** [comment]
Close this issue as it is implemented by [GreatVoyage-v4.7.0.1](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.7.0.1).
Check TIP detail at [TIP-486](https://github.com/tronprotocol/tips/blob/master/tip-486.md)
Check implementation PR at https://github.com/tronprotocol/java-tron/pull/4758
