### ISSUE TITLE
TRC-CRS05: Cross-chain asset transfer

### ISSUE THREAD

**Issue by lvs007** [tronprotocol/tips#49]
# Simple Summary
This doc describes the a solution to cross-chain asset transfer

# Abstract

# Motivation
Realize the transfer of assets between different chains

# Specification
Add a trade-type CrossContract, the transfer process is as follows:

1. Chain A receives a cross-chain transaction, checks the legality of the transaction (signature balance, etc.), and if it is legally placed in pending, waits for the sr node to pack into the block.

2. When the transaction is packaged into the block and cannot be rolled back, the transaction is forwarded to the main chain (sr signature with A chain more than 2/3), and the main chain will verify whether the transaction has more than 2/3 Signature, if it is, package it into the block

3. When the transaction is packaged into the main chain block and cannot be rolled back, the transaction is sent to the B chain (sr signature with the main chain more than 2/3), and the B chain will verify to the main chain whether the transaction has More than 2/3 of the signature, if you have it, package it into the block

Until it is ensured that the transaction is solidified in the B chain, repackage the transaction if the block is rolled back

# Algorithm

# Proto

message CrossContract {
 bytes owner_address = 1;
 int32 owner_version = 2;
 bytes owner_genesisBlockId = 3;
 bytes to_address = 4;
 int32 to_version = 5;
 bytes to_genesisBlockId = 6;
 int64 amount = 7;
}

**Comment by shydesky** [comment]
The tip about cross-chain is moved to the folder "tp/ticp". So we close this issue.
