### ISSUE TITLE
Stake 1.1 - A new TRON staking model based on TRON community feedback

### ISSUE THREAD

**Issue by otakuinny** [tronprotocol/tips#490]
Note: **This model is created by a TRON user and not by a TRON foundation member. This model addresses frequently requested features, improvements and issues that the TRON community has been asking for years.**

### Simple Summary:
This model builds on top of the current staking model and addresses the following issues with the current model.
- Separate staking and resource delegation operations: In the current staking system, freezing TRX would give the account both tron power and tron resource (energy or bandwidth). This is extremely in-efficient as there are several accounts that only freeze trx so they could vote and receive voter rewards. These accounts do not engage in any kind of transactions (like trx transfers, smart contract calls etc) that require bandwidth and energy. Assigning TRON resources to these accounts wastes precious tron resources un-necessarily while increasing the trx necessary to obtain the required resources for everyone else.
- Open up the staking duration period to more than 3 days by making it a value within a range (3-14 days). This will faciliate more trust between the buyers and sellers in the resource rental market
- Treat each resource delegation between 2 accounts separately with their own expiration times so each subsequent delegation does not increase the freeze duration of a previous delegation. This is another hugely helpful feature for the resource rental market users.
- When a delegated resource is used in excess by a receiver account, when the owner account undelegates trx, the resource amount should be reset immediately so when the owner delegates the same trx to another account, that account receives the full resource amount.

***

We propose the following new APIs.

**/wallet/freezebalancev2**

Description: Calling this operation will stake trx in owner_address and gives the account tron power (voting rights). 

Params:

`owner_address` - Address of transaction initiator, data type is string
`frozen_balance` - Amount of TRX to be staked, unit is sun, data type is uint256
`duration` - Minimum amount of time in days the trx should be frozen for. Min of 3 days. Max of 14 days. These values can be changed later using governance proposals
`visible` - Whether the address is in Base58 format, data type is bool

---

**/wallet/unfreezebalancev2**

Description: Calling this operation will unstake trx in owner_address and removes the tron power (voting rights) from the account. Partial unstaking is supported. When this operation is called by passing frozen_balance parameter, the system checks if there is enough undelegated trx amount that >= frozen_balance value. If yes, provided the duration condition of the freezebalancev2 operation is met, the trx is unfrozen.

Params:

`owner_address` - Address of transaction initiator, data type is string
`frozen_balance` - Amount of TRX to be staked, unit is sun, data type is uint256
`duration` - Duration of the freeze
`visible` - Whether the address is in Base58 format, data type is bool

---

**/wallet/delegateresource**

Description: Calling this operation will delegate resource to the receiver_address. The calling account can specify its own address for receiver_address to get resource in the same account. The duration value of this operation should supersede the duration value of freezebalancev2 operation. For example, If account A freezes 100 TRX for 7 days on day 1 and delegates 20 TRX to account B on Day 2 for 10 days, the 20 delegated trx should be locked for 10 days instead of 7 days. The remaining 80 trx can be unfrozen after 7 days.

Params:

`owner_address` - Address of transaction initiator, data type is string
`receiver_address` - Receiver address of resource to be delegated to
`balance` - Amount of TRX staked for resource to be delegated, unit is sun, data type is unit256
`resource` - Resource type, "BANDWIDTH" or "ENERGY", data type is string
`duration` - Number of days the TRX is delegated to receiver_address for. Min of 3 days. Max of 14 days. These values can be changed later using governance proposals
`visible` - Whether the address is in base58 format, data type is bool

_**A note on /delegateresource:**_
The same owner_address should be able to delegate the same resource to the same receiver_address without extending the duration of the previous freezes from the same owner to the same receiver address. For example, if A delegates 100 TRX for energy for 7 days to B and then 5 days later, delegates another 100 TRX for 7 days to B, the duration of the first 100 TRX (which is set to expire in 2 days) should not be extended by 5 more days. These 2 delegations should be treated as separate delegations with their own separate expiration times.

---

**/wallet/undelegateresource**

Description: Calling this operation will un-delegate the frozen TRX to the receiver_address provided the duration is met

Params:

`owner_address` - Address of transaction initiator, data type is string
`receiver_address` - Receiver address of resource to be delegated to
balance - Amount of TRX staked for resource to be undelegated, unit is sun, data type is unit256
resource - Resource type, "BANDWIDTH" or "ENERGY", data type is string
visible - Whether the address is in base58 format, data type is bool

_**A couple of notes on /undelegateresource:**_
When there are multiple delegations from the same owner_address for the same resource to the same receiver_address, each of these delegations should be treated separately. When owner_address calls the undelegateresource operation by passing the balance/resource parameters, the system should check to see if there is currently delegation that matches these parameter values. If a delegation exists, it should undelegate the resource provided the duration is met and throw an error otherwise.

Because of the way resources are replenished after consumption, there currently exists an issue within the current staking model where, in the scenario of resource rental market with an energy seller and a buyer, the buyer can use excess resource on the last day of the rental. Please see the example below.

E.g. Let's say account A freezes 4000 trx to account B which gives B 100K energy on Dec 20 at 00:00

Let's say B uses up all 100k energy in one transaction immediately Dec 20 at 00:00. By Dec 21 00:00, B gets another 100K energy which he uses up immediately again in one transaction. On Dec 22 at 00:00, B gets another 100K energy which is used up immediately as well. Now B used a total of 300K energy which is what he paid for but there is still one full day left until the freeze expires. The freeze will expire on Dec 23 at 00:00 and can't be unfrozen till then. B will have almost 100K energy available again by Dec 22, 23:59 which he can use for free. Even if A unfreezes the 4K trx immediately on Dec 23, 00:00, because B has used up all 100k energy, when A delegates the same 4K trx to another address C, C will have 0 energy. This creates a big problem for the owner in the energy rental market because there is no way for the owner to know how much excess resource is used up by B.

This is a flaw in the current tron staking system. This needs to be fixed so when A delegates 4K trx again to C, C should receive the full 100k energy even if B uses additional 100K energy.

---

Notes from community, devs welcome.

**Comment by otakuinny** [comment]
This proposal addresses all the issues that TIP-467 neglected.

**Comment by ethan1844** [comment]
Please continue the topic in TIP-476

**Comment by otakuinny** [comment]
> Please continue the topic in TIP-476

Do you mean TIP-467?
The tron dev who created the proposal is not responding to the community's questions and seems to have little to no understanding of the staking mechanism and the implications of changing it recklessly.
