### ISSUE TITLE
Proposal: Enable delegate data structure optimization

### ISSUE THREAD

**Issue by lxcmyf** [tronprotocol/tips#492]
# Simple Summary
This proposal aims to optimize the account index storage structure of resource delegating and improve system performance. For more detailed information about delegate data structure optimization, please refer to: [TIP-476](https://github.com/tronprotocol/tips/blob/master/tip-476.md).

# Motivation
For the existing account index storage structure of resource delegating, the read performance of the delegate relationship will drop sharply when the delegate relationship of a certain owner increases, and even seriously affect the execution efficiency of the transactions. We need to optimize the delegate relationship storage structure to improve the network performance and cut the transaction execution time. 

The delegate relationship storage optimization is a dynamic parameter of the TRON network, optimizes the index storage structure of the resource delegate relationship and changes it from a list to a key-value pair, so as to complete the querying and modification of its data in a constant time, which greatly speeds up the execution speed of the delegation related transactions and improves network throughput. 

# Timeline
Any opinions or discussions about this proposal are welcomed.

The estimated timeline

- Creation time of the voting request: 27th December 2022
- The effective time of voting request: 14:00, 30th December 2022

Hi [@TronSpark](https://github.com/TronSpark) [@fbsobreira](https://github.com/fbsobreira), would you please help to raise a proposal to activate it? Thanks a lot.

# How to Initialize the Voting Request
Open asset optimization proposal.

createProposal 69 1

# Performance Test
Tested under 3 different pressure models and got the results of the performance test

## Pressure Model 1

- when the number of delegate relationship is 1

Test Results:

```
Before opening proposal 69, packaged Avg. execution time is 5ms
After opening proposal 69, packaged Avg. execution time is 5ms
```
## Pressure Model 2

- when the number of delegate relationship is 20,000

Test Results:

```
Before opening proposal 69, packaged Avg. execution time is 74ms
After opening proposal 69, packaged Avg. execution time is 6ms
```
## Pressure Model 3

- when the number of delegate relationship is 180,000

Test Results:

```
Before opening proposal 69, packaged Avg. execution time is 620ms
After opening proposal 69, packaged Avg. execution time is 8ms
```

**Comment by sunflower-sun** [comment]
High effective resource delegate transaction is the base of the new stake model. Go ahead.

**Comment by LauraYH** [comment]
As it says above, it utilizes a key-value pair to take the place of the list, the old delegate relationship data, and slice the total time complexity of executing this type of transaction.  I can see the core developers are working with an indomitable will to promote the OS.

**Comment by souppopnix** [comment]
I am interested in *cut the transaction execution time*, keep it up if you have more details. The test results with huge number of delegate relationship seems tempting.

**Comment by jernganl** [comment]
I am glad to see the optimization of data structure.
Judging from the test results, the more relationship, the better the effect.

**Comment by Ademillery** [comment]
With no doubt, as TIP https://github.com/tronprotocol/tips/issues/467 and TIP https://github.com/tronprotocol/tips/issues/484 is going to take effect, the community is expecting to welcome explosive growth of resource delegating market it is necessary to optimize corresponding data storage,  query, statistic, etc. I did not notice that account index storage would cause such obvious execution lag when the number goes to exceed 20,000. If this is the case shown in the performance test, seems new account index storage structure works very well. Meanwhile hope developers conduct whole process performance test with number increase to discover more weak part.

**Comment by otakuinny** [comment]
There is no reason for any one account to do more than a few thousand resource delegations. This proposal is a clear sign that TRON foundation wants to muscle into the energy rental market and use the foundation accounts with billions of trx in them to rent out resources by doing tens of thousands of delegations from each of their accounts.

**Comment by Jackmrshen** [comment]
Based on the performance test result, the new data storage structure is far more efficient when the delegating relation become large, agree with this optimization.

**Comment by L-Reid** [comment]
Using List as delegate relationship storage is not a good choice because of its low efficiency of query. so i'm glad to see optimize the storage structure to a map. Stake and resource market needs efficient delegate transactions.

**Comment by ExOCeo** [comment]
Once implemented, this could be helpful to facilitate the resource delegate market. It is always delightful to see proposals that improve the efficiency of the network and executing speed.

**Comment by ethan1844** [comment]
Thanks to everyone's contribution to this proposal.

This issue will be closed as it is already going to effect, check detail at: https://tronscan.org/#/proposal/81

**Comment by lxcmyf** [comment]
At present, this proposal has been effective for 10 days, comparison of average execution time of unstake related transaction before and after the proposal is shown as follows:

The Number of Maintenance Periods | Average Execution Time Before the Proposal Takes Effect | Average Execution Time After the Proposal Takes Effect
-- | -- | --
1000 | 1 - 1000 ms | 0.08 ms
3000 | 1000 - 5000 ms | 0.09 ms
</google-sheets-html-origin>
The result meets expectation, and I will continue to follow up performance of this proposal.

**Comment by lxcmyf** [comment]
Till now, this proposal has been enabled for 1 month, the actual performance is going as expected.
Here I list the data comparison below, from which we can see that the delegation average execution time remains basically constant as the number of resource delegations increase.
Number of Resource Delegations | FreezeBalance Transactions Average Execution Time Before the Proposal Takes Effect | FreezeBalance Average Execution Time After the Proposal Takes Effect
-- | -- | --
1 | 0.244 ms | 0.75 ms
20,000 | 1.85 ms | 0.75 ms
180,000 | 17.86 ms | 0.75 ms


I will keep following the performance of this proposal continuously.
