### ISSUE TITLE
TIP-522: Lite Fullnode support database auto-pruning

### ISSUE THREAD

**Issue by lurais** [tronprotocol/tips#522]
```
tip: 522
title: Lite Fullnode support database auto-pruning
author: lurais <lurais.p@gmail.com>
discussions to: https://github.com/tronprotocol/tips/issues/522
status: Draft
type: Standards Track
category: Core
created: 2022-02-27
```
## Table of Contents
- [Table of Contents](#table-of-contents)
- [Simple Summary](#simple-summary)
- [Abstract](#abstract)
- [Motivation](#motivation)
- [Specification](#specification)
    - [a.Add customize parameters](#a-add-customize-parameters)
    - [b.Monitor block persistence](#b-monitor-block-persistence)
    - [c.Judge and prune data](#c-judge-and-prune-data)
- [Backwards Compatibility](#backwards-compatibility)

## Simple Summary
This TIP describes the feature of LiteNode data automatical pruning to reduce node database storage occupation.
## Abstract
There are many separate DBs in LiteNode. By analyzing the storage space occupation of each database, a scheme is proposed for cleaning historical data to reduce node database storage occupation.

## Motivation
The storage space occupied by LiteNode data will continue to increase during usage at present. Moreover, the storage space occupied by LiteNode may increase by more than 300GB after half a year according to the current data increase speed (recent data daily increment is about 1.9GB). Most of the increased data come from a few DBs, such as block, transactionRetStore, and trans. And these three DBs account for about 95% of the daily incremental storage space. As a result, it can be seen that LiteNode can dynamically cut the historical data of DBs such as block to reduce most of the storage space occupied.

#### a. Add customize parameters
In order to support machine hardware with different configurations, it is necessary to be able to customize the data pruning function. And the specific parameters planning to provide are as follows:
* chainDataPruneEnable: the pruning function switch, to disable the function by setting it to false.

* chainDataPruneRetain:  the number of latest blocks retained after pruning, which must be greater than 65536, otherwise, it is ignored and the default value of 65536 is used. Pruning can only be performed when the reserved blocks on the disk are greater than this value.

* chainDataPruneBlocksFrequency: the execution frequency of pruning. When it is set to 0, it will be ignored and it will be set to the default value of 1. Pruning can only be executed whenever the difference between the total number of the blocks placed on the disk and the value of chainDataPruneRetain is greater than or equal to the execution frequency of pruning.
```javascript
######### conditionalized prune start
prune {
       # prune enable switch
       chainDataPruneEnable  = false
       # retain number of blocks after prune
       chainDataPruneRetain = 65536
       # number of blocks add to the chain between two prune operations
       chainDataPruneBlocksFrequency = 1
}
######### conditionalized prune start
```
#### b. Monitor block persistence
Since the pruning function of LiteNode needs to use the persisted block data as a basis for judgment, a  block placement monitoring mechanism is added. The details are as follows when the block is persisted, this function will continue to monitor the height of each placed block as one of the judgment conditions for pruning.
```java
public void flush() {
    ......
    refresh();
    flushCount = 0;
    // add prune logic trigger
    ......
}
```
#### c. Judge and prune data
Query and calculate the difference between the total number of the blocks that has persisted and the value of chainDataPruneRetain. When the difference is greater than or equal to the value of chainDataPruneBlocksFrequency , the pruning condition is met, and the pruning will be performed.

## Backwards Compatibility
There are no compatibility issues.

**Comment by ahmadbrainworks** [comment]
Gladly this is now being proposed.

**Comment by souppopnix** [comment]
What's the default value of `chainDataPruneEnable`? I think it should be `true` to enable the pruning by default, cutting space is a good one. Also want to confirm the unit of `chainDataPruneBlocksFrequency`, based on the context, I believe it's block?

**Comment by LauraYH** [comment]
@souppopnix I think it is clear that you need to set `chainDataPruneEnable` to `true` to enable this function. And you are right on the `chainDataPruneBlocksFrequency`, though it is just a number, it is counted by the difference of total blocks placed and the `chainDataPruneRetain`, so its unit is block.

**Comment by lurais** [comment]
> What's the default value of `chainDataPruneEnable`? I think it should be `true` to enable the pruning by default, cutting space is a good one. Also want to confirm the unit of `chainDataPruneBlocksFrequency`, based on the context, I believe it's block?

@souppopnix  , hello ,the default value of `chainDataPruneEnable` is `false` ,this function is designed to cut space and it will take up some machine resources at the same time, you should make your own decision judging to your own machine.And the unit of chainDataPruneBlocksFrequency is block, that's right.

**Comment by lurais** [comment]
> @souppopnix I think it is clear that you need to set `chainDataPruneEnable` to `true` to enable this function. And you are right on the `chainDataPruneBlocksFrequency`, though it is just a number, it is counted by the difference of total blocks placed and the `chainDataPruneRetain`, so its unit is block.
Yes , that's right.

**Comment by halibobo1205** [comment]
@lurais As far as I know, [offline tools](https://tronprotocol.github.io/documentation-en/using_javatron/toolkit/#lite-fullnode-data-pruning) are already available for this purpose. Is this project still going on?

**Comment by lurais** [comment]
> @lurais As far as I know, [offline tools](https://tronprotocol.github.io/documentation-en/using_javatron/toolkit/#lite-fullnode-data-pruning) are already available for this purpose. Is this project still going on?

@halibobo1205 As [offline tools](https://tronprotocol.github.io/documentation-en/using_javatron/toolkit/#lite-fullnode-data-pruning) are already available for this purpose, this project have been stopped.
