### ISSUE TITLE
Stake 2.0 after thoughts and improvements.

### ISSUE THREAD

**Issue by otakuinny** [tronprotocol/tips#539]
Please leave your comments on what you think about Stake 2.0 and suggest improvements if you have any suggestions.

**Comment by ExOCeo** [comment]
The newly added lock period when delegate could be more specific to how many days, put this aside, Stake 2.0 is far more convenient than before when delegating resources to others, the old stake-delegate bonded transaction is silly, maybe it was better to maintain in the back end.

**Comment by amiramir88** [comment]
The new Mechanism is very interesting specially when you delegate your ressources to your other accounts without unfreezing etc.  But the only thing that I do not like is the lock time period, I find the 14 days a very long period.

**Comment by CooperDepp** [comment]
As a long-term TRX holder, I like Stake 2.0, it's a big evolution.

**Comment by ethan1844** [comment]
This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback.
