### ISSUE TITLE
Proposal: Adjust Parameter of Dynamic Energy Model

### ISSUE THREAD

**Issue by daniel-cao-byte** [tronprotocol/tips#540]
# Proposal: Adjust Parameter of Dynamic Energy Model

## Simple Summary

To reasonably distribute resources and make a more robust and balanced ecosystem, the `max_factor` of the Dynamic Energy Model should be adjusted, and meanwhile the unit price of energy should be reduced.

For more details on the Dynamic Energy Model and `max_factor`, please refer to [TIP-491](https://github.com/tronprotocol/tips/issues/491).

## Motivation
The Dynamic Energy Model ([TIP-508](https://github.com/tronprotocol/tips/issues/508)) has been enabled on the main network for more than two months and has achieved remarkable results. The low-value transactions on the chain have been greatly reduced, the proportion of calls to non-popular contracts has significantly increased, the situation of excessively possessed network resources has been significantly improved, and the deflation and stake rate of TRX have also been improved.

However, it can be seen that the distribution of energy consumption on the current chain is still unbalanced, and the proportion of calls to popular contracts is still high. It is recommended that, on the premise of keeping the transaction fee competitive with other main public chains, adjust the `max_factor` in the Dynamic Energy Model properly to further increase the cost of using popular contracts and make the Dynamic Energy Model play a more positive role in balancing resource distribution on the chain and combating low-value transactions.

Since the Dynamic Energy Model can strike against low-value transactions without increasing the cost of using other dApps, this makes space for reducing the unit price of energy. Therefore, it is recommended to appropriately reduce the unit price of energy while increasing the cost of calling popular contracts, in turn, reducing the cost of calling other non-popular contracts and attracting more dApps to join the TRON ecosystem.

## Specifications

Propose to decrease the unit price of energy to 380 sun and set the `max_factor` of the dynamic energy model to 1.8, the proposed parameters are as follows,

- ENERGY_FEE = 380
The No.11 network parameter, means the unit price of energy decreases from 420 sun to 380 sun.

- DYNAMIC_ENERGY_MAX_FACTOR = 18000
The No. 75 network parameter, the precision is 10000, set the `max_factor` parameter in the dynamic energy model to 1.8, `max_factor` is the maximum value of the `energy_factor` variable of the contract. This means that no matter how many maintenance time intervals the energy consumption of popular contracts exceeds the threshold continuously, the maximum `energy_factor` will only increase up to 180%.

For more details on the Dynamic Energy Model, please check [Introduction to Dynamic Energy Model](https://coredevs.medium.com/introduction-to-dynamic-energy-model-31917419b61a).

## How to Initiate the Voting Request

This is the command for initiating the voting request (wallet-cli):

- createProposal 11 380 75 18000

## Analysis

After the Dynamic Energy Model takes effect, low-value transactions are effectively suppressed, and the number of transactions of non-popular smart contracts has increased. However, the proportion of popular smart contracts is yet too high, and the distribution of on-chain resource consumption is still unbalanced. Below is the relevant data analysis.

Compared with the month before the Dynamic Energy Model came into effect, the average daily low-value transaction volume of popular TRC20 in the past month has dropped by 39.11%, while the high-value transaction volume has grown by 5.90%. The data is shown in the table below，

||Popular TRC20 Token Transaction with Value Lower than $ 0.5|Popular TRC20 Token Transaction with Value Higher than $ 0.5|
|:----:|:----:|:----:|
|The average daily  value in 1 month before the TIP-508|  897,438|1,397,657|
|The average daily  value in the recent 1 month|546,484|1,480,149|
|Increase|-39.11%|+5.90%|

The following figure is the volume curve of low-value transactions on-chain after the Dynamic Energy Model was enabled, it is obvious that the curve dropped sharply at the beginning weeks but there is an increasing trend recently,

![low-value-transaction-volume-trend](https://user-images.githubusercontent.com/91414247/234006248-81f56158-cf95-4616-82d0-d923a980f905.png)

Compared with the month before the Dynamic Energy Model took effect, the call volume of non-popular contracts increased by about 2.5 times when the total call volume remained unchanged in the past month, and the proportion of call volume of popular contracts decreased from 96% to 85%. , but overall the proportion of calls to popular smart contracts is yet irrational,

||Total contract calls|Popular contract calls|Non-popular contract calls|
|:----:|:----:|:----:|:----:|
|The average daily  value in 1 month before the TIP-508|2,391,643|2,295,095 (96%)|96,548 (4%)|
|The average daily  value in the recent 1 month|2,369,187|2,026,633 (85%)|342,554 (15%)|

## Impact on TRC20 Transfer Fee

Once the `max_factor` is raised to 1.8, the cost of pupular `TRC20` token transactions would increase, but it is still strongly competitive with the gas fee of `ERC20` token transactions, see below,

|ERC20 Gas Usage|Ethereum Gas Fee|ETH Price|Cost|
|:----:|:----:|:----:|:----:|
|41,000|40 Gwei|$ 1850|$ 3.03|

|TRC20 Energy Usage|TRX Price|Non-popular Token Transfer Cost|Popular Token Transfer Cost|
|:----:|:----:|:----:|:----:|
|15,000|$ 0.066|$ 0.38|$ 1.05|

## Impact on Striking against the Low-value Transactions

After the `max_factor` of the Dynamic Energy Model is increased, the cost of popular smart contracts will be further increased, as well as the cost of low-value transactions involved in popular smart contracts. It is expected that the volume of low-value transactions will be further reduced without affecting other smart contracts in the ecosystem.

## Impact on Deflation

In the short-term, the energy consumption of popular contracts will continue to increase, which will greatly increase the amount of TRX burned, resulting in a continued increase deflation rate of the network. However, as the use of popular contracts decreases subsequently, the network deflation rate will gradually return to normal.

**Comment by CooperDepp** [comment]
The influence of Dynamic Energy model is beyond my expectation, it works, and I have to say TRON is still the best choice for USDT transaction. Dynamic Energy model, Stake 2.0, strx, TRON has speeded up its evolution. But it seems has nothing to do with the TRX price so far, come on, increase the power!

**Comment by ethan1844** [comment]
This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback.
