### ISSUE TITLE
TRC: Support interact with built-in dex in smartcontract

### ISSUE THREAD

**Issue by HiroKryptor** [tronprotocol/tips#55]
**1. What did you do?**
Interact with built-in TRC10 dex in smartcontract for auto swap token.

**2. What did you expect to see?**
Support interact with built-in TRC10 dex in smartcontract

**3. What did you see instead?**
Not supported

**Comment by fbsobreira** [comment]
for auto swap token you don't need built-in dex. Built-int TRC10 maybe cheaper to use but volatility is too high due the bancor mechanism, I rather not use that.

**Comment by Sh11thead** [comment]
seems like your idea is to create a DEX like Uniswap in Ethereum.What kind of function do you need？you can put your thoughts, some details here.

**Comment by shydesky** [comment]
@HiroKryptor  any updates about your thoughts？

**Comment by ethan1844** [comment]
This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback.
