### ISSUE TITLE
ERC20 Token Proposal 

### ISSUE THREAD

**Issue by dbuarque** [tronprotocol/tips#6]
Currently it's not possible to exchange tokens inside TRON Network. However the industry standard ERC20 have been developed. Our proposal is to taken advantage of the open source standard ERC20 and create a new ERC20 standard for TRON. ERC20 is an interface that allows any tokens on TRON to be re-used and exchanged by other applications: from wallets to decentralized exchanges.

**Comment by sullof** [comment]
What about an ERC20-compatible wrapper around native tokens?

**Comment by zhaohong** [comment]
@dbuarque we have implements the   ERC20-compatible  token :)

**Comment by zhaohong** [comment]
For a more convenient understanding， we call our contract token  TRC 20.  Here 20 is not the issue number.
