### ISSUE TITLE
Emergency multi-signature operation guide

### ISSUE THREAD

**Issue by lltx16888** [tronprotocol/tips#627]
I am a layman and know nothing about these aspects. However, because my account has been tampered with by a nasty bad guy, I have been trying for several months and still cannot successfully transfer assets. The transaction must be signed by the bad guy, but according to your tips here The method, change the account permissions, seems to have changed a bit, but when it comes to the final signature, I don’t know how to do it. I hope I can get your help and look forward to your reply: Email lltx16888@gmail.com/lltx16888@qq.com

**Comment by laurenceja** [comment]
@lltx16888 If the account's permission changed, only the accounts with permission can modify the account permission again. So you can check on Tronscan if your account address has the permission. Or show your address here.

**Comment by lltx16888** [comment]
TExPk5wT7pXAjxdZdkN3Yo5RaGCAv1yDhe //This is my account address, please take a look

**Comment by lltx16888** [comment]
> @lltx16888如果账户权限发生变化，只有拥有权限的账户才能再次修改账户权限。所以你可以在Tronscan上查看你的账户地址是否有权限。或者在此处显示您的地址。  My account address should have permissions, because the owner and the active person are two addresses, and the weight is one each, and the total threshold is 2. As your article said, if this is the case, the other party dies unexpectedly. Isn’t it possible to operate according to the method you provided, but I changed it, and the final signature cannot be operated or encoded?

**Comment by lltx16888** [comment]
My account address should have permissions, because the owner and the
active person are two addresses, and the weight is one each, and the total
threshold is 2. As your article said, if this is the case, the other party
dies unexpectedly. Isn’t it possible to operate according to the method you
provided, but I changed it, and the final signature cannot be operated or
encoded?
TExPk5wT7pXAjxdZdkN3Yo5RaGCAv1yDhe //This is my account address, please
take a look
Looking forward eagerly to your reply and your online guidance

laurenceja ***@***.***> 于2023年11月28日周二 16:11写道：

**Comment by laurenceja** [comment]
@lltx16888  TExPk5wT7pXAjxdZdkN3Yo5RaGCAv1yDhe This account has already controlled by another one, so you cannot modify the account's permission again, nobody can help to process it. so please do not trust anyone who can restore account permission or optimize account, they are scammers.
