### ISSUE TITLE
about  DUP_TRANSACTION_ERROR error

### ISSUE THREAD

**Issue by tensecond** [tronprotocol/tips#66]
问题现象：
1、创建一个转账交易，A转B，1trx
2、用C的私钥，对结果签名
3、调用广播交易接口（grpc），得到错误：SIGERROR
4、重复3的步骤，再次发送，得到错误：DUP_TRANSACTION_ERROR

官方微信开发群的解释是：交易第一次广播到节点A，节点A会先缓存起来（可能没上链），交易再次广播到节点A，就会报重复交易

问题：
当重复步骤3的时候，得到的DUP_TRANSACTION_ERROR错误，不再是这个交易原本的错误，即原始错误已经丢失了

希望的结果：
无论重复多少次步骤3，得到的结果应该还是原始错误SIGERROR

注：不止SIGERROR，很多错误，重复发送之后都会得到DUP_TRANSACTION_ERROR

**Comment by zk19862018** [comment]
Hi, this zone is only for TIPS issues, please go to [https://github.com/tronprotocol/java-tron/issues](https://github.com/tronprotocol/java-tron/issues) to create the issue. Thank you!
