### ISSUE TITLE
Why the tips is ordered by tip number, not by created time?

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/tips#666]
It seems more reasonable to order tips  by created time. Developers can track the latest tips.

**Comment by hitlxy** [comment]
@abn2357 In my opinion, TIP file should be name with its unique identifier, that is TIP number. When we talk about a TIP, or search a TIP, it is very convenient to use the TIP number directly. 

The files in all repository are sorted alphabetically based on the file name.

I always find the latest tips through TIP/proposals page or the tip issues page, because they are usually the most popular and discussed recently, or the tips that have just been launched on TRON mainnet.

**Comment by abn2357** [comment]
@hitlxy 
<img width="1086" alt="截屏2024-07-08 16 35 08" src="https://github.com/tronprotocol/tips/assets/165134544/78eb5f55-ea5f-4d9a-89ee-9de571f468f0">
As the above image show, important tips(related to SRs) are not ordered by tip number(column of TIP LINK), it looks good.  The other tips are not related to SRs,  they are mostly related to developers. I think it maybe good to order tips of Tips Guide(image below) by creating time or maintain a list of latest tips ordered by creating time. It will be friendly to developers.
<img width="924" alt="截屏2024-07-08 16 47 54" src="https://github.com/tronprotocol/tips/assets/165134544/c7a07b81-d995-4b6c-8be1-e635eb53fa0b">

**Comment by abn2357** [comment]
> @abn2357 In my opinion, TIP file should be name with its unique identifier, that is TIP number. When we talk about a TIP, or search a TIP, it is very convenient to use the TIP number directly.
> 
> The files in all repository are sorted alphabetically based on the file name.
> 
> I always find the latest tips through TIP/proposals page or the tip issues page, because they are usually the most popular and discussed recently, or the tips that have just been launched on TRON mainnet.

@hitlxy 
<img width="721" alt="截屏2024-07-08 16 52 02" src="https://github.com/tronprotocol/tips/assets/165134544/daeb3873-c616-433a-b27b-9895d3df1512">

As the above image show, important tips(Proposals) are not ordered by tip number(column of TIP LINK), it looks good.  I think it maybe good to order tips of Tips Guide(image below) by creating time or maintain a list of latest tips ordered by creating time like Proposals. It will be friendly to users and developers.

<img width="924" alt="截屏2024-07-08 16 47 54" src="https://github.com/tronprotocol/tips/assets/165134544/2fb3ff05-d152-4adb-a20a-372b8f7beafc">

**Comment by abn2357** [comment]
@hitlxy 
All tips are ordered alphabetically, tips of Tips Guide are ordered by tip number(as a int not as str), it is confused. 
Also users can not get the latest tips by any one of the two orders.

**Comment by L-Reid** [comment]
@abn2357 There are many ways to display the table, but sorting the table by tip number will make it easier for us to find any tip and get the detailed information of it. 

For the latest tips, we can get from [Java-tron releases](https://github.com/tronprotocol/java-tron/releases) and  [TIP issues](https://github.com/tronprotocol/tips/issues). Any Java-tron release may include several tips, any TIP will be discussed at TIP issues page, so we can get the latest tips from the latest release or TIP issues.

**Comment by TARNA95** [comment]
[AccessKey_5923321054688334.csv](https://github.com/user-attachments/files/16321890/AccessKey_5923321054688334.csv)
