### ISSUE TITLE
at go lang i create transation 

### ISSUE THREAD

**Issue by canitakeyourecode** [tronprotocol/tips#673]
But problem i dont make to understand !
 {"code":"CONTRACT_VALIDATE_ERROR","txid":"b3d02ae1b991401c01c2d1323e618df0785646fd7b1c4a629212d7b14e6d6a04","message":"436f6e74726163742076616c6964617465206572726f72203a204e6f20636f6e747261637421"}

or this one !

{"Error":"class java.lang.NullPointerException : null"}

`
package main

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"math/big"
	"net/http"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/mr-tron/base58"
)

const (
	fullNodeURL = "https://api.trongrid.io"
	privateKey  = ""
	apiKey      = ""
)

func main() {
	// Шаг 1: Кодирование параметров
	toAddress := ""
	ownerAddress := ""
	amount := uint64(1000)

	encodedParams, err := encodeParams(toAddress, amount)
	if err != nil {
		log.Fatalf("Ошибка кодирования параметров: %v", err)
	}

	// Шаг 2: Создание транзакции
	txResult, err := createTransaction("", ownerAddress, "transfer(address,uint256)", encodedParams, 0, 5000000)
	if err != nil {
		log.Fatalf("Ошибка создания транзакции: %v", err)
	}

	// Получение данных транзакции
	txData, ok := txResult["transaction"].(map[string]interface{})
	if !ok {
		log.Fatalf("Ошибка получения данных транзакции")
	}
	rawDataHex, ok := txData["raw_data_hex"].(string)
	if !ok {
		log.Fatalf("Ошибка получения raw_data_hex")
	}
	txID, ok := txData["txID"].(string)
	if !ok {
		log.Fatalf("Ошибка получения txID")
	}
	rawData, ok := txData["raw_data"].(map[string]interface{})
	if !ok {
		log.Fatalf("Ошибка получения raw_data")
	}

	// Шаг 3: Подпись транзакции
	signature, err := signTransaction(rawDataHex, privateKey)
	if err != nil {
		log.Fatalf("Ошибка подписания транзакции: %v", err)
	}

	// Выводим на экран подписанные данные для отладки
	fmt.Printf("Подпись транзакции (hex): %s\n", signature)
	fmt.Printf("raw_data_hex перед отправкой: %s\n", rawDataHex)

	// Шаг 4: Подготовка данных для отправки транзакции
	signedTx := map[string]interface{}{
		"txID":         txID,
		"raw_data":     rawData,   // Добавляем raw_data вместо raw_data_hex
		"signature":    signature, // Signature как строка
		"raw_data_hex": rawDataHex,
	}

	// Преобразуем в JSON и выводим для отладки
	jsonData, _ := json.Marshal(signedTx)
	fmt.Printf("JSON запроса на отправку транзакции: %s\n", jsonData)

	result, err := broadcastTransaction(signedTx)
	if err != nil {
		log.Fatalf("Ошибка отправки транзакции: %v", err)
	}

	fmt.Printf("Транзакция успешно отправлена! Результат: %+v\n", result)
}

// Функция кодирования параметров для передачи в контракт
func encodeParams(toAddress string, amount uint64) (string, error) {
	parsedABI, err := abi.JSON(strings.NewReader(`[{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"}]`))
	if err != nil {
		return "", fmt.Errorf("ошибка парсинга ABI: %v", err)
	}

	// Преобразуем адрес назначения в hex
	toAddressHex, err := tronAddressToHex(toAddress)
	if err != nil {
		return "", fmt.Errorf("ошибка конвертации адреса: %v", err)
	}
	fmt.Printf("Hex адрес назначения: %s\n", toAddressHex)

	// Преобразуем uint64 amount в *big.Int
	amountBigInt := big.NewInt(0).SetUint64(amount)

	// Кодирование параметров
	encodedData, err := parsedABI.Pack("transfer", common.HexToAddress(toAddressHex), amountBigInt)
	if err != nil {
		return "", fmt.Errorf("ошибка кодирования параметров: %v", err)
	}

	return hex.EncodeToString(encodedData), nil
}

// Функция для создания транзакции
func createTransaction(contractAddress, ownerAddress, functionSelector, parameter string, callValue, feeLimit int64) (map[string]interface{}, error) {
	url := fullNodeURL + "/wallet/triggersmartcontract"

	parameters := map[string]interface{}{
		"contract_address":  contractAddress,
		"owner_address":     ownerAddress,
		"function_selector": functionSelector,
		"parameter":         parameter,
		"call_value":        callValue,
		"fee_limit":         feeLimit,
		"visible":           true,
	}

	jsonData, err := json.Marshal(parameters)
	if err != nil {
		return nil, fmt.Errorf("ошибка преобразования в JSON: %v", err)
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return nil, fmt.Errorf("ошибка создания запроса: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("TRON-PRO-API-KEY", apiKey)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("ошибка выполнения запроса: %v", err)
	}
	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("ошибка чтения ответа: %v", err)
	}

	var result map[string]interface{}
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("ошибка декодирования ответа: %v", err)
	}

	fmt.Printf("Ответ от создания транзакции: %s\n", string(body))

	if result["result"] != nil && result["result"].(map[string]interface{})["result"] != true {
		message := result["result"].(map[string]interface{})["message"].(string)
		decodedMessage, _ := hex.DecodeString(message)
		return nil, fmt.Errorf("ошибка создания транзакции: %s", decodedMessage)
	}

	return result, nil
}

// Функция для подписи транзакции
func signTransaction(rawDataHex, privateKeyHex string) (string, error) {
	rawData, err := hex.DecodeString(rawDataHex)
	if err != nil {
		return "", fmt.Errorf("ошибка декодирования rawDataHex: %v", err)
	}

	privateKey, err := crypto.HexToECDSA(privateKeyHex)
	if err != nil {
		return "", fmt.Errorf("ошибка декодирования приватного ключа: %v", err)
	}

	hash := crypto.Keccak256(rawData)
	signature, err := crypto.Sign(hash, privateKey)
	if err != nil {
		return "", fmt.Errorf("ошибка подписания: %v", err)
	}

	fmt.Printf("Подпись транзакции (hex): %s\n", hex.EncodeToString(signature))
	return hex.EncodeToString(signature), nil
}

// Функция для отправки подписанной транзакции
func broadcastTransaction(signedTransaction map[string]interface{}) (map[string]interface{}, error) {
	url := fullNodeURL + "/wallet/broadcasttransaction"

	// Преобразование структуры signedTransaction в JSON
	requestBody, err := json.Marshal(signedTransaction)
	if err != nil {
		return nil, fmt.Errorf("ошибка маршалинга данных: %v", err)
	}

	// Вывод отформатированного JSON для отладки
	var prettyJSON bytes.Buffer
	if err := json.Indent(&prettyJSON, requestBody, "", "  "); err != nil {
		return nil, fmt.Errorf("ошибка форматирования JSON: %v", err)
	}
	fmt.Printf("Отправка JSON запроса на отправку транзакции: %s\n", prettyJSON.String())

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(requestBody))
	if err != nil {
		return nil, fmt.Errorf("ошибка создания запроса: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("TRON-PRO-API-KEY", apiKey)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("ошибка выполнения запроса: %v", err)
	}
	defer resp.Body.Close()

	respBody, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("ошибка чтения ответа: %v", err)
	}

	fmt.Printf("Ответ от отправки транзакции: %s\n", string(respBody))

	var result map[string]interface{}
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, fmt.Errorf("ошибка декодирования ответа: %v", err)
	}

	if errorMessage, exists := result["Error"]; exists {
		return nil, fmt.Errorf("ошибка отправки транзакции: %v", errorMessage)
	}

	return result, nil
}

// Функция для конвертации адресов TRON из Base58 в HEX
func tronAddressToHex(address string) (string, error) {
	addressBytes, err := base58.Decode(address)
	if err != nil {
		return "", fmt.Errorf("Ошибка при декодировании base58: %v", err)
	}
	// Убедитесь, что адрес начинается с префикса 0x41 для TRON
	if len(addressBytes) == 0 || addressBytes[0] != 0x41 {
		return "", fmt.Errorf("Недопустимая версия адреса: %x", addressBytes)
	}
	return hex.EncodeToString(addressBytes), nil
}

`

**Comment by Channing0501** [comment]
@canitakeyourecode To convert the error message from hex to string, it is "No contract!", so the contract address may be wrong or the network is not selected correctly.

**Comment by vivian1912** [comment]
@canitakeyourecode This is the repository of TRON improvement proposal, and welcome any suggestions, comments about TRON TIP. But for any issues about Java-tron or Tron transactions, we can raise an issue under [Java-Tron repository](https://github.com/tronprotocol/java-tron/issues). Thanks.
