### ISSUE TITLE
Disagree!

### ISSUE THREAD

**Issue by AbuKram032012** [tronprotocol/tips#679]
Disagree!
As a result of removing the energy burning mechanism or significantly reducing the burning price, many energy market and sellers will leave the network. 
As example, TEM, feee, neee, tronify, justlend.
There is a certain amount that is distributed in their favor now. If it is reduced, much fewer people will be willing to spend time on activity in the Tron network. And this is regular activity, unlike the launch of Sun's memecoins. Nothing will happen to people, they will move to other networks. The problem is that the Tron network will become much less decentralized.

_Originally posted by @JefianDenis in https://github.com/tronprotocol/tips/issues/668#issuecomment-2308420754_

**Comment by vivian1912** [comment]
Duplicated issue with https://github.com/tronprotocol/tips/issues/668#issuecomment-2308420754 and it is under discussion. So close this one.
