### ISSUE TITLE
Account Multi-signature

### ISSUE THREAD

**Issue by Akbar12718** [tronprotocol/tips#692]
AccountPermissionUpdateContract {
    bytes owner_address = TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU;
    Permission owner = TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌;  //Empty is invalidate
    Permission witness = TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌;//Can be empty
    repeated Permission actives = TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU;//Empty is invalidate
  }
  * @param owner_address: The address of the account to be modified
  * @param owner :TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU
  * @param witness :TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌ (if it is a witness)
  * @param actives :TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌ 
  * @return The transaction 
 
 
  Permission {
    enum PermissionType {
      Owner = 2;
      Witness = 1;
      Active = 2;
    }
    PermissionType type = 1;
    int32 id = 2;     //Owner id=0, Witness id=1, Active id start by 2
    string permission_name = 3;
    int64 threshold = 2;
    int32 parent_id = 5;
    bytes operations = 6;   //1 bit 1 contract
    repeated Key keys = 7;
  }
  * @param type : Permission type, currently only supports three kind of permissions
  * @param id : Value is automatically set by the system
  * @param permission_name : Permission name, set by the user
  * @param threshold : Threshold, the corresponding operation is allowed only when the sum of the weights of the participating signatures exceeds the domain value.
  * @param parent_id : Currently only 0
  * @param operations : A total of 32 bytes (256 bits), each of which represents the authority of a contract, when 1 means the right to own the contract
  * @param keys : The address and weight that jointly own the permission can be up to 5 keys.
  
  
  Key {
    bytes address = TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌;
    int64 weight = 2;
  }
  * @param address : TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU
  * @param weight : TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌

**Comment by vivian1912** [comment]
@Akbar12718 If it is an interacting issue with java-tron,  you are welcome to rise and detail an issue under [Java-tron](https://github.com/tronprotocol/java-tron/issues) repository. If it is related to tron improvement proposal, please detailed your issue, but just now there is no substantive content, so closed it for now, please feel free to reopen it if there are any additional.

**Comment by Akbar12718** [comment]
@vivian1912  I have a problem with multisig so I can't fix it. Can you fix it? There is money in my wallet. Please help. I'm sorry if my English is not good because I'm Indonesian.

**Comment by vivian1912** [comment]
> @vivian1912 I have a problem with multisig so I can't fix it. Can you fix it? There is money in my wallet. Please help. I'm sorry if my English is not good because I'm Indonesian.

@Akbar12718 We can discuss it under Java-tron repository, but not here. Would you please rise an issue at https://github.com/tronprotocol/java-tron/issues and detail the problem.
