### ISSUE TITLE
Proposal: Enable Resource Redelegation to Improve Security

### ISSUE THREAD

**Issue by aghamir** [tronprotocol/tips#696]
### Current Situation

To delegate resources to multiple wallets, users are required to stake TRX in hot wallets. This exposes staked TRX to security risks associated with a hot environment, potentially making them vulnerable to hacks or unauthorized access.

### Proposed Solution

Introduce the ability to redelegate resources. This would allow users to:

1. Keep their TRX in a cold wallet (offline storage) for enhanced security.
2. Delegate resources from the cold wallet to a hot wallet.
3. From the hot wallet, dispatch resources as needed to other addresses.

**Benefits:**

- **Enhanced Security:** TRX would remain secure in cold storage, reducing the risk of compromise.
- **Efficient Resource Management:** Users can control and distribute resources from a single hot wallet without exposing their main holdings.

**Comment by lxcmyf** [comment]
In the TRON network, it makes no difference when delegating resources no matter you use a cold or hot wallet when it comes to securty concerning. Your intention might be to achieve indirect or multi-layered delegation of resources, such as where 'a' delegates resources to 'b', and 'b' can then delegate the obtained resources from 'a' to another party, 'c'. However, in Stake 2.0, resources can only be directly delegated from one account to another, without allowing indirect delegation to a third party, as it would increase complexity and potential security risks.

**Comment by KrisdiaPaul** [comment]
I think the redelegation just makes things too complicated. And the operation of staking TRX in cold wallet could not be avoided by adding this type of transaction. So it would not help reduce the risk.

**Comment by endiaoekoe** [comment]
in my understanding,cold wallet mean it won't interact with smart contracts. to achive your goal,the cold wallet needs to permit to other hot wallet;but if you do that ,the cold wallet will not be cold,it become hot wallet.
so ,how can it achive your goal base on your descibtions?

**Comment by CarlChaoCarl** [comment]
In my view, introducing resource redelegation in Tron could increase complexity and, if used improperly, It will introduce new issues.

**Comment by lxcmyf** [comment]
Tron network has always been committed to ensuring transaction security. Additionally, you can further enhance account and asset security by using multi-signature for staking.

**Comment by lxcmyf** [comment]
@aghamir 
I understand your concerns, but please rest assured that things are not as you imagined. After the launch of Stake 2.0, the amount of TRX you staked was only deducted from your account balance and moved to the Tron network's delegating resource database, and was not placed in the hot or cold wallet. When you cancel the staking, the TRX previously stored in the delegating resource database will be re added to your balance through the request interface, which is not related to the hot or cold wallet. The wallet is just a client that sends requests, and you can check your balance, the amount of TRX staked, and the resources obtained by the delegating through the wallet. As for the automatic recycling of delegating resources you mentioned, the Tron network currently does not support this. Tron aims to provide atomic interfaces or instructions, and you can achieve the function of automatic resource recycling by developing smart contracts.

**Comment by CarlChaoCarl** [comment]
> @lxcmyf,
> 
> If I understand your position correctly, you're concerned that redelegation adds more complexity and security risks than it resolves.
> 
> First, there are alternative methods beyond using `FreezeBalanceV2` that could enable redelegation without altering the current flow.
> 
> Second, we shouldn't ignore the underlying issue. **Where should I store my TRX?** Stake v2 effectively forces me to keep it in hot wallets, unless you can tell me there is another way I can freeze TRX.
> 
> I want to re-elaborate issue once more:
> 
> 1. **Secure Storage of TRX for Freezing:** I want to securely store a large amount of TRX for the purpose of freezing.
> 2. **Dynamic Delegation of Resources:** I need the ability to delegate resources to other addresses dynamically—that is, whenever I want to extract their assets.
> 3. **Automation of Delegation Process:** I want the process in step 2 to be automated.

@aghamir 

For the first point you mentioned, you can use multisignature to ensure security.

**Comment by aghamir** [comment]
Thanks you for giving me your time. I will close this issue as I see you are trying to solve the problem with atomic interface.
