### ISSUE TITLE
{   "Error": "class org.tron.core.services.http.JsonFormat$ParseException : 1:1: Expected \"{\"." }

### ISSUE THREAD

**Issue by Rafazzzz** [tronprotocol/tips#701]
![-5319124603492230651_121](https://github.com/user-attachments/assets/c3f98572-7a1b-4649-84ac-8b65a4a9b5e3)

**Comment by vivian1912** [comment]
@Rafazzzz For the interactive issue with TRON node, would you please rise an issue at [Java-tron repository](https://github.com/tronprotocol/java-tron/issues), and detail it? Community members will help to solve your issue there more effective. So just closing this one, thanks.
